// ignore_for_file: unused_element, unused_field

part of 'image_editor_screen.dart';

enum _CanvasLayerType { photo, text, sticker }

enum _ExportImageFormat { png, pngTransparent, jpg, psd, pdf }

enum _BottomPrimaryTool { none, photo, text, background }

enum _BottomInlineMode {
  none,
  layers,
  stickerCategories,
  stickerItems,
  border,
  photoEraser,
}

enum _LayerStyleQuickTab { stroke, shadow, glow, colorOverlay, gradient }

enum _BorderStyle { none, thinWhite, thinBlack, rounded, glow, custom }

const double _topBarHeight = 86;
const double _bottomBarHeight = 66;
const double _cropBarHeight = 120;
const double _adjustBarHeight = 180;
const double _eraserBarHeight = 160;
const double _stretchBarHeight = 202;
const double _drawBarHeight = 112;
const double _textStyleBarHeight = 224;
const double _layerStyleQuickPanelHeight = 92;
const double _canvasChromeInset = 18;

final List<Color> _textColors = List<Color>.unmodifiable(
  editorBackgroundColors.take(50),
);

const List<String> _stickerCategories = <String>[
  'Emojis',
  'DesignPro Shapes',
  'Callouts',
  'SVG Marks',
  'Shapes',
  'Hearts',
  'Stars',
  'Festival',
  'Political',
];

const Map<String, List<String>> _stickerCatalog = <String, List<String>>{
  'Emojis': <String>['😀', '😁', '😎', '🥳', '❤️', '✨'],
  'DesignPro Shapes': <String>[
    'assets/designpro_reference_full/assets/shapes/circle.svg',
    'assets/designpro_reference_full/assets/shapes/square.svg',
    'assets/designpro_reference_full/assets/shapes/rectangle.svg',
    'assets/designpro_reference_full/assets/shapes/triangle.svg',
    'assets/designpro_reference_full/assets/shapes/star.svg',
    'assets/designpro_reference_full/assets/shapes/heart.svg',
    'assets/designpro_reference_full/assets/shapes/arrow.svg',
    'assets/designpro_reference_full/assets/shapes/cloud.svg',
    'assets/designpro_reference_full/assets/shapes/crown.svg',
    'assets/designpro_reference_full/assets/shapes/diamond.svg',
    'assets/designpro_reference_full/assets/shapes/hexagon.svg',
    'assets/designpro_reference_full/assets/shapes/octagon.svg',
    'assets/designpro_reference_full/assets/shapes/lightning.svg',
    'assets/designpro_reference_full/assets/shapes/flower.svg',
    'assets/designpro_reference_full/assets/shapes/sunflower1.svg',
    'assets/designpro_reference_full/assets/shapes/paint_line.svg',
    'assets/designpro_reference_full/assets/shapes/boom.svg',
    'assets/designpro_reference_full/assets/shapes/callout.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_circle.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_square.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_star.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_triangle.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_heart.svg',
  ],
  'Callouts': <String>[
    'assets/designpro_reference_full/assets/callouts/callout_cloud.svg',
    'assets/designpro_reference_full/assets/callouts/callout_dest_bubble.svg',
    'assets/designpro_reference_full/assets/callouts/callout_dest_triangle.svg',
    'assets/designpro_reference_full/assets/callouts/callout_oval.svg',
    'assets/designpro_reference_full/assets/callouts/callout_rectangle.svg',
    'assets/designpro_reference_full/assets/callouts/callout_round_rectangle.svg',
    'assets/designpro_reference_full/assets/callouts/callout_shape_1.svg',
    'assets/designpro_reference_full/assets/callouts/callout_shape_2.svg',
    'assets/designpro_reference_full/assets/callouts/callout_shape_4.svg',
    'assets/designpro_reference_full/assets/callouts/callout_shape_5.svg',
    'assets/designpro_reference_full/assets/callouts/callout_shape_6.svg',
    'assets/designpro_reference_full/assets/callouts/i_message_1.svg',
    'assets/designpro_reference_full/assets/callouts/i_message_2.svg',
    'assets/designpro_reference_full/assets/callouts/i_message_3.svg',
    'assets/designpro_reference_full/assets/callouts/i_message_4.svg',
    'assets/designpro_reference_full/assets/callouts/valentine_cloud.svg',
    'assets/designpro_reference_full/assets/callouts/valentine_red_heart.svg',
  ],
  'SVG Marks': <String>[
    'assets/designpro_reference_full/assets/shapes/default_shape_x.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_star.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_star_2.svg',
    'assets/designpro_reference_full/assets/shapes/default_shape_heart.svg',
    'assets/designpro_reference_full/assets/shapes/arrow.svg',
    'assets/designpro_reference_full/assets/shapes/lightning.svg',
    'assets/designpro_reference_full/assets/shapes/paint_line.svg',
    'assets/designpro_reference_full/assets/shapes/boom.svg',
    'assets/designpro_reference_full/assets/shapes/lines.svg',
    'assets/designpro_reference_full/assets/shapes/drops.svg',
    'assets/designpro_reference_full/assets/shapes/foot_print.svg',
    'assets/designpro_reference_full/assets/shapes/crown.svg',
    'assets/designpro_reference_full/assets/shapes/cloud_down.svg',
    'assets/designpro_reference_full/assets/shapes/melt.svg',
  ],
  'Shapes': <String>[
    '●',
    '○',
    '◐',
    '◑',
    '■',
    '□',
    '▣',
    '▢',
    '◆',
    '◇',
    '◈',
    '▲',
    '△',
    '▼',
    '▽',
    '◀',
    '▶',
    '◁',
    '▷',
    '⬟',
    '⬢',
    '⬡',
    '★',
    '☆',
    '✦',
    '✧',
    '✚',
    '✖',
    '✓',
    '✔',
    '⬆',
    '⬇',
    '⬅',
    '➡',
    '↗',
    '↘',
    '↙',
    '↖',
    '━',
    '┃',
    '┏',
    '┓',
    '┗',
    '┛',
    '⌜',
    '⌝',
    '⌞',
    '⌟',
    '⬛',
    '⬜',
    '🔶',
    '🔷',
    '🔺',
    '🔻',
  ],
  'Hearts': <String>['❤️', '💚', '💙', '💜', '🧡', '💕'],
  'Stars': <String>['⭐', '🌟', '✨', '💫', '🔆', '✳️'],
  'Festival': <String>['🎉', '🎊', '🪔', '🪙', '🕯️', '🌸'],
  'Political': <String>[],
};

final List<List<Color>> _textGradients = List<List<Color>>.unmodifiable(
  editorBackgroundGradients
      .map((gradient) => List<Color>.unmodifiable(gradient))
      .toList(growable: false),
);

const List<String> _textFontFamilies = <String>[
  'Anek Telugu Condensed Regular',
  'Anek Telugu Condensed Bold',
  'Anek Telugu Condensed Extra Bold',
  'Anek Telugu Condensed Extra Light',
  'Anek Telugu Condensed Light',
  'Anek Telugu Condensed Medium',
  'Noto Sans Telugu Condensed Black',
  'Noto Sans Telugu Condensed Bold',
  'Noto Sans Telugu Condensed Extra Bold',
  'Noto Sans Telugu Condensed Extra Light',
  'Noto Sans Telugu Condensed Light',
  'Aaradhana',
  'Abhilasha',
  'Ajantha',
  'Akshara',
  'Amrutha',
  'Anjali',
  'Anu Subhalekha Two',
  'Anupama Bold',
  'Anupama Extra Bold',
  'Anupama Medium',
  'Anupama Thin',
  'Anusha',
  'Apoorva',
  'Ashwini',
  'Bapu Bold',
  'Bapu Brush',
  'Bapu Script',
  'Bharghava',
  'Bhavya',
  'Brahma',
  'Brahma Script',
  'Chandra Script',
  'Deepika',
  'Dharani',
  'Geetha',
  'Gowthami Black',
  'Gowthami Bold',
  'Gowthami Extra Bold',
  'Gowthami Medium',
  'Gowthami Narrow',
  'Gowthami Thin',
  'Harsha',
  'Hiranya',
  'Jyothi',
  'Kalaanjali',
  'Keerthi Font',
  'Kranthi',
  'Kusuma',
  'Maanasa',
  'Madhubala',
  'Meena Script',
  'Mohini',
  'Natyamayuri',
  'Neelima',
  'Padmini',
  'Pallavi Bold',
  'Pallavi Medium',
  'Pallavi Thin',
  'Prabhava',
  'Pragathi',
  'Pragathi Italic',
  'Pragathi Narrow',
  'Pragathi Special',
  'Preethi',
  'Pridhvi',
  'Priyaanka',
  'Priyaanka Bold',
  'Rachana',
  'Rachana Bold',
  'Ramana Brush',
  'Ramana Script',
  'Ramana Script Medium',
  'Ravali',
  'Reshma',
  'Rohini',
  'Saagari',
  'Sanghavi',
  'Sowmya',
  'Sravya',
  'Subhadra',
  'Suchithra',
  'Sujatha',
  'Suneetha',
  'Supriya',
  'Tejafont',
  'Thripura',
  'Udayam',
  'Vaibhav',
  'Vasantha',
  'Vasundhara',
  'Veenaa',
  'Vikaas',
];

const List<String> _englishTextFontFamilies = <String>[
  'Anton',
  'Archivo Black',
  'Bebas Neue',
  'League Spartan',
  'Montserrat',
  'Playfair Display',
  'Poppins',
  'Rasa',
  'Oswald',
  'Lobster',
  'Pacifico',
  'Dancing Script',
  'Great Vibes',
  'Abril Fatface',
  'Bangers',
  'Cinzel',
  'Cormorant Garamond',
  'Lora',
  'Raleway',
  'Roboto Slab',
  'Rubik',
  'Nunito',
  'Caveat',
];

const List<String> _hindiTextFontFamilies = <String>[
  'Noto Sans Devanagari',
  'Noto Serif Devanagari',
  'Hind',
  'Teko',
  'Rajdhani',
  'Baloo 2',
  'Kalam',
  'Yatra One',
  'Gotu',
  'Mukta',
  'Arya',
  'Martel',
  'Sarpanch',
  'Kurale',
  'Rozha One',
];

const List<String> _allTextFontFamilies = <String>[
  ..._textFontFamilies,
  ..._englishTextFontFamilies,
  ..._hindiTextFontFamilies,
];
