// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5A9-RoKLvae3S1e3vij31Vj_0JifMu1o',
    appId: '1:1093335255199:web:987809f0af53e7cb1bfaaa',
    messagingSenderId: '1093335255199',
    projectId: 'mana-poster-ap',
    authDomain: 'mana-poster-ap.firebaseapp.com',
    databaseURL: 'https://mana-poster-ap-default-rtdb.firebaseio.com',
    storageBucket: 'mana-poster-ap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_SrDCjsg-DmWGP3A7Gq6dqTj7AH9q5w',
    appId: '1:1093335255199:android:2b3e0d1f5edfb17c1bfaaa',
    messagingSenderId: '1093335255199',
    projectId: 'mana-poster-ap',
    databaseURL: 'https://mana-poster-ap-default-rtdb.firebaseio.com',
    storageBucket: 'mana-poster-ap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbsLSsy1vdFO-8feUkK6-xI_qS6ex9C3k',
    appId: '1:1093335255199:ios:091f4173a3458f8f1bfaaa',
    messagingSenderId: '1093335255199',
    projectId: 'mana-poster-ap',
    databaseURL: 'https://mana-poster-ap-default-rtdb.firebaseio.com',
    storageBucket: 'mana-poster-ap.firebasestorage.app',
    androidClientId: '1093335255199-epku2qvq4engjo8m7a80qt8oavnp77up.apps.googleusercontent.com',
    iosClientId: '1093335255199-ar6eh077lj97rhbfhvak4vi2dftr1bdl.apps.googleusercontent.com',
    iosBundleId: 'com.telugutouch.manaposter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5A9-RoKLvae3S1e3vij31Vj_0JifMu1o',
    appId: '1:1093335255199:web:54d47979558f9cfa1bfaaa',
    messagingSenderId: '1093335255199',
    projectId: 'mana-poster-ap',
    authDomain: 'mana-poster-ap.firebaseapp.com',
    databaseURL: 'https://mana-poster-ap-default-rtdb.firebaseio.com',
    storageBucket: 'mana-poster-ap.firebasestorage.app',
  );
}