import 'package:mana_poster/features/prehome/models/dynamic_category.dart';

abstract class DynamicEventRepository {
  const DynamicEventRepository();

  List<DynamicCalendarEvent> loadEvents();
}

class LocalDynamicEventRepository implements DynamicEventRepository {
  const LocalDynamicEventRepository();

  @override
  List<DynamicCalendarEvent> loadEvents() => localSeedDynamicEvents;
}

const List<DynamicCalendarEvent> localSeedDynamicEvents =
    <DynamicCalendarEvent>[
      DynamicCalendarEvent(
        id: 'new_year_day',
        slug: 'new_year_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.global,
        priority: 88,
        sortOrder: 10,
        startMonth: 1,
        startDay: 1,
        title: DynamicLocalizedTitle(
          telugu: 'నూతన సంవత్సర శుభాకాంక్షలు',
          english: 'New Year Special',
          hindi: 'नव वर्ष विशेष',
        ),
        tags: <String>['new_year', 'important_day', 'celebration'],
      ),
      DynamicCalendarEvent(
        id: 'national_youth_day',
        slug: 'national_youth_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 82,
        sortOrder: 20,
        startMonth: 1,
        startDay: 12,
        title: DynamicLocalizedTitle(
          telugu: 'జాతీయ యువజన దినోత్సవం',
          english: 'National Youth Day',
          hindi: 'राष्ट्रीय युवा दिवस',
        ),
        tags: <String>['india', 'important_day', 'youth'],
      ),
      DynamicCalendarEvent(
        id: 'makara_sankranti',
        slug: 'makara_sankranti',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.bothTeluguStates,
        priority: 96,
        sortOrder: 30,
        startMonth: 1,
        startDay: 14,
        durationDays: 3,
        title: DynamicLocalizedTitle(
          telugu: 'సంక్రాంతి స్పెషల్',
          english: 'Sankranti Special',
          hindi: 'संक्रांति विशेष',
        ),
        tags: <String>['festival', 'sankranti', 'harvest', 'devotional'],
      ),
      DynamicCalendarEvent(
        id: 'army_day',
        slug: 'army_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 78,
        sortOrder: 40,
        startMonth: 1,
        startDay: 15,
        title: DynamicLocalizedTitle(
          telugu: 'ఆర్మీ డే',
          english: 'Army Day',
          hindi: 'आर्मी डे',
        ),
        tags: <String>['india', 'important_day', 'army'],
      ),
      DynamicCalendarEvent(
        id: 'gandhi_vardhanthi',
        slug: 'gandhi_vardhanthi',
        type: DynamicCategoryType.vardhanthi,
        scope: DynamicEventScope.india,
        priority: 84,
        sortOrder: 50,
        startMonth: 1,
        startDay: 30,
        title: DynamicLocalizedTitle(
          telugu: 'మహాత్మా గాంధీ వర్ధంతి',
          english: 'Mahatma Gandhi Vardhanthi',
          hindi: 'महात्मा गांधी पुण्यतिथि',
        ),
        tags: <String>['india', 'vardhanthi', 'gandhi'],
      ),
      DynamicCalendarEvent(
        id: 'international_mother_language_day',
        slug: 'mother_language_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.global,
        priority: 76,
        sortOrder: 60,
        startMonth: 2,
        startDay: 21,
        title: DynamicLocalizedTitle(
          telugu: 'అంతర్జాతీయ మాతృభాషా దినోత్సవం',
          english: 'International Mother Language Day',
          hindi: 'अंतरराष्ट्रीय मातृभाषा दिवस',
        ),
        tags: <String>['important_day', 'language', 'global'],
      ),
      DynamicCalendarEvent(
        id: 'womens_day',
        slug: 'international_womens_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.global,
        priority: 83,
        sortOrder: 70,
        startMonth: 3,
        startDay: 8,
        title: DynamicLocalizedTitle(
          telugu: 'అంతర్జాతీయ మహిళా దినోత్సవం',
          english: 'International Women’s Day',
          hindi: 'अंतरराष्ट्रीय महिला दिवस',
        ),
        tags: <String>['important_day', 'women', 'global'],
      ),
      DynamicCalendarEvent(
        id: 'world_health_day',
        slug: 'world_health_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.global,
        priority: 75,
        sortOrder: 80,
        startMonth: 4,
        startDay: 7,
        title: DynamicLocalizedTitle(
          telugu: 'ప్రపంచ ఆరోగ్య దినోత్సవం',
          english: 'World Health Day',
          hindi: 'विश्व स्वास्थ्य दिवस',
        ),
        tags: <String>['important_day', 'health', 'global'],
      ),
      DynamicCalendarEvent(
        id: 'ambedkar_jayanthi',
        slug: 'ambedkar_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.india,
        priority: 95,
        sortOrder: 90,
        startMonth: 4,
        startDay: 14,
        title: DynamicLocalizedTitle(
          telugu: 'డా. బి.ఆర్. అంబేద్కర్ జయంతి',
          english: 'Dr. B.R. Ambedkar Jayanti',
          hindi: 'डॉ. बी.आर. आंबेडकर जयंती',
        ),
        tags: <String>['india', 'jayanthi', 'ambedkar'],
      ),
      DynamicCalendarEvent(
        id: 'labour_day',
        slug: 'labour_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 80,
        sortOrder: 100,
        startMonth: 5,
        startDay: 1,
        title: DynamicLocalizedTitle(
          telugu: 'కార్మిక దినోత్సవం',
          english: 'Labour Day',
          hindi: 'मज़दूर दिवस',
        ),
        tags: <String>['india', 'important_day', 'labour'],
      ),
      DynamicCalendarEvent(
        id: 'alluri_sitarama_raju_vardhanthi',
        slug: 'alluri_sitarama_raju_vardhanthi',
        type: DynamicCategoryType.vardhanthi,
        scope: DynamicEventScope.andhraPradesh,
        priority: 85,
        sortOrder: 110,
        startMonth: 5,
        startDay: 7,
        title: DynamicLocalizedTitle(
          telugu: 'అల్లూరి సీతారామరాజు వర్ధంతి',
          english: 'Alluri Sitarama Raju Vardhanthi',
          hindi: 'अल्लूरी सीताराम राजू पुण्यतिथि',
        ),
        tags: <String>['andhra_pradesh', 'vardhanthi', 'alluri'],
      ),
      DynamicCalendarEvent(
        id: 'ntr_jayanthi',
        slug: 'ntr_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.andhraPradesh,
        priority: 92,
        sortOrder: 120,
        startMonth: 5,
        startDay: 28,
        title: DynamicLocalizedTitle(
          telugu: 'ఎన్.టి.ఆర్ జయంతి',
          english: 'N.T.R. Jayanti',
          hindi: 'एन.टी.आर जयंती',
        ),
        tags: <String>['andhra_pradesh', 'jayanthi', 'ntr', 'political'],
      ),
      DynamicCalendarEvent(
        id: 'telangana_formation_day',
        slug: 'telangana_formation_day',
        type: DynamicCategoryType.regionalSpecial,
        scope: DynamicEventScope.telangana,
        priority: 97,
        sortOrder: 130,
        startMonth: 6,
        startDay: 2,
        title: DynamicLocalizedTitle(
          telugu: 'తెలంగాణ ఆవిర్భావ దినోత్సవం',
          english: 'Telangana Formation Day',
          hindi: 'तेलंगाना स्थापना दिवस',
        ),
        tags: <String>['telangana', 'regional_special', 'formation_day'],
      ),
      DynamicCalendarEvent(
        id: 'environment_day',
        slug: 'world_environment_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.global,
        priority: 77,
        sortOrder: 140,
        startMonth: 6,
        startDay: 5,
        title: DynamicLocalizedTitle(
          telugu: 'ప్రపంచ పర్యావరణ దినోత్సవం',
          english: 'World Environment Day',
          hindi: 'विश्व पर्यावरण दिवस',
        ),
        tags: <String>['important_day', 'environment', 'global'],
      ),
      DynamicCalendarEvent(
        id: 'international_yoga_day',
        slug: 'international_yoga_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 81,
        sortOrder: 150,
        startMonth: 6,
        startDay: 21,
        title: DynamicLocalizedTitle(
          telugu: 'అంతర్జాతీయ యోగా దినోత్సవం',
          english: 'International Yoga Day',
          hindi: 'अंतरराष्ट्रीय योग दिवस',
        ),
        tags: <String>['india', 'important_day', 'yoga', 'health'],
      ),
      DynamicCalendarEvent(
        id: 'pv_narasimha_rao_jayanthi',
        slug: 'pv_narasimha_rao_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.telangana,
        priority: 90,
        sortOrder: 160,
        startMonth: 6,
        startDay: 28,
        title: DynamicLocalizedTitle(
          telugu: 'పీ.వి. నరసింహరావు జయంతి',
          english: 'P.V. Narasimha Rao Jayanti',
          hindi: 'पी.वी. नरसिम्हा राव जयंती',
        ),
        tags: <String>['telangana', 'jayanthi', 'pv_narasimha_rao'],
      ),
      DynamicCalendarEvent(
        id: 'doctors_day',
        slug: 'national_doctors_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 79,
        sortOrder: 170,
        startMonth: 7,
        startDay: 1,
        title: DynamicLocalizedTitle(
          telugu: 'డాక్టర్స్ డే',
          english: 'National Doctors’ Day',
          hindi: 'राष्ट्रीय डॉक्टर्स डे',
        ),
        tags: <String>['india', 'important_day', 'doctors'],
      ),
      DynamicCalendarEvent(
        id: 'alluri_sitarama_raju_jayanthi',
        slug: 'alluri_sitarama_raju_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.andhraPradesh,
        priority: 89,
        sortOrder: 180,
        startMonth: 7,
        startDay: 4,
        title: DynamicLocalizedTitle(
          telugu: 'అల్లూరి సీతారామరాజు జయంతి',
          english: 'Alluri Sitarama Raju Jayanti',
          hindi: 'अल्लूरी सीताराम राजू जयंती',
        ),
        tags: <String>['andhra_pradesh', 'jayanthi', 'alluri'],
      ),
      DynamicCalendarEvent(
        id: 'ysr_jayanthi',
        slug: 'ysr_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.andhraPradesh,
        priority: 91,
        sortOrder: 190,
        startMonth: 7,
        startDay: 8,
        title: DynamicLocalizedTitle(
          telugu: 'వైఎస్‌ఆర్ జయంతి',
          english: 'Y.S.R. Jayanti',
          hindi: 'वाई.एस.आर जयंती',
        ),
        tags: <String>['andhra_pradesh', 'jayanthi', 'ysr', 'political'],
      ),
      DynamicCalendarEvent(
        id: 'prof_jayashankar_jayanthi',
        slug: 'prof_jayashankar_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.telangana,
        priority: 87,
        sortOrder: 200,
        startMonth: 8,
        startDay: 6,
        title: DynamicLocalizedTitle(
          telugu: 'ప్రొ. జయశంకర్ జయంతి',
          english: 'Prof. Jayashankar Jayanti',
          hindi: 'प्रो. जयशंकर जयंती',
        ),
        tags: <String>['telangana', 'jayanthi', 'jayashankar'],
      ),
      DynamicCalendarEvent(
        id: 'independence_day',
        slug: 'independence_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 100,
        sortOrder: 210,
        startMonth: 8,
        startDay: 15,
        title: DynamicLocalizedTitle(
          telugu: 'స్వాతంత్ర్య దినోత్సవం',
          english: 'Independence Day Special',
          hindi: 'स्वतंत्रता दिवस विशेष',
        ),
        tags: <String>['india', 'important_day', 'independence_day'],
      ),
      DynamicCalendarEvent(
        id: 'tanguturi_prakasam_jayanthi',
        slug: 'tanguturi_prakasam_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.andhraPradesh,
        priority: 84,
        sortOrder: 220,
        startMonth: 8,
        startDay: 23,
        title: DynamicLocalizedTitle(
          telugu: 'టంగుటూరి ప్రకాశం పంతులు జయంతి',
          english: 'Tanguturi Prakasam Jayanti',
          hindi: 'टंगुटूरि प्रकाशम जयंती',
        ),
        tags: <String>['andhra_pradesh', 'jayanthi', 'prakasam'],
      ),
      DynamicCalendarEvent(
        id: 'telugu_language_day',
        slug: 'telugu_language_day',
        type: DynamicCategoryType.regionalSpecial,
        scope: DynamicEventScope.bothTeluguStates,
        priority: 94,
        sortOrder: 230,
        startMonth: 8,
        startDay: 29,
        title: DynamicLocalizedTitle(
          telugu: 'తెలుగు భాషా దినోత్సవం',
          english: 'Telugu Language Day',
          hindi: 'तेलुगु भाषा दिवस',
        ),
        tags: <String>['both_telugu_states', 'regional_special', 'language'],
      ),
      DynamicCalendarEvent(
        id: 'teachers_day',
        slug: 'teachers_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 86,
        sortOrder: 240,
        startMonth: 9,
        startDay: 5,
        title: DynamicLocalizedTitle(
          telugu: 'ఉపాధ్యాయ దినోత్సవం',
          english: 'Teachers’ Day',
          hindi: 'शिक्षक दिवस',
        ),
        tags: <String>['india', 'important_day', 'teachers'],
      ),
      DynamicCalendarEvent(
        id: 'kaloji_jayanthi',
        slug: 'kaloji_narayana_rao_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.telangana,
        priority: 88,
        sortOrder: 250,
        startMonth: 9,
        startDay: 9,
        title: DynamicLocalizedTitle(
          telugu: 'కాళోజి నారాయణరావు జయంతి',
          english: 'Kaloji Narayana Rao Jayanti',
          hindi: 'कालोजी नारायण राव जयंती',
        ),
        tags: <String>['telangana', 'jayanthi', 'kaloji'],
      ),
      DynamicCalendarEvent(
        id: 'ysr_vardhanthi',
        slug: 'ysr_vardhanthi',
        type: DynamicCategoryType.vardhanthi,
        scope: DynamicEventScope.andhraPradesh,
        priority: 90,
        sortOrder: 260,
        startMonth: 9,
        startDay: 2,
        title: DynamicLocalizedTitle(
          telugu: 'వైఎస్‌ఆర్ వర్ధంతి',
          english: 'Y.S.R. Vardhanthi',
          hindi: 'वाई.एस.आर पुण्यतिथि',
        ),
        tags: <String>['andhra_pradesh', 'vardhanthi', 'ysr', 'political'],
      ),
      DynamicCalendarEvent(
        id: 'gandhi_jayanthi',
        slug: 'gandhi_jayanthi',
        type: DynamicCategoryType.jayanthi,
        scope: DynamicEventScope.india,
        priority: 98,
        sortOrder: 270,
        startMonth: 10,
        startDay: 2,
        title: DynamicLocalizedTitle(
          telugu: 'మహాత్మా గాంధీ జయంతి',
          english: 'Mahatma Gandhi Jayanti',
          hindi: 'महात्मा गांधी जयंती',
        ),
        tags: <String>['india', 'jayanthi', 'gandhi'],
      ),
      DynamicCalendarEvent(
        id: 'national_unity_day',
        slug: 'national_unity_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 79,
        sortOrder: 280,
        startMonth: 10,
        startDay: 31,
        title: DynamicLocalizedTitle(
          telugu: 'జాతీయ ఏకతా దినోత్సవం',
          english: 'National Unity Day',
          hindi: 'राष्ट्रीय एकता दिवस',
        ),
        tags: <String>['india', 'important_day', 'unity'],
      ),
      DynamicCalendarEvent(
        id: 'andhra_pradesh_formation_day',
        slug: 'andhra_pradesh_formation_day',
        type: DynamicCategoryType.regionalSpecial,
        scope: DynamicEventScope.andhraPradesh,
        priority: 93,
        sortOrder: 290,
        startMonth: 11,
        startDay: 1,
        title: DynamicLocalizedTitle(
          telugu: 'ఆంధ్రప్రదేశ్ ఆవిర్భావ దినోత్సవం',
          english: 'Andhra Pradesh Formation Day',
          hindi: 'आंध्र प्रदेश स्थापना दिवस',
        ),
        tags: <String>['andhra_pradesh', 'regional_special', 'formation_day'],
      ),
      DynamicCalendarEvent(
        id: 'childrens_day',
        slug: 'childrens_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 82,
        sortOrder: 300,
        startMonth: 11,
        startDay: 14,
        title: DynamicLocalizedTitle(
          telugu: 'బాలల దినోత్సవం',
          english: 'Children’s Day',
          hindi: 'बाल दिवस',
        ),
        tags: <String>['india', 'important_day', 'children'],
      ),
      DynamicCalendarEvent(
        id: 'constitution_day',
        slug: 'constitution_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 84,
        sortOrder: 310,
        startMonth: 11,
        startDay: 26,
        title: DynamicLocalizedTitle(
          telugu: 'రాజ్యాంగ దినోత్సవం',
          english: 'Constitution Day',
          hindi: 'संविधान दिवस',
        ),
        tags: <String>['india', 'important_day', 'constitution'],
      ),
      DynamicCalendarEvent(
        id: 'potti_sriramulu_vardhanthi',
        slug: 'potti_sriramulu_vardhanthi',
        type: DynamicCategoryType.vardhanthi,
        scope: DynamicEventScope.andhraPradesh,
        priority: 88,
        sortOrder: 320,
        startMonth: 12,
        startDay: 15,
        title: DynamicLocalizedTitle(
          telugu: 'పొట్టి శ్రీరాములు వర్ధంతి',
          english: 'Potti Sriramulu Vardhanthi',
          hindi: 'पोट्टि श्रीरामुलु पुण्यतिथि',
        ),
        tags: <String>['andhra_pradesh', 'vardhanthi', 'potti_sriramulu'],
      ),
      DynamicCalendarEvent(
        id: 'national_farmers_day',
        slug: 'national_farmers_day',
        type: DynamicCategoryType.importantDay,
        scope: DynamicEventScope.india,
        priority: 80,
        sortOrder: 330,
        startMonth: 12,
        startDay: 23,
        title: DynamicLocalizedTitle(
          telugu: 'జాతీయ రైతు దినోత్సవం',
          english: 'National Farmers’ Day',
          hindi: 'राष्ट्रीय किसान दिवस',
        ),
        tags: <String>['india', 'important_day', 'farmers'],
      ),
      DynamicCalendarEvent(
        id: 'christmas',
        slug: 'christmas',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.global,
        priority: 91,
        sortOrder: 340,
        startMonth: 12,
        startDay: 25,
        title: DynamicLocalizedTitle(
          telugu: 'క్రిస్మస్ స్పెషల్',
          english: 'Christmas Special',
          hindi: 'क्रिसमस विशेष',
        ),
        tags: <String>['festival', 'christmas', 'global'],
      ),
      DynamicCalendarEvent(
        id: 'ugadi_placeholder',
        slug: 'ugadi',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.bothTeluguStates,
        priority: 99,
        sortOrder: 350,
        calendarType: DynamicCalendarType.lunarPlaceholder,
        enabled: false,
        title: DynamicLocalizedTitle(
          telugu: 'ఉగాది స్పెషల్',
          english: 'Ugadi Special',
          hindi: 'उगादि विशेष',
        ),
        tags: <String>['festival', 'ugadi', 'lunar_pending'],
      ),
      DynamicCalendarEvent(
        id: 'sri_rama_navami_placeholder',
        slug: 'sri_rama_navami',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.bothTeluguStates,
        priority: 99,
        sortOrder: 360,
        calendarType: DynamicCalendarType.lunarPlaceholder,
        enabled: false,
        title: DynamicLocalizedTitle(
          telugu: 'శ్రీరామ నవమి స్పెషల్',
          english: 'Sri Rama Navami Special',
          hindi: 'श्री राम नवमी विशेष',
        ),
        tags: <String>['festival', 'rama_navami', 'lunar_pending'],
      ),
      DynamicCalendarEvent(
        id: 'bonalu_placeholder',
        slug: 'bonalu',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.telangana,
        priority: 98,
        sortOrder: 370,
        calendarType: DynamicCalendarType.lunarPlaceholder,
        enabled: false,
        title: DynamicLocalizedTitle(
          telugu: 'బోనాలు స్పెషల్',
          english: 'Bonalu Special',
          hindi: 'बोनालु विशेष',
        ),
        tags: <String>['festival', 'bonalu', 'telangana', 'lunar_pending'],
      ),
      DynamicCalendarEvent(
        id: 'bathukamma_placeholder',
        slug: 'bathukamma',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.telangana,
        priority: 98,
        sortOrder: 380,
        calendarType: DynamicCalendarType.lunarPlaceholder,
        enabled: false,
        title: DynamicLocalizedTitle(
          telugu: 'బతుకమ్మ స్పెషల్',
          english: 'Bathukamma Special',
          hindi: 'बथुकम्मा विशेष',
        ),
        tags: <String>['festival', 'bathukamma', 'telangana', 'lunar_pending'],
      ),
      DynamicCalendarEvent(
        id: 'vinayaka_chavithi_placeholder',
        slug: 'vinayaka_chavithi',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.bothTeluguStates,
        priority: 97,
        sortOrder: 390,
        calendarType: DynamicCalendarType.lunarPlaceholder,
        enabled: false,
        title: DynamicLocalizedTitle(
          telugu: 'వినాయక చవితి స్పెషల్',
          english: 'Vinayaka Chavithi Special',
          hindi: 'विनायक चतुर्थी विशेष',
        ),
        tags: <String>['festival', 'vinayaka', 'lunar_pending'],
      ),
      DynamicCalendarEvent(
        id: 'deepavali_placeholder',
        slug: 'deepavali',
        type: DynamicCategoryType.festival,
        scope: DynamicEventScope.india,
        priority: 98,
        sortOrder: 400,
        calendarType: DynamicCalendarType.lunarPlaceholder,
        enabled: false,
        title: DynamicLocalizedTitle(
          telugu: 'దీపావళి స్పెషల్',
          english: 'Deepavali Special',
          hindi: 'दीपावली विशेष',
        ),
        tags: <String>['festival', 'deepavali', 'lunar_pending'],
      ),
    ];
