import 'package:mana_poster/features/prehome/models/dynamic_category.dart';

const List<List<Object>> _fixedGregorianSeedRows = <List<Object>>[
  ['bhogi', 'Bhogi', 'భోగి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90, 1, 13],
  ['kanuma', 'Kanuma', 'కనుమ', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90, 1, 15],
  ['mukkanuma', 'Mukkanuma', 'ముక్కనుమ', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70, 1, 16],
  ['christmas', 'Christmas', 'క్రిస్మస్', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70, 12, 25],
  ['yogi_vemana_jayanthi', 'Yogi Vemana Jayanthi', 'యోగి వేమన జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 1, 19],
  ['n_t_rama_rao_vardhanthi', 'N.T. Rama Rao Vardhanthi', 'ఎన్.టి.రామారావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 90, 1, 18],
  ['damodaram_sanjivayya_jayanthi', 'Damodaram Sanjivayya Jayanthi', 'దామోదరం సంజీవయ్య జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 2, 14],
  ['potti_sreeramulu_jayanthi', 'Potti Sreeramulu Jayanthi', 'పొట్టి శ్రీరాములు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 3, 16],
  ['kandukuri_veeresalingam_jayanthi', 'Kandukuri Veeresalingam Jayanthi', 'కందుకూరి వీరేశలింగం జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 4, 16],
  ['n_t_rama_rao_jayanthi', 'N.T. Rama Rao Jayanthi', 'ఎన్.టి.రామారావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 5, 28],
  ['kandukuri_veeresalingam_vardhanthi', 'Kandukuri Veeresalingam Vardhanthi', 'కందుకూరి వీరేశలింగం వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 5, 27],
  ['alluri_sitarama_raju_jayanthi', 'Alluri Sitarama Raju Jayanthi', 'అల్లూరి సీతారామరాజు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 7, 4],
  ['y_s_rajasekhara_reddy_jayanthi', 'Y.S. Rajasekhara Reddy Jayanthi', 'వై.ఎస్. రాజశేఖర రెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 7, 8],
  ['tanguturi_prakasam_panthulu_jayanthi', 'Tanguturi Prakasam Panthulu Jayanthi', 'టంగుటూరి ప్రకాశం పంతులు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 8, 23],
  ['gurajada_apparao_jayanthi', 'Gurajada Apparao Jayanthi', 'గురజాడ అప్పారావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 9, 21],
  ['y_s_rajasekhara_reddy_vardhanthi', 'Y.S. Rajasekhara Reddy Vardhanthi', 'వై.ఎస్. రాజశేఖర రెడ్డి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 90, 9, 2],
  ['andhra_state_formation_day', 'Andhra State Formation Day', 'ఆంధ్ర రాష్ట్ర ఆవిర్భావ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.andhraPradesh, 70, 10, 1],
  ['potti_sreeramulu_vardhanthi_atmarpana_dinotsavam', 'Potti Sreeramulu Vardhanthi / Atmarpana Dinotsavam', 'పొట్టి శ్రీరాములు వర్ధంతి / ఆత్మార్పణ దినోత్సవం', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 90, 12, 15],
  ['andhra_pradesh_formation_day', 'Andhra Pradesh Formation Day', 'ఆంధ్రప్రదేశ్ ఆవిర్భావ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.andhraPradesh, 90, 11, 1],
  ['viswakarma_jayanthi', 'Viswakarma Jayanthi', 'విశ్వకర్మ జయంతి', DynamicCategoryType.festival, DynamicEventScope.andhraPradesh, 70, 9, 17],
  ['damodaram_sanjivayya_vardhanthi', 'Damodaram Sanjivayya Vardhanthi', 'దామోదరం సంజీవయ్య వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 5, 7],
  ['gurajada_apparao_vardhanthi', 'Gurajada Apparao Vardhanthi', 'గురజాడ అప్పారావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 11, 30],
  ['sant_sevalal_maharaj_jayanthi', 'Sant Sevalal Maharaj Jayanthi', 'సంత్ సేవాలాల్ మహారాజ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 2, 15],
  ['komaram_bheem_vardhanthi', 'Komaram Bheem Vardhanthi', 'కొమరం భీం వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 90, 10, 7],
  ['telangana_formation_day', 'Telangana Formation Day', 'తెలంగాణ ఆవిర్భావ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.telangana, 90, 6, 2],
  ['p_v_narasimha_rao_jayanthi', 'P.V. Narasimha Rao Jayanthi', 'పి.వి. నరసింహరావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 6, 28],
  ['prof_kothapalli_jayashankar_jayanthi', 'Prof. Kothapalli Jayashankar Jayanthi', 'ప్రొఫెసర్ కొత్తపల్లి జయశంకర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 8, 6],
  ['kaloji_narayana_rao_jayanthi', 'Kaloji Narayana Rao Jayanthi', 'కాళోజి నారాయణరావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 9, 9],
  ['chityala_ilamma_vardhanthi', 'Chityala Ilamma Vardhanthi', 'చిట్యాల ఐలమ్మ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 90, 9, 10],
  ['praja_palana_dinotsavam', 'Praja Palana Dinotsavam', 'ప్రజా పాలన దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.telangana, 70, 9, 17],
  ['komaram_bheem_jayanthi', 'Komaram Bheem Jayanthi', 'కొమరం భీం జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 10, 22],
  ['p_v_narasimha_rao_vardhanthi', 'P.V. Narasimha Rao Vardhanthi', 'పి.వి. నరసింహరావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 90, 12, 23],
  ['kaloji_narayana_rao_vardhanthi', 'Kaloji Narayana Rao Vardhanthi', 'కాళోజి నారాయణరావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 11, 13],
  ['telangana_liberation_integration_memory_day_usage_variants', 'Telangana Liberation / Integration memory day usage variants', 'తెలంగాణ విమోచన / విలీన స్మృతి దిన వినియోగం', DynamicCategoryType.importantDay, DynamicEventScope.telangana, 50, 9, 17],
  ['swami_vivekananda_jayanthi', 'Swami Vivekananda Jayanthi', 'స్వామి వివేకానంద జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 1, 12],
  ['netaji_subhas_chandra_bose_jayanthi', 'Netaji Subhas Chandra Bose Jayanthi', 'నేతాజీ సుభాస్ చంద్రబోస్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 1, 23],
  ['lala_lajpat_rai_jayanthi', 'Lala Lajpat Rai Jayanthi', 'లాలా లజపత్ రాయ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 1, 28],
  ['swami_dayananda_saraswati_jayanthi', 'Swami Dayananda Saraswati Jayanthi', 'స్వామి దయానంద సరస్వతి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 2, 12],
  ['chhatrapati_shivaji_maharaj_jayanthi', 'Chhatrapati Shivaji Maharaj Jayanthi', 'ఛత్రపతి శివాజీ మహారాజ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 2, 19],
  ['sarojini_naidu_jayanthi', 'Sarojini Naidu Jayanthi', 'సరోజిని నాయుడు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 2, 13],
  ['babu_jagjivan_ram_jayanthi', 'Babu Jagjivan Ram Jayanthi', 'బాబూ జగ్జీవన్ రామ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 4, 5],
  ['dr_b_r_ambedkar_jayanthi', 'Dr. B.R. Ambedkar Jayanthi', 'డా. బి.ఆర్. అంబేద్కర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 4, 14],
  ['rabindranath_tagore_jayanthi', 'Rabindranath Tagore Jayanthi', 'రవీంద్రనాథ్ ఠాగూర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 5, 7],
  ['veer_savarkar_jayanthi', 'Veer Savarkar Jayanthi', 'వీర్ సావర్కర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 5, 28],
  ['jawaharlal_nehru_jayanthi', 'Jawaharlal Nehru Jayanthi', 'జవహర్‌లాల్ నెహ్రూ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 11, 14],
  ['rajiv_gandhi_jayanthi_sadbhavana_diwas', 'Rajiv Gandhi Jayanthi / Sadbhavana Diwas', 'రాజీవ్ గాంధీ జయంతి / సద్భావనా దివస్', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 8, 20],
  ['mangal_pandey_jayanthi', 'Mangal Pandey Jayanthi', 'మంగళ్ పాండే జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 50, 7, 19],
  ['bal_gangadhar_tilak_jayanthi', 'Bal Gangadhar Tilak Jayanthi', 'బాల గంగాధర్ తిలక్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 7, 23],
  ['chandrashekhar_azad_jayanthi', 'Chandrashekhar Azad Jayanthi', 'చంద్రశేఖర్ ఆజాద్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 7, 23],
  ['dr_sarvepalli_radhakrishnan_jayanthi', 'Dr. Sarvepalli Radhakrishnan Jayanthi', 'డా. సర్వేపల్లి రాధాకృష్ణన్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 9, 5],
  ['bhagat_singh_jayanthi', 'Bhagat Singh Jayanthi', 'భగత్‌సింగ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 9, 28],
  ['mahatma_gandhi_jayanthi', 'Mahatma Gandhi Jayanthi', 'మహాత్మా గాంధీ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 10, 2],
  ['lal_bahadur_shastri_jayanthi', 'Lal Bahadur Shastri Jayanthi', 'లాల్ బహాదూర్ శాస్త్రి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 10, 2],
  ['sardar_vallabhbhai_patel_jayanthi', 'Sardar Vallabhbhai Patel Jayanthi', 'సర్దార్ వల్లభభాయ్ పటేల్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 10, 31],
  ['rani_lakshmibai_jayanthi', 'Rani Lakshmibai Jayanthi', 'రాణి లక్ష్మీబాయి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 11, 19],
  ['indira_gandhi_jayanthi', 'Indira Gandhi Jayanthi', 'ఇందిరా గాంధీ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 11, 19],
  ['birsa_munda_jayanthi_janjatiya_gaurav_divas', 'Birsa Munda Jayanthi / Janjatiya Gaurav Divas', 'బిర్సా ముండా జయంతి / జనజాతీయ గౌరవ దివస్', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 11, 15],
  ['a_p_j_abdul_kalam_jayanthi', 'A.P.J. Abdul Kalam Jayanthi', 'ఏ.పి.జె. అబ్దుల్ కలాం జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 10, 15],
  ['lal_bahadur_shastri_vardhanthi', 'Lal Bahadur Shastri Vardhanthi', 'లాల్ బహాదూర్ శాస్త్రి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 1, 11],
  ['mahatma_gandhi_vardhanthi_martyrs_day', 'Mahatma Gandhi Vardhanthi / Martyrs’ Day', 'మహాత్మా గాంధీ వర్ధంతి / అమరవీరుల దినం', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 90, 1, 30],
  ['chhatrapati_shivaji_maharaj_vardhanthi', 'Chhatrapati Shivaji Maharaj Vardhanthi', 'ఛత్రపతి శివాజీ మహారాజ్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 4, 3],
  ['dr_b_r_ambedkar_vardhanthi_mahaparinirvan_diwas', 'Dr. B.R. Ambedkar Vardhanthi / Mahaparinirvan Diwas', 'డా. బి.ఆర్. అంబేద్కర్ వర్ధంతి / మహాపరినిర్వాణ దివస్', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 90, 12, 6],
  ['shaheed_diwas_bhagat_singh_rajguru_sukhdev', 'Shaheed Diwas (Bhagat Singh, Rajguru, Sukhdev)', 'శహీద్ దివస్', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 90, 3, 23],
  ['jawaharlal_nehru_vardhanthi', 'Jawaharlal Nehru Vardhanthi', 'జవహర్‌లాల్ నెహ్రూ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 5, 27],
  ['rajiv_gandhi_vardhanthi_anti_terrorism_day', 'Rajiv Gandhi Vardhanthi / Anti-Terrorism Day', 'రాజీవ్ గాంధీ వర్ధంతి / ఉగ్రవాద వ్యతిరేక దినం', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 5, 21],
  ['babu_jagjivan_ram_vardhanthi', 'Babu Jagjivan Ram Vardhanthi', 'బాబూ జగ్జీవన్ రామ్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 7, 6],
  ['a_p_j_abdul_kalam_vardhanthi', 'A.P.J. Abdul Kalam Vardhanthi', 'ఏ.పి.జె. అబ్దుల్ కలాం వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 90, 7, 27],
  ['subhas_chandra_bose_vardhanthi', 'Subhas Chandra Bose Vardhanthi', 'సుభాస్ చంద్రబోస్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 8, 18],
  ['vinoba_bhave_vardhanthi', 'Vinoba Bhave Vardhanthi', 'వినోబా భావే వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 50, 11, 15],
  ['indira_gandhi_vardhanthi', 'Indira Gandhi Vardhanthi', 'ఇందిరా గాంధీ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 10, 31],
  ['sardar_vallabhbhai_patel_vardhanthi', 'Sardar Vallabhbhai Patel Vardhanthi', 'సర్దార్ వల్లభభాయ్ పటేల్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 12, 15],
  ['rabindranath_tagore_vardhanthi', 'Rabindranath Tagore Vardhanthi', 'రవీంద్రనాథ్ ఠాగూర్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 50, 8, 7],
  ['national_youth_day', 'National Youth Day', 'జాతీయ యువజన దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 1, 12],
  ['army_day', 'Army Day', 'సైన్య దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 1, 15],
  ['national_girl_child_day', 'National Girl Child Day', 'జాతీయ బాలిక దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 1, 24],
  ['national_voters_day', 'National Voters’ Day', 'జాతీయ ఓటర్ల దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 1, 25],
  ['republic_day', 'Republic Day', 'గణతంత్ర దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 1, 26],
  ['martyrs_day', 'Martyrs’ Day', 'అమరవీరుల దినం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 1, 30],
  ['national_science_day', 'National Science Day', 'జాతీయ విజ్ఞాన దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 2, 28],
  ['international_women_s_day', 'International Women’s Day', 'అంతర్జాతీయ మహిళా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 3, 8],
  ['world_water_day', 'World Water Day', 'ప్రపంచ జల దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 3, 22],
  ['world_health_day', 'World Health Day', 'ప్రపంచ ఆరోగ్య దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 4, 7],
  ['national_civil_services_day', 'National Civil Services Day', 'జాతీయ సివిల్ సర్వీసెస్ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 50, 4, 21],
  ['labour_day_may_day', 'Labour Day / May Day', 'కార్మిక దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 5, 1],
  ['national_technology_day', 'National Technology Day', 'జాతీయ సాంకేతిక దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 5, 11],
  ['world_environment_day', 'World Environment Day', 'ప్రపంచ పర్యావరణ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 6, 5],
  ['international_yoga_day', 'International Yoga Day', 'అంతర్జాతీయ యోగా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 6, 21],
  ['national_doctors_day', 'National Doctors’ Day', 'జాతీయ వైద్యుల దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 7, 1],
  ['kargil_vijay_diwas', 'Kargil Vijay Diwas', 'కార్గిల్ విజయ్ దివస్', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 7, 26],
  ['independence_day', 'Independence Day', 'స్వాతంత్ర్య దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 8, 15],
  ['national_sports_day', 'National Sports Day', 'జాతీయ క్రీడా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 8, 29],
  ['teachers_day', 'Teachers’ Day', 'ఉపాధ్యాయ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 9, 5],
  ['hindi_diwas', 'Hindi Diwas', 'హిందీ దివస్', DynamicCategoryType.importantDay, DynamicEventScope.india, 50, 9, 14],
  ['gandhi_jayanti_international_day_of_non_violence', 'Gandhi Jayanti / International Day of Non-Violence', 'గాంధీ జయంతి / అహింసా దినం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 10, 2],
  ['national_unity_day', 'National Unity Day', 'జాతీయ ఐక్యతా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 10, 31],
  ['constitution_day_samvidhan_divas', 'Constitution Day / Samvidhan Divas', 'రాజ్యాంగ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 11, 26],
  ['national_education_day', 'National Education Day', 'జాతీయ విద్యా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 11, 11],
  ['children_s_day', 'Children’s Day', 'బాలల దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 11, 14],
  ['armed_forces_flag_day', 'Armed Forces Flag Day', 'సాయుధ దళాల జెండా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 12, 7],
  ['kisan_diwas_national_farmers_day', 'Kisan Diwas / National Farmers’ Day', 'జాతీయ రైతు దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 12, 23],
  ['good_governance_day', 'Good Governance Day', 'సుశాసన దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 12, 25],
  ['sri_krishnadevaraya_jayanthi', 'Sri Krishnadevaraya Jayanthi', 'శ్రీకృష్ణదేవరాయ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 1, 17],
  ['nara_lokesh_jayanthi', 'Nara Lokesh Jayanthi', 'నారా లోకేష్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 1, 23],
  ['n_chandrababu_naidu_jayanthi', 'N. Chandrababu Naidu Jayanthi', 'ఎన్. చంద్రబాబు నాయుడు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 4, 20],
  ['kodela_siva_prasada_rao_jayanthi', 'Kodela Siva Prasada Rao Jayanthi', 'కొడెల శివప్రసాదరావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 5, 2],
  ['puchalapalli_sundarayya_jayanthi', 'Puchalapalli Sundarayya Jayanthi', 'పుచ్చలపల్లి సుందరయ్య జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 5, 1],
  ['annamacharya_jayanthi', 'Annamacharya Jayanthi', 'అన్నమాచార్య జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 5, 9],
  ['tyagaraja_jayanthi', 'Tyagaraja Jayanthi', 'త్యాగరాజ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 5, 4],
  ['pawan_kalyan_jayanthi', 'Pawan Kalyan Jayanthi', 'పవన్ కళ్యాణ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 9, 2],
  ['vangaveeti_mohana_ranga_vardhanthi', 'Vangaveeti Mohana Ranga Vardhanthi', 'వంగవీటి మోహన రంగా వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 12, 26],
  ['kodela_siva_prasada_rao_vardhanthi', 'Kodela Siva Prasada Rao Vardhanthi', 'కొడెల శివప్రసాదరావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 9, 16],
  ['puchalapalli_sundarayya_vardhanthi', 'Puchalapalli Sundarayya Vardhanthi', 'పుచ్చలపల్లి సుందరయ్య వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 5, 19],
  ['annamacharya_vardhanthi', 'Annamacharya Vardhanthi', 'అన్నమాచార్య వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 2, 23],
  ['k_chandrashekar_rao_jayanthi', 'K. Chandrashekar Rao Jayanthi', 'కె. చంద్రశేఖర్ రావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 2, 17],
  ['burgula_ramakrishna_rao_jayanthi', 'Burgula Ramakrishna Rao Jayanthi', 'బూర్గుల రామకృష్ణారావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 3, 13],
  ['ravi_narayana_reddy_jayanthi', 'Ravi Narayana Reddy Jayanthi', 'రావి నారాయణ రెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 6, 4],
  ['k_t_rama_rao_jayanthi', 'K.T. Rama Rao Jayanthi', 'కేటీఆర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 7, 24],
  ['dasarathi_krishnamacharyulu_jayanthi', 'Dasarathi Krishnamacharyulu Jayanthi', 'దాశరథి కృష్ణమాచార్యులు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 7, 22],
  ['a_revanth_reddy_jayanthi', 'A. Revanth Reddy Jayanthi', 'ఎ. రేవంత్ రెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 11, 8],
  ['suravaram_pratap_reddy_jayanthi', 'Suravaram Pratap Reddy Jayanthi', 'సురవరం ప్రతాప్ రెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 5, 28],
  ['konda_laxman_bapuji_jayanthi', 'Konda Laxman Bapuji Jayanthi', 'కొండా లక్ష్మణ్ బాపూజి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 9, 27],
  ['marri_chenna_reddy_jayanthi', 'Marri Chenna Reddy Jayanthi', 'మర్రి చెన్నారెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 1, 13],
  ['burgula_ramakrishna_rao_vardhanthi', 'Burgula Ramakrishna Rao Vardhanthi', 'బూర్గుల రామకృష్ణారావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 9, 15],
  ['ravi_narayana_reddy_vardhanthi', 'Ravi Narayana Reddy Vardhanthi', 'రావి నారాయణ రెడ్డి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 9, 7],
  ['dasarathi_krishnamacharyulu_vardhanthi', 'Dasarathi Krishnamacharyulu Vardhanthi', 'దాశరథి కృష్ణమాచార్యులు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 11, 5],
  ['suravaram_pratap_reddy_vardhanthi', 'Suravaram Pratap Reddy Vardhanthi', 'సురవరం ప్రతాప్ రెడ్డి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 8, 25],
  ['konda_laxman_bapuji_vardhanthi', 'Konda Laxman Bapuji Vardhanthi', 'కొండా లక్ష్మణ్ బాపూజి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 9, 21],
  ['marri_chenna_reddy_vardhanthi', 'Marri Chenna Reddy Vardhanthi', 'మర్రి చెన్నారెడ్డి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 12, 2],
  ['savitribai_phule_jayanthi', 'Savitribai Phule Jayanthi', 'సావిత్రిబాయి ఫూలే జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 1, 3],
  ['kalpana_chawla_jayanthi', 'Kalpana Chawla Jayanthi', 'కల్పనా చావ్లా జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 3, 17],
  ['ram_manohar_lohia_jayanthi', 'Ram Manohar Lohia Jayanthi', 'రామ్ మనోహర్ లోహియా జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 3, 23],
  ['jyotirao_phule_jayanthi', 'Jyotirao Phule Jayanthi', 'జ్యోతిరావ్ ఫూలే జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 4, 11],
  ['syama_prasad_mookerjee_jayanthi', 'Syama Prasad Mookerjee Jayanthi', 'శ్యామ ప్రసాద్ ముఖర్జీ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 7, 6],
  ['vikram_sarabhai_jayanthi', 'Vikram Sarabhai Jayanthi', 'విక్రమ్ సారాభాయ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 8, 12],
  ['m_s_swaminathan_jayanthi', 'M.S. Swaminathan Jayanthi', 'ఎం.ఎస్. స్వామినాథన్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 8, 7],
  ['periyar_e_v_ramasamy_jayanthi', 'Periyar E.V. Ramasamy Jayanthi', 'పెరియార్ ఈ.వి.రామస్వామి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 9, 17],
  ['deendayal_upadhyaya_jayanthi', 'Deendayal Upadhyaya Jayanthi', 'దీన్‌దయాళ్ ఉపాధ్యాయ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 9, 25],
  ['homi_j_bhabha_jayanthi', 'Homi J. Bhabha Jayanthi', 'హోమీ జె. భాభా జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 10, 30],
  ['dhyan_chand_jayanthi', 'Dhyan Chand Jayanthi', 'ధ్యాన్ చంద్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 8, 29],
  ['madan_mohan_malaviya_jayanthi', 'Madan Mohan Malaviya Jayanthi', 'మదన్ మోహన్ మాలవ్య జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 12, 25],
  ['atal_bihari_vajpayee_jayanthi', 'Atal Bihari Vajpayee Jayanthi', 'అటల్ బిహారీ వాజ్‌పేయి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 90, 12, 25],
  ['udham_singh_jayanthi', 'Udham Singh Jayanthi', 'ఉధమ్ సింగ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 12, 26],
  ['savitribai_phule_vardhanthi', 'Savitribai Phule Vardhanthi', 'సావిత్రిబాయి ఫూలే వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 3, 10],
  ['kalpana_chawla_vardhanthi', 'Kalpana Chawla Vardhanthi', 'కల్పనా చావ్లా వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 2, 1],
  ['deendayal_upadhyaya_vardhanthi', 'Deendayal Upadhyaya Vardhanthi', 'దీన్‌దయాళ్ ఉపాధ్యాయ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 2, 11],
  ['homi_j_bhabha_vardhanthi', 'Homi J. Bhabha Vardhanthi', 'హోమీ జె. భాభా వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 1, 24],
  ['jyotirao_phule_vardhanthi', 'Jyotirao Phule Vardhanthi', 'జ్యోతిరావ్ ఫూలే వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 90, 11, 28],
  ['syama_prasad_mookerjee_vardhanthi', 'Syama Prasad Mookerjee Vardhanthi', 'శ్యామ ప్రసాద్ ముఖర్జీ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 6, 23],
  ['vikram_sarabhai_vardhanthi', 'Vikram Sarabhai Vardhanthi', 'విక్రమ్ సారాభాయ్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 12, 30],
  ['dhyan_chand_vardhanthi', 'Dhyan Chand Vardhanthi', 'ధ్యాన్ చంద్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 50, 12, 3],
  ['m_s_swaminathan_vardhanthi', 'M.S. Swaminathan Vardhanthi', 'ఎం.ఎస్. స్వామినాథన్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 9, 28],
  ['periyar_e_v_ramasamy_vardhanthi', 'Periyar E.V. Ramasamy Vardhanthi', 'పెరియార్ ఈ.వి.రామస్వామి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 12, 24],
  ['ram_manohar_lohia_vardhanthi', 'Ram Manohar Lohia Vardhanthi', 'రామ్ మనోహర్ లోహియా వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 10, 12],
  ['atal_bihari_vajpayee_vardhanthi', 'Atal Bihari Vajpayee Vardhanthi', 'అటల్ బిహారీ వాజ్‌పేయి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 90, 8, 16],
  ['sushma_swaraj_jayanthi', 'Sushma Swaraj Jayanthi', 'సుష్మా స్వరాజ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 2, 14],
  ['sushma_swaraj_vardhanthi', 'Sushma Swaraj Vardhanthi', 'సుష్మా స్వరాజ్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 8, 6],
  ['madan_mohan_malaviya_vardhanthi', 'Madan Mohan Malaviya Vardhanthi', 'మదన్ మోహన్ మాలవ్య వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 11, 12],
  ['udham_singh_vardhanthi', 'Udham Singh Vardhanthi', 'ఉధమ్ సింగ్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 7, 31],
  ['national_mathematics_day', 'National Mathematics Day', 'జాతీయ గణిత దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 12, 22],
  ['national_handloom_day', 'National Handloom Day', 'జాతీయ హ్యాండ్లూమ్ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 8, 7],
  ['national_legal_services_day', 'National Legal Services Day', 'జాతీయ న్యాయ సేవల దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 50, 11, 9],
  ['national_maritime_day', 'National Maritime Day', 'జాతీయ సముద్ర దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 50, 4, 5],
  ['national_unity_day_run_for_unity_use_case', 'National Unity Day (Run for Unity use-case)', 'జాతీయ ఐక్యతా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 10, 31],
  ['y_s_jagan_mohan_reddy_jayanthi', 'Y.S. Jagan Mohan Reddy Jayanthi', 'వై.ఎస్. జగన్ మోహన్ రెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 12, 21],
  ['nandamuri_balakrishna_jayanthi', 'Nandamuri Balakrishna Jayanthi', 'నందమూరి బాలకృష్ణ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 6, 10],
  ['akkineni_nageswara_rao_jayanthi', 'Akkineni Nageswara Rao Jayanthi', 'అక్కినేని నాగేశ్వరరావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 9, 20],
  ['akkineni_nageswara_rao_vardhanthi', 'Akkineni Nageswara Rao Vardhanthi', 'అక్కినేని నాగేశ్వరరావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 90, 1, 22],
  ['nandamuri_taraka_rama_rao_jr_jayanthi', 'Nandamuri Taraka Rama Rao Jr. Jayanthi', 'నందమూరి తారక రామారావు జూనియర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 5, 20],
  ['s_v_ranga_rao_jayanthi', 'S. V. Ranga Rao Jayanthi', 'ఎస్.వి. రంగారావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 7, 3],
  ['s_v_ranga_rao_vardhanthi', 'S. V. Ranga Rao Vardhanthi', 'ఎస్.వి. రంగారావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 7, 18],
  ['gummadi_venkateswara_rao_jayanthi', 'Gummadi Venkateswara Rao Jayanthi', 'గుమ్మడి వెంకటేశ్వరరావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 7, 9],
  ['gummadi_venkateswara_rao_vardhanthi', 'Gummadi Venkateswara Rao Vardhanthi', 'గుమ్మడి వెంకటేశ్వరరావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 1, 26],
  ['krishnam_raju_jayanthi', 'Krishnam Raju Jayanthi', 'కృష్ణంరాజు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 1, 20],
  ['krishnam_raju_vardhanthi', 'Krishnam Raju Vardhanthi', 'కృష్ణంరాజు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 9, 11],
  ['sobhan_babu_jayanthi', 'Sobhan Babu Jayanthi', 'శోభన్ బాబు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 1, 14],
  ['sobhan_babu_vardhanthi', 'Sobhan Babu Vardhanthi', 'శోభన్ బాబు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 3, 20],
  ['bhanumathi_ramakrishna_jayanthi', 'Bhanumathi Ramakrishna Jayanthi', 'భానుమతి రామకృష్ణ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 9, 7],
  ['bhanumathi_ramakrishna_vardhanthi', 'Bhanumathi Ramakrishna Vardhanthi', 'భానుమతి రామకృష్ణ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 12, 24],
  ['kasinadhuni_nageswara_rao_pantulu_jayanthi', 'Kasinadhuni Nageswara Rao Pantulu Jayanthi', 'కాసినాధుని నాగేశ్వరరావు పంతులు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 5, 1],
  ['kasinadhuni_nageswara_rao_pantulu_vardhanthi', 'Kasinadhuni Nageswara Rao Pantulu Vardhanthi', 'కాసినాధుని నాగేశ్వరరావు పంతులు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 4, 11],
  ['tenneti_viswanadham_jayanthi', 'Tenneti Viswanadham Jayanthi', 'తెన్నేటి విశ్వనాథం జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 7, 9],
  ['tenneti_viswanadham_vardhanthi', 'Tenneti Viswanadham Vardhanthi', 'తెన్నేటి విశ్వనాథం వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 11, 10],
  ['gouthu_latchanna_jayanthi', 'Gouthu Latchanna Jayanthi', 'గౌతు లచ్చన్న జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 70, 8, 16],
  ['gouthu_latchanna_vardhanthi', 'Gouthu Latchanna Vardhanthi', 'గౌతు లచ్చన్న వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 4, 19],
  ['pingali_venkayya_jayanthi', 'Pingali Venkayya Jayanthi', 'పింగళి వెంకయ్య జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 8, 2],
  ['pingali_venkayya_vardhanthi', 'Pingali Venkayya Vardhanthi', 'పింగళి వెంకయ్య వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 90, 7, 4],
  ['sri_potti_sriramulu_andhra_state_day_memory_usage', 'Sri Potti Sriramulu Andhra State Day memory usage', 'పొట్టి శ్రీరాములు ఆంధ్ర రాష్ట్ర దిన స్మరణ', DynamicCategoryType.importantDay, DynamicEventScope.andhraPradesh, 70, 10, 1],
  ['sri_annamayya_jayanthi', 'Sri Annamayya Jayanthi', 'శ్రీ అన్నమయ్య జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.andhraPradesh, 90, 5, 9],
  ['sri_annamayya_vardhanthi', 'Sri Annamayya Vardhanthi', 'శ్రీ అన్నమయ్య వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.andhraPradesh, 70, 2, 23],
  ['kaloji_narayana_rao_telangana_language_day_usage', 'Kaloji Narayana Rao Telangana Language Day usage', 'కాళోజి నారాయణరావు తెలంగాణ భాషా దినోత్సవ వినియోగం', DynamicCategoryType.importantDay, DynamicEventScope.telangana, 70, 9, 9],
  ['dasarathi_rangacharya_jayanthi', 'Dasarathi Rangacharya Jayanthi', 'దాశరథి రంగాచార్య జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 8, 24],
  ['dasarathi_rangacharya_vardhanthi', 'Dasarathi Rangacharya Vardhanthi', 'దాశరథి రంగాచార్య వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 6, 8],
  ['c_narayana_reddy_jayanthi', 'C. Narayana Reddy Jayanthi', 'సి. నారాయణరెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 7, 29],
  ['c_narayana_reddy_vardhanthi', 'C. Narayana Reddy Vardhanthi', 'సి. నారాయణరెడ్డి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 90, 6, 12],
  ['chakali_ailamma_jayanthi', 'Chakali Ailamma Jayanthi', 'చాకలి ఐలమ్మ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 90, 9, 26],
  ['chakali_ailamma_vardhanthi', 'Chakali Ailamma Vardhanthi', 'చాకలి ఐలమ్మ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 9, 10],
  ['baddam_yella_reddy_jayanthi', 'Baddam Yella Reddy Jayanthi', 'బడ్డం యెల్లారెడ్డి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 10, 9],
  ['baddam_yella_reddy_vardhanthi', 'Baddam Yella Reddy Vardhanthi', 'బడ్డం యెల్లారెడ్డి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 2, 9],
  ['ramji_gond_jayanthi', 'Ramji Gond Jayanthi', 'రాం జీ గోండ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 4, 1],
  ['ramji_gond_vardhanthi', 'Ramji Gond Vardhanthi', 'రాం జీ గోండ్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 4, 9],
  ['shoebullah_khan_jayanthi', 'Shoebullah Khan Jayanthi', 'షోయబుల్లా ఖాన్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.telangana, 70, 10, 16],
  ['shoebullah_khan_vardhanthi', 'Shoebullah Khan Vardhanthi', 'షోయబుల్లా ఖాన్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.telangana, 70, 8, 22],
  ['savarkar_vardhanthi', 'Savarkar Vardhanthi', 'సావర్కర్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 2, 26],
  ['dr_rajendra_prasad_jayanthi', 'Dr. Rajendra Prasad Jayanthi', 'డా. రాజేంద్ర ప్రసాద్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 12, 3],
  ['dr_rajendra_prasad_vardhanthi', 'Dr. Rajendra Prasad Vardhanthi', 'డా. రాజేంద్ర ప్రసాద్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 2, 28],
  ['sardar_bhagat_singh_martyrdom_remembrance_usage', 'Sardar Bhagat Singh Martyrdom remembrance usage', 'సర్దార్ భగత్‌సింగ్ అమరవీరుల స్మరణ', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 3, 23],
  ['lalaji_vardhanthi', 'Lalaji Vardhanthi', 'లాలా లజపత్ రాయ్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 11, 17],
  ['madan_lal_dhingra_jayanthi', 'Madan Lal Dhingra Jayanthi', 'మదన్ లాల్ ఢీంగ్రా జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 50, 2, 18],
  ['madan_lal_dhingra_vardhanthi', 'Madan Lal Dhingra Vardhanthi', 'మదన్ లాల్ ఢీంగ్రా వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 50, 8, 17],
  ['sukhdev_thapar_jayanthi', 'Sukhdev Thapar Jayanthi', 'సుఖ్‌దేవ్ థాపర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 50, 5, 15],
  ['rajguru_jayanthi', 'Rajguru Jayanthi', 'రాజ్‌గురు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 50, 8, 24],
  ['rash_behari_bose_jayanthi', 'Rash Behari Bose Jayanthi', 'రాస్ బిహారి బోస్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 50, 5, 25],
  ['rash_behari_bose_vardhanthi', 'Rash Behari Bose Vardhanthi', 'రాస్ బిహారి బోస్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 50, 1, 21],
  ['mangal_pandey_vardhanthi', 'Mangal Pandey Vardhanthi', 'మంగళ్ పాండే వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 4, 8],
  ['chandrashekhar_azad_vardhanthi', 'Chandrashekhar Azad Vardhanthi', 'చంద్రశేఖర్ ఆజాద్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 90, 2, 27],
  ['bal_gangadhar_tilak_vardhanthi', 'Bal Gangadhar Tilak Vardhanthi', 'బాల గంగాధర్ తిలక్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 8, 1],
  ['sardar_udham_singh_martyrdom_remembrance_usage', 'Sardar Udham Singh Martyrdom remembrance usage', 'ఉధమ్ సింగ్ అమరస్మరణ వినియోగం', DynamicCategoryType.importantDay, DynamicEventScope.india, 50, 7, 31],
  ['dr_zakir_husain_jayanthi', 'Dr. Zakir Husain Jayanthi', 'డా. జాకిర్ హుస్సేన్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 2, 8],
  ['dr_zakir_husain_vardhanthi', 'Dr. Zakir Husain Vardhanthi', 'డా. జాకిర్ హుస్సేన్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 5, 3],
  ['a_p_j_abdul_kalam_world_students_day_linkage', 'A.P.J. Abdul Kalam World Students Day linkage', 'ఏ.పి.జె. అబ్దుల్ కలాం వరల్డ్ స్టూడెంట్స్ డే లింక్', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 10, 15],
  ['national_space_day', 'National Space Day', 'జాతీయ అంతరిక్ష దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 90, 8, 23],
  ['national_startup_day', 'National Startup Day', 'జాతీయ స్టార్టప్ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 1, 16],
  ['national_press_day', 'National Press Day', 'జాతీయ పత్రికా దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 11, 16],
  ['national_energy_conservation_day', 'National Energy Conservation Day', 'జాతీయ ఇంధన సంరక్షణ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 12, 14],
  ['national_consumer_rights_day', 'National Consumer Rights Day', 'జాతీయ వినియోగదారుల హక్కుల దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 12, 24],
  ['national_pollution_control_day', 'National Pollution Control Day', 'జాతీయ కాలుష్య నియంత్రణ దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 12, 2],
  ['world_literacy_day', 'World Literacy Day', 'ప్రపంచ సాక్షరత దినోత్సవం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 9, 8],
  ['national_nutrition_week_start_usage', 'National Nutrition Week start usage', 'జాతీయ పోషణ వారోత్సవ వినియోగం', DynamicCategoryType.importantDay, DynamicEventScope.india, 50, 9, 1],
  ['national_unity_week_start_usage', 'National Unity Week start usage', 'జాతీయ ఐక్యత వారోత్సవ వినియోగం', DynamicCategoryType.importantDay, DynamicEventScope.india, 50, 10, 31],
  ['sardar_patel_national_unity_day_campaign_use', 'Sardar Patel National Unity Day campaign use', 'సర్దార్ పటేల్ జాతీయ ఐక్యతా దినం క్యాంపైన్ వినియోగం', DynamicCategoryType.importantDay, DynamicEventScope.india, 70, 10, 31],
  ['satyajit_ray_jayanthi', 'Satyajit Ray Jayanthi', 'సత్యజిత్ రే జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 5, 2],
  ['satyajit_ray_vardhanthi', 'Satyajit Ray Vardhanthi', 'సత్యజిత్ రే వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 4, 23],
  ['dadasaheb_phalke_jayanthi', 'Dadasaheb Phalke Jayanthi', 'దాదాసాహెబ్ ఫాల్కే జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 4, 30],
  ['dadasaheb_phalke_vardhanthi', 'Dadasaheb Phalke Vardhanthi', 'దాదాసాహెబ్ ఫాల్కే వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 2, 16],
  ['lata_mangeshkar_jayanthi', 'Lata Mangeshkar Jayanthi', 'లతా మంగేష్కర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70, 9, 28],
  ['lata_mangeshkar_vardhanthi', 'Lata Mangeshkar Vardhanthi', 'లతా మంగేష్కర్ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 70, 2, 6],
  ['bhimsen_joshi_jayanthi', 'Bhimsen Joshi Jayanthi', 'భీంసేన్ జోషి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 50, 2, 4],
  ['bhimsen_joshi_vardhanthi', 'Bhimsen Joshi Vardhanthi', 'భీంసేన్ జోషి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.india, 50, 1, 24],
  ['sri_sri_jayanthi', 'Sri Sri Jayanthi', 'శ్రీశ్రీ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.bothTeluguStates, 90, 4, 30],
  ['sri_sri_vardhanthi', 'Sri Sri Vardhanthi', 'శ్రీశ్రీ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.bothTeluguStates, 90, 6, 15],
  ['gurram_jashuva_jayanthi', 'Gurram Jashuva Jayanthi', 'గుర్రం జాషువా జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.bothTeluguStates, 90, 9, 28],
  ['gurram_jashuva_vardhanthi', 'Gurram Jashuva Vardhanthi', 'గుర్రం జాషువా వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.bothTeluguStates, 90, 7, 24],
  ['viswanatha_satyanarayana_jayanthi', 'Viswanatha Satyanarayana Jayanthi', 'విశ్వనాథ సత్యనారాయణ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.bothTeluguStates, 70, 9, 10],
  ['viswanatha_satyanarayana_vardhanthi', 'Viswanatha Satyanarayana Vardhanthi', 'విశ్వనాథ సత్యనారాయణ వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.bothTeluguStates, 70, 10, 18],
  ['tripuraneni_ramaswamy_jayanthi', 'Tripuraneni Ramaswamy Jayanthi', 'త్రిపురనేని రామస్వామి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.bothTeluguStates, 70, 1, 15],
  ['tripuraneni_ramaswamy_vardhanthi', 'Tripuraneni Ramaswamy Vardhanthi', 'త్రిపురనేని రామస్వామి వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.bothTeluguStates, 70, 1, 16],
  ['rayaprolu_subba_rao_jayanthi', 'Rayaprolu Subba Rao Jayanthi', 'రాయప్రోలు సుబ్బారావు జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.bothTeluguStates, 50, 3, 8],
  ['rayaprolu_subba_rao_vardhanthi', 'Rayaprolu Subba Rao Vardhanthi', 'రాయప్రోలు సుబ్బారావు వర్ధంతి', DynamicCategoryType.vardhanthi, DynamicEventScope.bothTeluguStates, 50, 6, 30],
];

const List<List<Object>> _lunarPlaceholderSeedRows = <List<Object>>[
  ['makara_sankranti', 'Makara Sankranti', 'మకర సంక్రాంతి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90],
  ['ratha_saptami', 'Ratha Saptami', 'రథసప్తమి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 50],
  ['maha_shivaratri', 'Maha Shivaratri', 'మహాశివరాత్రి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90],
  ['holi', 'Holi', 'హోళీ', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['ugadi', 'Ugadi', 'ఉగాది', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90],
  ['sri_rama_navami', 'Sri Rama Navami', 'శ్రీరామ నవమి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90],
  ['hanuman_jayanthi', 'Hanuman Jayanthi', 'హనుమాన్ జయంతి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['narasimha_jayanthi', 'Narasimha Jayanthi', 'నరసింహ జయంతి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 50],
  ['bonalu', 'Bonalu', 'బోనాలు', DynamicCategoryType.festival, DynamicEventScope.telangana, 90],
  ['varalakshmi_vratham', 'Varalakshmi Vratham', 'వరలక్ష్మీ వ్రతం', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['krishna_janmashtami', 'Krishna Janmashtami', 'శ్రీకృష్ణ జన్మాష్టమి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['vinayaka_chavithi', 'Vinayaka Chavithi', 'వినాయక చవితి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90],
  ['bathukamma', 'Bathukamma', 'బతుకమ్మ', DynamicCategoryType.festival, DynamicEventScope.telangana, 90],
  ['dasara_vijayadashami', 'Dasara / Vijayadashami', 'దసరా / విజయదశమి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90],
  ['deepavali', 'Deepavali', 'దీపావళి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 90],
  ['karthika_pournami_karthika_deepam', 'Karthika Pournami / Karthika Deepam', 'కార్తీక పౌర్ణమి / కార్తీక దీపం', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['vaikuntha_ekadashi', 'Vaikuntha Ekadashi', 'వైకుంఠ ఏకాదశి', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['sammakka_saralamma_jatara_medaram_jatara', 'Sammakka Saralamma Jatara / Medaram Jatara', 'సమ్మక్క సారలమ్మ జాతర / మేడారం జాతర', DynamicCategoryType.festival, DynamicEventScope.telangana, 90],
  ['nagoba_jatara', 'Nagoba Jatara', 'నాగోబా జాతర', DynamicCategoryType.festival, DynamicEventScope.telangana, 70],
  ['guru_nanak_jayanti', 'Guru Nanak Jayanti', 'గురు నానక్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70],
  ['tyagaraja_aradhana', 'Tyagaraja Aradhana', 'త్యాగరాజ ఆరాధన', DynamicCategoryType.festival, DynamicEventScope.andhraPradesh, 90],
  ['guru_gobind_singh_jayanti', 'Guru Gobind Singh Jayanti', 'గురు గోబింద్ సింగ్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70],
  ['basava_jayanti', 'Basava Jayanti', 'బసవ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70],
  ['valmiki_jayanti', 'Valmiki Jayanti', 'వాల్మీకి జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70],
  ['mahavir_jayanti', 'Mahavir Jayanti', 'మహావీర్ జయంతి', DynamicCategoryType.jayanthi, DynamicEventScope.india, 70],
  ['kanaka_durga_temple_dasara', 'Kanaka Durga Temple Dasara', 'కనకదుర్గమ్మ దసరా ఉత్సవాలు', DynamicCategoryType.festival, DynamicEventScope.andhraPradesh, 90],
  ['tirumala_brahmotsavam', 'Tirumala Brahmotsavam', 'తిరుమల బ్రహ్మోత్సవాలు', DynamicCategoryType.festival, DynamicEventScope.andhraPradesh, 90],
  ['simhachalam_chandanotsavam', 'Simhachalam Chandanotsavam', 'సింహాచలం చందనోత్సవం', DynamicCategoryType.festival, DynamicEventScope.andhraPradesh, 70],
  ['srisailam_maha_shivaratri_brahmotsavam', 'Srisailam Maha Shivaratri Brahmotsavam', 'శ్రీశైలం మహాశివరాత్రి బ్రహ్మోత్సవాలు', DynamicCategoryType.festival, DynamicEventScope.andhraPradesh, 70],
  ['yadadri_brahmotsavam', 'Yadadri Brahmotsavam', 'యాదాద్రి బ్రహ్మోత్సవాలు', DynamicCategoryType.festival, DynamicEventScope.telangana, 70],
  ['bhadrachalam_sri_rama_kalyanam', 'Bhadrachalam Sri Rama Kalyanam', 'భద్రాచలం శ్రీరామ కల్యాణం', DynamicCategoryType.festival, DynamicEventScope.telangana, 90],
  ['peerla_panduga_usage', 'Peerla Panduga usage', 'పీర్‌ల పండుగ వినియోగం', DynamicCategoryType.festival, DynamicEventScope.telangana, 50],
  ['sri_ramanavami_sita_rama_kalyanam_usage', 'Sri Ramanavami Sita Rama Kalyanam usage', 'శ్రీరామనవమి సీతారామ కళ్యాణ వినియోగం', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['anjaneya_swamy_jayanti_usage', 'Anjaneya Swamy Jayanti usage', 'ఆంజనేయ స్వామి జయంతి వినియోగం', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
  ['sri_narasimha_jayanti_usage', 'Sri Narasimha Jayanti usage', 'శ్రీ నరసింహ జయంతి వినియోగం', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 50],
  ['devotional_karthika_masam_start_usage', 'Devotional Karthika Masam start usage', 'దేవోషనల్ కార్తీక మాస ప్రారంభ వినియోగం', DynamicCategoryType.festival, DynamicEventScope.bothTeluguStates, 70],
];

List<DynamicCalendarEvent> buildCsvBackedDynamicEvents() {
  final output = <DynamicCalendarEvent>[];

  for (var index = 0; index < _fixedGregorianSeedRows.length; index++) {
    output.add(_fixedRowToEvent(_fixedGregorianSeedRows[index], index));
  }

  for (var index = 0; index < _lunarPlaceholderSeedRows.length; index++) {
    output.add(_lunarRowToEvent(_lunarPlaceholderSeedRows[index], index));
  }

  return output;
}

DynamicCalendarEvent _fixedRowToEvent(List<Object> row, int index) {
  return DynamicCalendarEvent(
    id: row[0] as String,
    slug: row[0] as String,
    type: row[3] as DynamicCategoryType,
    scope: row[4] as DynamicEventScope,
    priority: row[5] as int,
    sortOrder: 1000 + index,
    startMonth: row[6] as int,
    startDay: row[7] as int,
    title: DynamicLocalizedTitle(
      telugu: row[2] as String,
      english: row[1] as String,
      hindi: row[1] as String,
    ),
    tags: <String>[
      'csv_import',
      (row[3] as DynamicCategoryType).name,
      (row[4] as DynamicEventScope).name,
      row[0] as String,
    ],
  );
}

DynamicCalendarEvent _lunarRowToEvent(List<Object> row, int index) {
  return DynamicCalendarEvent(
    id: row[0] as String,
    slug: row[0] as String,
    type: row[3] as DynamicCategoryType,
    scope: row[4] as DynamicEventScope,
    priority: row[5] as int,
    sortOrder: 5000 + index,
    enabled: false,
    calendarType: DynamicCalendarType.lunarPlaceholder,
    title: DynamicLocalizedTitle(
      telugu: row[2] as String,
      english: row[1] as String,
      hindi: row[1] as String,
    ),
    tags: <String>[
      'csv_import',
      'lunar_placeholder',
      (row[3] as DynamicCategoryType).name,
      (row[4] as DynamicEventScope).name,
      row[0] as String,
    ],
  );
}
