import 'package:mana_poster/features/prehome/models/dynamic_category.dart';

const List<List<Object>> _regionalFixedEventRows = <List<Object>>[
  [
    'arunachal_pradesh',
    'arunachal_pradesh_statehood_day',
    'Arunachal Pradesh Statehood Day',
    'అరుణాచల్ ప్రదేశ్ రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    2,
    20,
    90,
  ],
  [
    'arunachal_pradesh',
    'nyokum',
    'Nyokum',
    'న్యోకుమ్',
    DynamicCategoryType.festival,
    2,
    26,
    70,
  ],
  [
    'arunachal_pradesh',
    'solung',
    'Solung Festival',
    'సోలుంగ్ పండుగ',
    DynamicCategoryType.festival,
    9,
    1,
    70,
  ],
  [
    'arunachal_pradesh',
    'losar_arunachal',
    'Losar',
    'లోసార్',
    DynamicCategoryType.festival,
    2,
    10,
    70,
  ],
  [
    'assam',
    'assam_day_asom_divas',
    'Assam Day / Asom Divas',
    'అస్సాం దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    12,
    2,
    90,
  ],
  [
    'assam',
    'rongali_bihu',
    'Rongali Bihu',
    'రొంగాలి బిహు',
    DynamicCategoryType.festival,
    4,
    14,
    90,
  ],
  [
    'assam',
    'bhogali_bihu',
    'Bhogali Bihu',
    'భోగాలి బిహు',
    DynamicCategoryType.festival,
    1,
    15,
    80,
  ],
  [
    'assam',
    'kati_bihu',
    'Kati Bihu',
    'కాటి బిహు',
    DynamicCategoryType.festival,
    10,
    18,
    70,
  ],
  [
    'assam',
    'lachit_divas',
    'Lachit Divas',
    'లాచిత్ దివస్',
    DynamicCategoryType.regionalSpecial,
    11,
    24,
    80,
  ],
  [
    'bihar',
    'bihar_diwas',
    'Bihar Diwas',
    'బీహార్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    3,
    22,
    90,
  ],
  [
    'bihar',
    'chhath_puja_bihar',
    'Chhath Puja',
    'ఛఠ్ పూజ',
    DynamicCategoryType.festival,
    11,
    7,
    90,
  ],
  [
    'bihar',
    'sonepur_mela',
    'Sonepur Mela',
    'సోనేపూర్ మేళా',
    DynamicCategoryType.festival,
    11,
    15,
    70,
  ],
  [
    'chhattisgarh',
    'chhattisgarh_rajyotsava',
    'Chhattisgarh Rajyotsava',
    'ఛత్తీస్‌గఢ్ రాజ్యోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    90,
  ],
  [
    'chhattisgarh',
    'hareli',
    'Hareli',
    'హరేలీ',
    DynamicCategoryType.festival,
    7,
    17,
    70,
  ],
  [
    'chhattisgarh',
    'pola_chhattisgarh',
    'Pola',
    'పోలా',
    DynamicCategoryType.festival,
    9,
    2,
    70,
  ],
  [
    'chhattisgarh',
    'teeja_chhattisgarh',
    'Teeja',
    'తీజా',
    DynamicCategoryType.festival,
    9,
    6,
    70,
  ],
  [
    'goa',
    'goa_statehood_day',
    'Goa Statehood Day',
    'గోవా రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    5,
    30,
    90,
  ],
  [
    'goa',
    'goa_liberation_day',
    'Goa Liberation Day',
    'గోవా విమోచన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    12,
    19,
    90,
  ],
  [
    'goa',
    'sao_joao',
    'Sao Joao',
    'సావో జోవో',
    DynamicCategoryType.festival,
    6,
    24,
    70,
  ],
  [
    'goa',
    'shigmo',
    'Shigmo',
    'శిగ్మో',
    DynamicCategoryType.festival,
    3,
    15,
    70,
  ],
  [
    'gujarat',
    'gujarat_day',
    'Gujarat Day',
    'గుజరాత్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    5,
    1,
    90,
  ],
  [
    'gujarat',
    'uttarayan_gujarat',
    'Uttarayan',
    'ఉత్తరాయణ్',
    DynamicCategoryType.festival,
    1,
    14,
    90,
  ],
  [
    'gujarat',
    'navratri_garba',
    'Navratri Garba',
    'నవరాత్రి గర్బా',
    DynamicCategoryType.festival,
    10,
    3,
    80,
  ],
  [
    'gujarat',
    'rann_utsav',
    'Rann Utsav',
    'రణ్ ఉత్సవ్',
    DynamicCategoryType.festival,
    11,
    1,
    60,
  ],
  [
    'haryana',
    'haryana_day',
    'Haryana Day',
    'హర్యానా దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    90,
  ],
  [
    'haryana',
    'surajkund_mela',
    'Surajkund Mela',
    'సురజ్‌కుండ్ మేళా',
    DynamicCategoryType.festival,
    2,
    1,
    70,
  ],
  [
    'haryana',
    'gita_jayanti_haryana',
    'Gita Jayanti',
    'గీతా జయంతి',
    DynamicCategoryType.festival,
    12,
    11,
    70,
  ],
  [
    'himachal_pradesh',
    'himachal_pradesh_statehood_day',
    'Himachal Pradesh Statehood Day',
    'హిమాచల్ ప్రదేశ్ రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    1,
    25,
    90,
  ],
  [
    'himachal_pradesh',
    'himachal_day',
    'Himachal Day',
    'హిమాచల్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    4,
    15,
    90,
  ],
  [
    'himachal_pradesh',
    'minjar_mela',
    'Minjar Mela',
    'మింజర్ మేళా',
    DynamicCategoryType.festival,
    7,
    28,
    70,
  ],
  [
    'himachal_pradesh',
    'kullu_dussehra',
    'Kullu Dussehra',
    'కులు దసరా',
    DynamicCategoryType.festival,
    10,
    12,
    80,
  ],
  [
    'jharkhand',
    'jharkhand_foundation_day',
    'Jharkhand Foundation Day',
    'జార్ఖండ్ స్థాపన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    15,
    90,
  ],
  [
    'jharkhand',
    'sarhul',
    'Sarhul',
    'సర్హుల్',
    DynamicCategoryType.festival,
    4,
    11,
    70,
  ],
  [
    'jharkhand',
    'karma_jharkhand',
    'Karma Festival',
    'కర్మ పండుగ',
    DynamicCategoryType.festival,
    9,
    14,
    70,
  ],
  [
    'jharkhand',
    'sohrai',
    'Sohrai',
    'సోహ్రాయ్',
    DynamicCategoryType.festival,
    11,
    1,
    70,
  ],
  [
    'karnataka',
    'karnataka_rajyotsava',
    'Karnataka Rajyotsava',
    'కర్ణాటక రాజ్యోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    90,
  ],
  [
    'karnataka',
    'basava_jayanti_karnataka',
    'Basava Jayanti',
    'బసవ జయంతి',
    DynamicCategoryType.jayanthi,
    5,
    10,
    80,
  ],
  [
    'karnataka',
    'kanakadasa_jayanthi',
    'Kanakadasa Jayanthi',
    'కనకదాస జయంతి',
    DynamicCategoryType.jayanthi,
    11,
    18,
    70,
  ],
  [
    'karnataka',
    'mysuru_dasara',
    'Mysuru Dasara',
    'మైసూరు దసరా',
    DynamicCategoryType.festival,
    10,
    12,
    90,
  ],
  [
    'kerala',
    'kerala_piravi',
    'Kerala Piravi',
    'కేరళ పిరవి',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    90,
  ],
  ['kerala', 'vishu', 'Vishu', 'విషు', DynamicCategoryType.festival, 4, 14, 90],
  [
    'kerala',
    'thrissur_pooram',
    'Thrissur Pooram',
    'త్రిస్సూర్ పూరం',
    DynamicCategoryType.festival,
    5,
    7,
    80,
  ],
  [
    'kerala',
    'attukal_pongala',
    'Attukal Pongala',
    'అట్టుకల్ పొంగళ',
    DynamicCategoryType.festival,
    3,
    13,
    70,
  ],
  [
    'madhya_pradesh',
    'madhya_pradesh_foundation_day',
    'Madhya Pradesh Foundation Day',
    'మధ్యప్రదేశ్ స్థాపన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    90,
  ],
  [
    'madhya_pradesh',
    'khajuraho_dance_festival',
    'Khajuraho Dance Festival',
    'ఖజురాహో నృత్యోత్సవం',
    DynamicCategoryType.festival,
    2,
    20,
    70,
  ],
  [
    'madhya_pradesh',
    'tansen_samaroh',
    'Tansen Samaroh',
    'తాన్సెన్ సమారోహ్',
    DynamicCategoryType.festival,
    12,
    15,
    70,
  ],
  [
    'maharashtra',
    'maharashtra_day',
    'Maharashtra Day',
    'మహారాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    5,
    1,
    90,
  ],
  [
    'maharashtra',
    'shivaji_jayanti_maharashtra',
    'Chhatrapati Shivaji Maharaj Jayanti',
    'ఛత్రపతి శివాజీ మహారాజ్ జయంతి',
    DynamicCategoryType.jayanthi,
    2,
    19,
    90,
  ],
  [
    'maharashtra',
    'gudi_padwa',
    'Gudi Padwa',
    'గుడి పడ్వా',
    DynamicCategoryType.festival,
    3,
    30,
    80,
  ],
  [
    'maharashtra',
    'ganesh_chaturthi_maharashtra',
    'Ganesh Chaturthi',
    'గణేష్ చతుర్థి',
    DynamicCategoryType.festival,
    8,
    27,
    90,
  ],
  [
    'manipur',
    'manipur_statehood_day',
    'Manipur Statehood Day',
    'మణిపూర్ రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    1,
    21,
    90,
  ],
  [
    'manipur',
    'yaoshang',
    'Yaoshang',
    'యావోషాంగ్',
    DynamicCategoryType.festival,
    3,
    14,
    80,
  ],
  [
    'manipur',
    'ningol_chakouba',
    'Ningol Chakouba',
    'నింగోల్ చాకౌబా',
    DynamicCategoryType.festival,
    11,
    3,
    70,
  ],
  [
    'manipur',
    'sangai_festival',
    'Sangai Festival',
    'సంగై పండుగ',
    DynamicCategoryType.festival,
    11,
    21,
    70,
  ],
  [
    'meghalaya',
    'meghalaya_statehood_day',
    'Meghalaya Statehood Day',
    'మేఘాలయ రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    1,
    21,
    90,
  ],
  [
    'meghalaya',
    'shad_suk_mynsiem',
    'Shad Suk Mynsiem',
    'షాడ్ సుక్ మిన్సీమ్',
    DynamicCategoryType.festival,
    4,
    14,
    70,
  ],
  [
    'meghalaya',
    'wangala',
    'Wangala Festival',
    'వాంగాలా పండుగ',
    DynamicCategoryType.festival,
    11,
    14,
    80,
  ],
  [
    'meghalaya',
    'nongkrem_dance_festival',
    'Nongkrem Dance Festival',
    'నాంగ్క్రెమ్ నృత్యోత్సవం',
    DynamicCategoryType.festival,
    11,
    5,
    70,
  ],
  [
    'mizoram',
    'mizoram_statehood_day',
    'Mizoram Statehood Day',
    'మిజోరం రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    2,
    20,
    90,
  ],
  [
    'mizoram',
    'chapchar_kut',
    'Chapchar Kut',
    'చప్చార్ కూట్',
    DynamicCategoryType.festival,
    3,
    7,
    80,
  ],
  [
    'mizoram',
    'mim_kut',
    'Mim Kut',
    'మిమ్ కూట్',
    DynamicCategoryType.festival,
    9,
    1,
    70,
  ],
  [
    'mizoram',
    'pawl_kut',
    'Pawl Kut',
    'పాల్ కూట్',
    DynamicCategoryType.festival,
    12,
    11,
    70,
  ],
  [
    'nagaland',
    'nagaland_statehood_day',
    'Nagaland Statehood Day',
    'నాగాలాండ్ రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    12,
    1,
    90,
  ],
  [
    'nagaland',
    'hornbill_festival',
    'Hornbill Festival',
    'హార్న్‌బిల్ పండుగ',
    DynamicCategoryType.festival,
    12,
    1,
    90,
  ],
  [
    'nagaland',
    'moatsu',
    'Moatsu',
    'మోయాట్సు',
    DynamicCategoryType.festival,
    5,
    1,
    70,
  ],
  [
    'nagaland',
    'sekrenyi',
    'Sekrenyi',
    'సెక్రెన్యి',
    DynamicCategoryType.festival,
    2,
    25,
    70,
  ],
  [
    'odisha',
    'odisha_day_utkala_dibasa',
    'Odisha Day / Utkala Dibasa',
    'ఒడిశా దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    4,
    1,
    90,
  ],
  [
    'odisha',
    'raja_parba',
    'Raja Parba',
    'రజ పర్బ',
    DynamicCategoryType.festival,
    6,
    14,
    80,
  ],
  [
    'odisha',
    'nuakhai_odisha',
    'Nuakhai',
    'నువాఖాయ్',
    DynamicCategoryType.festival,
    9,
    1,
    80,
  ],
  [
    'odisha',
    'rath_yatra_puri',
    'Puri Rath Yatra',
    'పూరి రథయాత్ర',
    DynamicCategoryType.festival,
    6,
    27,
    90,
  ],
  [
    'punjab',
    'punjab_day',
    'Punjab Day',
    'పంజాబ్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    90,
  ],
  [
    'punjab',
    'lohri',
    'Lohri',
    'లోహ్రీ',
    DynamicCategoryType.festival,
    1,
    13,
    90,
  ],
  [
    'punjab',
    'baisakhi_punjab',
    'Baisakhi',
    'బైసాఖి',
    DynamicCategoryType.festival,
    4,
    13,
    90,
  ],
  [
    'punjab',
    'hola_mohalla',
    'Hola Mohalla',
    'హోలా మొహల్లా',
    DynamicCategoryType.festival,
    3,
    15,
    70,
  ],
  [
    'rajasthan',
    'rajasthan_day',
    'Rajasthan Day',
    'రాజస్థాన్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    3,
    30,
    90,
  ],
  [
    'rajasthan',
    'gangaur',
    'Gangaur',
    'గంగౌర్',
    DynamicCategoryType.festival,
    4,
    2,
    80,
  ],
  [
    'rajasthan',
    'teej_rajasthan',
    'Teej',
    'తీజ్',
    DynamicCategoryType.festival,
    8,
    7,
    80,
  ],
  [
    'rajasthan',
    'pushkar_fair',
    'Pushkar Fair',
    'పుష్కర్ మేళా',
    DynamicCategoryType.festival,
    11,
    9,
    70,
  ],
  [
    'sikkim',
    'sikkim_state_day',
    'Sikkim State Day',
    'సిక్కిం రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    5,
    16,
    90,
  ],
  [
    'sikkim',
    'saga_dawa',
    'Saga Dawa',
    'సాగా దావా',
    DynamicCategoryType.festival,
    6,
    11,
    70,
  ],
  [
    'sikkim',
    'pang_lhabsol',
    'Pang Lhabsol',
    'పాంగ్ ల్హాబ్సోల్',
    DynamicCategoryType.festival,
    9,
    8,
    70,
  ],
  [
    'sikkim',
    'losoong',
    'Losoong',
    'లోసూంగ్',
    DynamicCategoryType.festival,
    12,
    19,
    70,
  ],
  [
    'tamil_nadu',
    'tamil_new_year',
    'Tamil New Year / Puthandu',
    'తమిళ నూతన సంవత్సరం',
    DynamicCategoryType.festival,
    4,
    14,
    90,
  ],
  [
    'tamil_nadu',
    'pongal',
    'Pongal',
    'పొంగళ్',
    DynamicCategoryType.festival,
    1,
    15,
    90,
  ],
  [
    'tamil_nadu',
    'thaipusam',
    'Thaipusam',
    'థైపూసం',
    DynamicCategoryType.festival,
    2,
    11,
    80,
  ],
  [
    'tamil_nadu',
    'tamil_nadu_day',
    'Tamil Nadu Day',
    'తమిళనాడు దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    7,
    18,
    90,
  ],
  [
    'tripura',
    'tripura_statehood_day',
    'Tripura Statehood Day',
    'త్రిపుర రాష్ట్ర దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    1,
    21,
    90,
  ],
  [
    'tripura',
    'garia_puja',
    'Garia Puja',
    'గరియా పూజ',
    DynamicCategoryType.festival,
    4,
    21,
    80,
  ],
  [
    'tripura',
    'kharchi_puja',
    'Kharchi Puja',
    'ఖార్చి పూజ',
    DynamicCategoryType.festival,
    7,
    3,
    80,
  ],
  [
    'tripura',
    'ker_puja',
    'Ker Puja',
    'కేర్ పూజ',
    DynamicCategoryType.festival,
    7,
    17,
    70,
  ],
  [
    'uttar_pradesh',
    'uttar_pradesh_day',
    'Uttar Pradesh Day',
    'ఉత్తరప్రదేశ్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    1,
    24,
    90,
  ],
  [
    'uttar_pradesh',
    'dev_deepawali_varanasi',
    'Dev Deepawali Varanasi',
    'దేవ దీపావళి వారణాసి',
    DynamicCategoryType.festival,
    11,
    15,
    80,
  ],
  [
    'uttar_pradesh',
    'krishna_janmashtami_mathura',
    'Krishna Janmashtami Mathura',
    'కృష్ణ జన్మాష్టమి మథుర',
    DynamicCategoryType.festival,
    8,
    16,
    80,
  ],
  [
    'uttarakhand',
    'uttarakhand_state_foundation_day',
    'Uttarakhand State Foundation Day',
    'ఉత్తరాఖండ్ స్థాపన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    9,
    90,
  ],
  [
    'uttarakhand',
    'harela',
    'Harela',
    'హరేలా',
    DynamicCategoryType.festival,
    7,
    16,
    80,
  ],
  [
    'uttarakhand',
    'phool_dei',
    'Phool Dei',
    'ఫూల్ దేయి',
    DynamicCategoryType.festival,
    3,
    14,
    70,
  ],
  [
    'west_bengal',
    'poila_boishakh',
    'Poila Boishakh',
    'పొయిలా బోయిశాఖ్',
    DynamicCategoryType.festival,
    4,
    15,
    90,
  ],
  [
    'west_bengal',
    'durga_puja_west_bengal',
    'Durga Puja',
    'దుర్గా పూజ',
    DynamicCategoryType.festival,
    10,
    9,
    90,
  ],
  [
    'west_bengal',
    'kali_puja_west_bengal',
    'Kali Puja',
    'కాళీ పూజ',
    DynamicCategoryType.festival,
    10,
    31,
    80,
  ],
  [
    'west_bengal',
    'west_bengal_day',
    'West Bengal Day',
    'పశ్చిమ బెంగాల్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    4,
    15,
    80,
  ],
  [
    'delhi',
    'delhi_formation_day',
    'Delhi Formation Day',
    'ఢిల్లీ స్థాపన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    2,
    1,
    80,
  ],
  [
    'jammu_kashmir',
    'jammu_kashmir_union_territory_day',
    'Jammu & Kashmir Union Territory Day',
    'జమ్మూ కాశ్మీర్ కేంద్రపాలిత దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    10,
    31,
    90,
  ],
  [
    'jammu_kashmir',
    'tulip_festival_kashmir',
    'Kashmir Tulip Festival',
    'కాశ్మీర్ ట్యూలిప్ పండుగ',
    DynamicCategoryType.festival,
    4,
    1,
    70,
  ],
  [
    'ladakh',
    'ladakh_union_territory_day',
    'Ladakh Union Territory Day',
    'లడాఖ్ కేంద్రపాలిత దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    10,
    31,
    90,
  ],
  [
    'ladakh',
    'hemis_festival',
    'Hemis Festival',
    'హెమిస్ పండుగ',
    DynamicCategoryType.festival,
    6,
    16,
    70,
  ],
  [
    'puducherry',
    'puducherry_liberation_day',
    'Puducherry Liberation Day',
    'పుదుచ్చేరి విమోచన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    90,
  ],
  [
    'puducherry',
    'de_jure_transfer_day',
    'De Jure Transfer Day',
    'డి జ్యూర్ ట్రాన్స్‌ఫర్ దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    8,
    16,
    80,
  ],
  [
    'chandigarh',
    'chandigarh_capital_day',
    'Chandigarh Capital Day',
    'చండీగఢ్ రాజధాని దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    70,
  ],
  [
    'andaman_nicobar',
    'island_tourism_festival',
    'Island Tourism Festival',
    'ఐలాండ్ టూరిజం ఫెస్టివల్',
    DynamicCategoryType.festival,
    1,
    5,
    70,
  ],
  [
    'andaman_nicobar',
    'andaman_nicobar_formation_day',
    'Andaman & Nicobar Formation Day',
    'అండమాన్ నికోబార్ స్థాపన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    70,
  ],
  [
    'lakshadweep',
    'lakshadweep_formation_day',
    'Lakshadweep Formation Day',
    'లక్షద్వీప్ స్థాపన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    11,
    1,
    70,
  ],
  [
    'dadra_nagar_haveli_daman_diu',
    'dadra_nagar_haveli_daman_diu_merger_day',
    'Dadra & Nagar Haveli and Daman & Diu Merger Day',
    'దాద్రా నగర్ హవేలీ దమన్ దీవ్ విలీన దినోత్సవం',
    DynamicCategoryType.regionalSpecial,
    1,
    26,
    80,
  ],
  [
    'arunachal_pradesh',
    'si_donyi',
    'Si-Donyi',
    'సి-దోని',
    DynamicCategoryType.festival,
    1,
    6,
    70,
  ],
  [
    'arunachal_pradesh',
    'dree_festival',
    'Dree Festival',
    'ద్రీ పండుగ',
    DynamicCategoryType.festival,
    7,
    5,
    70,
  ],
  [
    'arunachal_pradesh',
    'torgya_festival',
    'Torgya Festival',
    'టోర్గ్యా పండుగ',
    DynamicCategoryType.festival,
    1,
    28,
    70,
  ],
  [
    'arunachal_pradesh',
    'reh_festival',
    'Reh Festival',
    'రెహ్ పండుగ',
    DynamicCategoryType.festival,
    2,
    1,
    70,
  ],
  [
    'assam',
    'ali_ai_ligang',
    'Ali-Ai-Ligang',
    'అలి-ఐ-లిగాంగ్',
    DynamicCategoryType.festival,
    2,
    15,
    70,
  ],
  [
    'assam',
    'baishagu',
    'Baishagu',
    'బైసాగు',
    DynamicCategoryType.festival,
    4,
    14,
    70,
  ],
  [
    'assam',
    'ambubachi_mela',
    'Ambubachi Mela',
    'అంబుబాచి మేళా',
    DynamicCategoryType.festival,
    6,
    22,
    80,
  ],
  [
    'assam',
    'me_dam_me_phi',
    'Me-Dam-Me-Phi',
    'మే-డామ్-మే-ఫీ',
    DynamicCategoryType.regionalSpecial,
    1,
    31,
    70,
  ],
  [
    'bihar',
    'sama_chakeva',
    'Sama Chakeva',
    'సామా చకేవా',
    DynamicCategoryType.festival,
    11,
    18,
    70,
  ],
  [
    'bihar',
    'pitrapaksha_mela_gaya',
    'Pitrapaksha Mela Gaya',
    'పిత్రపక్ష మేళా గయా',
    DynamicCategoryType.festival,
    9,
    15,
    70,
  ],
  [
    'bihar',
    'rajgir_mahotsav',
    'Rajgir Mahotsav',
    'రాజగిర్ మహోత్సవ్',
    DynamicCategoryType.festival,
    11,
    25,
    70,
  ],
  [
    'chhattisgarh',
    'bastar_dussehra',
    'Bastar Dussehra',
    'బస్తర్ దసరా',
    DynamicCategoryType.festival,
    10,
    1,
    80,
  ],
  [
    'chhattisgarh',
    'madai_festival',
    'Madai Festival',
    'మడై పండుగ',
    DynamicCategoryType.festival,
    12,
    1,
    70,
  ],
  [
    'chhattisgarh',
    'goncha_festival',
    'Goncha Festival',
    'గొంచా పండుగ',
    DynamicCategoryType.festival,
    7,
    1,
    70,
  ],
  [
    'goa',
    'goa_carnival',
    'Goa Carnival',
    'గోవా కార్నివల్',
    DynamicCategoryType.festival,
    2,
    10,
    80,
  ],
  [
    'goa',
    'bonderam_festival',
    'Bonderam Festival',
    'బోండెరాం పండుగ',
    DynamicCategoryType.festival,
    8,
    24,
    70,
  ],
  [
    'goa',
    'three_kings_feast',
    'Three Kings Feast',
    'త్రీ కింగ్స్ ఫీస్ట్',
    DynamicCategoryType.festival,
    1,
    6,
    70,
  ],
  [
    'gujarat',
    'modhera_dance_festival',
    'Modhera Dance Festival',
    'మోధేరా నృత్యోత్సవం',
    DynamicCategoryType.festival,
    1,
    19,
    70,
  ],
  [
    'gujarat',
    'tarnetar_fair',
    'Tarnetar Fair',
    'తర్నేతర్ మేళా',
    DynamicCategoryType.festival,
    9,
    5,
    70,
  ],
  [
    'gujarat',
    'dwarka_janmashtami',
    'Dwarka Janmashtami',
    'ద్వారక జన్మాష్టమి',
    DynamicCategoryType.festival,
    8,
    16,
    80,
  ],
  [
    'haryana',
    'phag_festival',
    'Phag Festival',
    'ఫాగ్ పండుగ',
    DynamicCategoryType.festival,
    3,
    1,
    70,
  ],
  [
    'haryana',
    'gugga_naumi',
    'Gugga Naumi',
    'గుగ్గా నవమి',
    DynamicCategoryType.festival,
    8,
    20,
    70,
  ],
  [
    'haryana',
    'kartik_cultural_festival',
    'Kartik Cultural Festival',
    'కార్తీక్ సాంస్కృతిక ఉత్సవం',
    DynamicCategoryType.festival,
    11,
    15,
    70,
  ],
  [
    'himachal_pradesh',
    'mandi_shivaratri_fair',
    'Mandi Shivaratri Fair',
    'మండీ శివరాత్రి మేళా',
    DynamicCategoryType.festival,
    3,
    8,
    80,
  ],
  [
    'himachal_pradesh',
    'halda_festival',
    'Halda Festival',
    'హల్డా పండుగ',
    DynamicCategoryType.festival,
    1,
    15,
    70,
  ],
  [
    'himachal_pradesh',
    'lavi_fair',
    'Lavi Fair',
    'లావి మేళా',
    DynamicCategoryType.festival,
    11,
    11,
    70,
  ],
  [
    'jharkhand',
    'tusu_parab',
    'Tusu Parab',
    'టుసు పండుగ',
    DynamicCategoryType.festival,
    1,
    15,
    70,
  ],
  [
    'jharkhand',
    'mage_parab',
    'Mage Parab',
    'మాగే పండుగ',
    DynamicCategoryType.festival,
    2,
    1,
    70,
  ],
  [
    'jharkhand',
    'rohini_festival',
    'Rohini Festival',
    'రోహిణి పండుగ',
    DynamicCategoryType.festival,
    6,
    1,
    70,
  ],
  [
    'karnataka',
    'ugadi_karnataka',
    'Ugadi',
    'ఉగాది',
    DynamicCategoryType.festival,
    3,
    30,
    80,
  ],
  [
    'karnataka',
    'karaga_festival',
    'Karaga Festival',
    'కరగా పండుగ',
    DynamicCategoryType.festival,
    4,
    12,
    70,
  ],
  [
    'karnataka',
    'hampi_utsav',
    'Hampi Utsav',
    'హంపి ఉత్సవ్',
    DynamicCategoryType.festival,
    1,
    10,
    70,
  ],
  ['kerala', 'onam', 'Onam', 'ఓణం', DynamicCategoryType.festival, 9, 5, 90],
  [
    'kerala',
    'nehru_trophy_boat_race',
    'Nehru Trophy Boat Race',
    'నెహ్రూ ట్రోఫీ బోట్ రేస్',
    DynamicCategoryType.festival,
    8,
    10,
    70,
  ],
  [
    'kerala',
    'makaravilakku',
    'Makaravilakku',
    'మకరవిళక్కు',
    DynamicCategoryType.festival,
    1,
    14,
    80,
  ],
  [
    'madhya_pradesh',
    'lokrang_festival',
    'Lokrang Festival',
    'లోకరంగ్ పండుగ',
    DynamicCategoryType.festival,
    1,
    26,
    70,
  ],
  [
    'madhya_pradesh',
    'bhagoria_festival',
    'Bhagoria Festival',
    'భగోరియా పండుగ',
    DynamicCategoryType.festival,
    3,
    1,
    70,
  ],
  [
    'madhya_pradesh',
    'malwa_utsav',
    'Malwa Utsav',
    'మాల్వా ఉత్సవ్',
    DynamicCategoryType.festival,
    5,
    2,
    70,
  ],
  [
    'maharashtra',
    'dahi_handi',
    'Dahi Handi',
    'దహీ హండి',
    DynamicCategoryType.festival,
    8,
    16,
    80,
  ],
  [
    'maharashtra',
    'ashadhi_wari',
    'Ashadhi Wari',
    'ఆషాఢీ వారీ',
    DynamicCategoryType.festival,
    7,
    6,
    80,
  ],
  [
    'maharashtra',
    'ambedkar_jayanti_maharashtra',
    'Dr. Ambedkar Jayanti',
    'డాక్టర్ అంబేద్కర్ జయంతి',
    DynamicCategoryType.jayanthi,
    4,
    14,
    80,
  ],
  [
    'manipur',
    'cheiraoba',
    'Cheiraoba',
    'చెయిరాబా',
    DynamicCategoryType.festival,
    4,
    14,
    70,
  ],
  [
    'manipur',
    'kut_festival',
    'Kut Festival',
    'కుట్ పండుగ',
    DynamicCategoryType.festival,
    11,
    1,
    70,
  ],
  [
    'manipur',
    'lui_ngai_ni',
    'Lui-Ngai-Ni',
    'లుయ్-ంగై-ని',
    DynamicCategoryType.festival,
    2,
    15,
    70,
  ],
  [
    'meghalaya',
    'behdienkhlam',
    'Behdienkhlam',
    'బెహ్డీన్‌ఖ్లామ్',
    DynamicCategoryType.festival,
    7,
    10,
    70,
  ],
  [
    'meghalaya',
    'meghalaya_autumn_festival',
    'Meghalaya Autumn Festival',
    'మేఘాలయ శరద్ ఉత్సవం',
    DynamicCategoryType.festival,
    10,
    25,
    70,
  ],
  [
    'meghalaya',
    'strawberry_festival_meghalaya',
    'Strawberry Festival',
    'స్ట్రాబెర్రీ పండుగ',
    DynamicCategoryType.festival,
    2,
    14,
    70,
  ],
  [
    'mizoram',
    'thalfavang_kut',
    'Thalfavang Kut',
    'థాల్ఫవాంగ్ కూట్',
    DynamicCategoryType.festival,
    11,
    15,
    70,
  ],
  [
    'mizoram',
    'anthurium_festival',
    'Anthurium Festival',
    'ఆంథూరియం పండుగ',
    DynamicCategoryType.festival,
    9,
    20,
    70,
  ],
  [
    'nagaland',
    'aoling_festival',
    'Aoling Festival',
    'ఆఓలింగ్ పండుగ',
    DynamicCategoryType.festival,
    4,
    1,
    70,
  ],
  [
    'nagaland',
    'tokhu_emong',
    'Tokhu Emong',
    'తోఖు ఎమోంగ్',
    DynamicCategoryType.festival,
    11,
    7,
    70,
  ],
  [
    'nagaland',
    'tuluni_festival',
    'Tuluni Festival',
    'తులుని పండుగ',
    DynamicCategoryType.festival,
    7,
    8,
    70,
  ],
  [
    'odisha',
    'konark_dance_festival',
    'Konark Dance Festival',
    'కొణార్క్ నృత్యోత్సవం',
    DynamicCategoryType.festival,
    12,
    1,
    80,
  ],
  [
    'odisha',
    'bali_jatra',
    'Bali Jatra',
    'బాలి జాత్రా',
    DynamicCategoryType.festival,
    11,
    15,
    80,
  ],
  [
    'odisha',
    'chhau_festival',
    'Chhau Festival',
    'ఛౌ పండుగ',
    DynamicCategoryType.festival,
    4,
    11,
    70,
  ],
  [
    'punjab',
    'maghi_mela',
    'Maghi Mela',
    'మాఘీ మేళా',
    DynamicCategoryType.festival,
    1,
    14,
    70,
  ],
  [
    'punjab',
    'basant_panchami_punjab',
    'Basant Panchami',
    'బసంత్ పంచమి',
    DynamicCategoryType.festival,
    2,
    2,
    70,
  ],
  [
    'punjab',
    'shaheedi_jor_mela',
    'Shaheedi Jor Mela',
    'షహీది జోర్ మేళా',
    DynamicCategoryType.regionalSpecial,
    12,
    25,
    70,
  ],
  [
    'rajasthan',
    'desert_festival_jaisalmer',
    'Jaisalmer Desert Festival',
    'జైసల్మేర్ ఎడారి ఉత్సవం',
    DynamicCategoryType.festival,
    2,
    22,
    70,
  ],
  [
    'rajasthan',
    'marwar_festival',
    'Marwar Festival',
    'మార్వార్ ఉత్సవం',
    DynamicCategoryType.festival,
    10,
    12,
    70,
  ],
  [
    'rajasthan',
    'mewar_festival',
    'Mewar Festival',
    'మేవార్ ఉత్సవం',
    DynamicCategoryType.festival,
    4,
    1,
    70,
  ],
  [
    'sikkim',
    'bhumchu',
    'Bhumchu',
    'భూమ్చు',
    DynamicCategoryType.festival,
    3,
    10,
    70,
  ],
  [
    'sikkim',
    'tendong_lho_rum_faat',
    'Tendong Lho Rum Faat',
    'టెండోంగ్ లో రమ్ ఫాత్',
    DynamicCategoryType.festival,
    8,
    8,
    70,
  ],
  [
    'sikkim',
    'maghe_sankranti_sikkim',
    'Maghe Sankranti',
    'మాఘే సంక్రాంతి',
    DynamicCategoryType.festival,
    1,
    15,
    70,
  ],
  [
    'tamil_nadu',
    'karthigai_deepam',
    'Karthigai Deepam',
    'కార్తిగై దీపం',
    DynamicCategoryType.festival,
    12,
    13,
    80,
  ],
  [
    'tamil_nadu',
    'chithirai_thiruvizha',
    'Chithirai Thiruvizha',
    'చిత్రై తిరువిజా',
    DynamicCategoryType.festival,
    4,
    15,
    80,
  ],
  [
    'tamil_nadu',
    'aadi_perukku',
    'Aadi Perukku',
    'ఆడి పెరుక్కు',
    DynamicCategoryType.festival,
    8,
    3,
    70,
  ],
  [
    'tripura',
    'diwali_tripureswari',
    'Diwali at Tripureswari Temple',
    'త్రిపురేశ్వరి దీపావళి',
    DynamicCategoryType.festival,
    10,
    31,
    80,
  ],
  [
    'tripura',
    'neermahal_festival',
    'Neermahal Festival',
    'నీర్మహల్ పండుగ',
    DynamicCategoryType.festival,
    8,
    1,
    70,
  ],
  [
    'tripura',
    'orange_tourism_festival',
    'Orange & Tourism Festival',
    'ఆరెంజ్ టూరిజం పండుగ',
    DynamicCategoryType.festival,
    11,
    20,
    70,
  ],
  [
    'uttar_pradesh',
    'lathmar_holi',
    'Lathmar Holi',
    'లాఠ్మార్ హోళీ',
    DynamicCategoryType.festival,
    3,
    7,
    80,
  ],
  [
    'uttar_pradesh',
    'taj_mahotsav',
    'Taj Mahotsav',
    'తాజ్ మహోత్సవ్',
    DynamicCategoryType.festival,
    2,
    18,
    70,
  ],
  [
    'uttar_pradesh',
    'nauchandi_mela',
    'Nauchandi Mela',
    'నౌచండి మేళా',
    DynamicCategoryType.festival,
    3,
    15,
    70,
  ],
  [
    'uttarakhand',
    'ganga_dussehra_uttarakhand',
    'Ganga Dussehra',
    'గంగా దసరా',
    DynamicCategoryType.festival,
    6,
    16,
    80,
  ],
  [
    'uttarakhand',
    'bikhauti_mela',
    'Bikhauti Mela',
    'బిఖౌతి మేళా',
    DynamicCategoryType.festival,
    4,
    14,
    70,
  ],
  [
    'uttarakhand',
    'nanda_devi_fair',
    'Nanda Devi Fair',
    'నందా దేవి మేళా',
    DynamicCategoryType.festival,
    9,
    1,
    70,
  ],
  [
    'west_bengal',
    'saraswati_puja_west_bengal',
    'Saraswati Puja',
    'సరస్వతి పూజ',
    DynamicCategoryType.festival,
    2,
    2,
    80,
  ],
  [
    'west_bengal',
    'rabindra_jayanti',
    'Rabindra Jayanti',
    'రవీంద్ర జయంతి',
    DynamicCategoryType.jayanthi,
    5,
    7,
    80,
  ],
  [
    'west_bengal',
    'jagaddhatri_puja',
    'Jagaddhatri Puja',
    'జగద్ధాత్రి పూజ',
    DynamicCategoryType.festival,
    11,
    8,
    70,
  ],
  [
    'delhi',
    'phool_walon_ki_sair',
    'Phool Walon Ki Sair',
    'ఫూల్ వాలోన్ కి సైర్',
    DynamicCategoryType.festival,
    9,
    15,
    70,
  ],
  [
    'delhi',
    'qutub_festival',
    'Qutub Festival',
    'కుతుబ్ పండుగ',
    DynamicCategoryType.festival,
    11,
    15,
    70,
  ],
  [
    'delhi',
    'india_international_trade_fair',
    'India International Trade Fair',
    'ఇండియా ఇంటర్నేషనల్ ట్రేడ్ ఫెయిర్',
    DynamicCategoryType.regionalSpecial,
    11,
    14,
    70,
  ],
  [
    'jammu_kashmir',
    'kheer_bhawani_mela',
    'Kheer Bhawani Mela',
    'ఖీర్ భవానీ మేళా',
    DynamicCategoryType.festival,
    6,
    10,
    70,
  ],
  [
    'jammu_kashmir',
    'bahu_mela',
    'Bahu Mela',
    'బాహు మేళా',
    DynamicCategoryType.festival,
    4,
    1,
    70,
  ],
  [
    'jammu_kashmir',
    'shikara_festival',
    'Shikara Festival',
    'శికారా పండుగ',
    DynamicCategoryType.festival,
    7,
    1,
    70,
  ],
  [
    'ladakh',
    'losar_ladakh',
    'Losar Ladakh',
    'లడాఖ్ లోసార్',
    DynamicCategoryType.festival,
    12,
    30,
    80,
  ],
  [
    'ladakh',
    'sindhu_darshan',
    'Sindhu Darshan Festival',
    'సింధు దర్శన్ పండుగ',
    DynamicCategoryType.festival,
    6,
    12,
    70,
  ],
  [
    'ladakh',
    'ladakh_festival',
    'Ladakh Festival',
    'లడాఖ్ పండుగ',
    DynamicCategoryType.festival,
    9,
    1,
    70,
  ],
  [
    'puducherry',
    'bastille_day_puducherry',
    'Bastille Day Puducherry',
    'పుదుచ్చేరి బాస్టిల్ డే',
    DynamicCategoryType.regionalSpecial,
    7,
    14,
    70,
  ],
  [
    'puducherry',
    'fete_de_puducherry',
    'Fete de Puducherry',
    'ఫేట్ డి పుదుచ్చేరి',
    DynamicCategoryType.festival,
    8,
    15,
    70,
  ],
  [
    'puducherry',
    'masimagam_puducherry',
    'Masimagam',
    'మాసిమగం',
    DynamicCategoryType.festival,
    3,
    6,
    70,
  ],
  [
    'chandigarh',
    'rose_festival_chandigarh',
    'Rose Festival',
    'రోజ్ ఫెస్టివల్',
    DynamicCategoryType.festival,
    2,
    23,
    70,
  ],
  [
    'chandigarh',
    'mango_mela_chandigarh',
    'Mango Mela',
    'మ్యాంగో మేళా',
    DynamicCategoryType.festival,
    7,
    6,
    70,
  ],
  [
    'chandigarh',
    'chrysanthemum_show_chandigarh',
    'Chrysanthemum Show',
    'క్రైసాంతిమం షో',
    DynamicCategoryType.festival,
    12,
    13,
    70,
  ],
  [
    'andaman_nicobar',
    'andaman_beach_festival',
    'Andaman Beach Festival',
    'అండమాన్ బీచ్ ఫెస్టివల్',
    DynamicCategoryType.festival,
    4,
    15,
    70,
  ],
  [
    'andaman_nicobar',
    'subhash_chandra_bose_island_day',
    'Subhash Chandra Bose Island Day',
    'సుభాష్ చంద్రబోస్ ద్వీప దినం',
    DynamicCategoryType.regionalSpecial,
    12,
    30,
    70,
  ],
  [
    'lakshadweep',
    'minicoy_fest',
    'Minicoy Fest',
    'మినికోయ్ ఫెస్ట్',
    DynamicCategoryType.festival,
    12,
    1,
    70,
  ],
  [
    'lakshadweep',
    'lakshadweep_lagoon_festival',
    'Lakshadweep Lagoon Festival',
    'లక్షద్వీప్ లగూన్ ఫెస్టివల్',
    DynamicCategoryType.festival,
    1,
    10,
    70,
  ],
  [
    'dadra_nagar_haveli_daman_diu',
    'tarpa_festival',
    'Tarpa Festival',
    'తర్పా పండుగ',
    DynamicCategoryType.festival,
    12,
    25,
    70,
  ],
  [
    'dadra_nagar_haveli_daman_diu',
    'nariyal_poornima_daman_diu',
    'Nariyal Poornima',
    'నారియల్ పూర్ణిమ',
    DynamicCategoryType.festival,
    8,
    19,
    70,
  ],
  [
    'dadra_nagar_haveli_daman_diu',
    'daman_ganga_festival',
    'Daman Ganga Festival',
    'దమన్ గంగా పండుగ',
    DynamicCategoryType.festival,
    12,
    19,
    70,
  ],
  [
    'kerala',
    'mannam_jayanthi',
    'Mannam Jayanthi',
    'మన్నం జయంతి',
    DynamicCategoryType.jayanthi,
    1,
    2,
    80,
  ],
  [
    'kerala',
    'sree_narayana_guru_samadhi',
    'Sree Narayana Guru Samadhi',
    'శ్రీ నారాయణ గురు సమాధి',
    DynamicCategoryType.vardhanthi,
    9,
    21,
    80,
  ],
  [
    'kerala',
    'ayyankali_jayanthi',
    'Ayyankali Jayanthi',
    'అయ్యంకాళి జయంతి',
    DynamicCategoryType.jayanthi,
    8,
    28,
    80,
  ],
  [
    'kerala',
    'karkidaka_vavu',
    'Karkidaka Vavu',
    'కర్కిడక వావు',
    DynamicCategoryType.regionalSpecial,
    8,
    12,
    70,
  ],
  [
    'kerala',
    'theyyam_season',
    'Theyyam Season',
    'తెయ్యం సీజన్',
    DynamicCategoryType.festival,
    12,
    1,
    70,
  ],
  [
    'kerala',
    'aranmula_boat_race',
    'Aranmula Boat Race',
    'అరన్ముల బోట్ రేస్',
    DynamicCategoryType.festival,
    9,
    10,
    70,
  ],
  [
    'tamil_nadu',
    'periyar_jayanthi',
    'Periyar Jayanthi',
    'పెరియార్ జయంతి',
    DynamicCategoryType.jayanthi,
    9,
    17,
    80,
  ],
  [
    'tamil_nadu',
    'kamarajar_jayanthi',
    'Kamarajar Jayanthi / Educational Development Day',
    'కామరాజర్ జయంతి',
    DynamicCategoryType.jayanthi,
    7,
    15,
    80,
  ],
  [
    'tamil_nadu',
    'anna_jayanthi',
    'C.N. Annadurai Jayanthi',
    'అన్నాదురై జయంతి',
    DynamicCategoryType.jayanthi,
    9,
    15,
    80,
  ],
  [
    'tamil_nadu',
    'm_g_ramachandran_jayanthi',
    'M.G. Ramachandran Jayanthi',
    'ఎం.జి. రామచంద్రన్ జయంతి',
    DynamicCategoryType.jayanthi,
    1,
    17,
    80,
  ],
  [
    'tamil_nadu',
    'jayalalithaa_jayanthi',
    'J. Jayalalithaa Jayanthi',
    'జె. జయలలిత జయంతి',
    DynamicCategoryType.jayanthi,
    2,
    24,
    80,
  ],
  [
    'tamil_nadu',
    'jayalalithaa_vardhanthi',
    'J. Jayalalithaa Vardhanthi',
    'జె. జయలలిత వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    12,
    5,
    80,
  ],
  [
    'karnataka',
    'kempegowda_jayanthi',
    'Kempegowda Jayanthi',
    'కెంపేగౌడ జయంతి',
    DynamicCategoryType.jayanthi,
    6,
    27,
    80,
  ],
  [
    'karnataka',
    'kuvempu_jayanthi',
    'Kuvempu Jayanthi',
    'కువెంపు జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    29,
    80,
  ],
  [
    'karnataka',
    'kanakadasa_vardhanthi',
    'Kanakadasa Vardhanthi',
    'కనకదాస వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    12,
    15,
    70,
  ],
  [
    'karnataka',
    'kittur_rani_chennamma_jayanthi',
    'Kittur Rani Chennamma Jayanthi',
    'కిత్తూరు రాణి చెన్నమ్మ జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    23,
    80,
  ],
  [
    'maharashtra',
    'savitribai_phule_jayanthi',
    'Savitribai Phule Jayanthi',
    'సావిత్రిబాయి ఫూలే జయంతి',
    DynamicCategoryType.jayanthi,
    1,
    3,
    80,
  ],
  [
    'maharashtra',
    'jyotiba_phule_jayanthi',
    'Jyotiba Phule Jayanthi',
    'జ్యోతిబా ఫూలే జయంతి',
    DynamicCategoryType.jayanthi,
    4,
    11,
    80,
  ],
  [
    'maharashtra',
    'shahu_maharaj_jayanthi',
    'Chhatrapati Shahu Maharaj Jayanthi',
    'ఛత్రపతి శాహూ మహారాజ్ జయంతి',
    DynamicCategoryType.jayanthi,
    6,
    26,
    80,
  ],
  [
    'maharashtra',
    'bal_gangadhar_tilak_vardhanthi',
    'Bal Gangadhar Tilak Vardhanthi',
    'బాల్ గంగాధర్ తిలక్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    8,
    1,
    80,
  ],
  [
    'gujarat',
    'zaverchand_meghani_jayanthi',
    'Zaverchand Meghani Jayanthi',
    'జవేర్చంద్ మేఘాణీ జయంతి',
    DynamicCategoryType.jayanthi,
    8,
    28,
    70,
  ],
  [
    'gujarat',
    'narmad_jayanthi',
    'Narmad Jayanthi',
    'నర్మద్ జయంతి',
    DynamicCategoryType.jayanthi,
    8,
    24,
    70,
  ],
  [
    'gujarat',
    'sardar_patel_vardhanthi_gujarat',
    'Sardar Patel Vardhanthi',
    'సర్దార్ పటేల్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    12,
    15,
    80,
  ],
  [
    'west_bengal',
    'ishwar_chandra_vidyasagar_jayanthi',
    'Ishwar Chandra Vidyasagar Jayanthi',
    'ఈశ్వర్ చంద్ర విద్యాసాగర్ జయంతి',
    DynamicCategoryType.jayanthi,
    9,
    26,
    80,
  ],
  [
    'west_bengal',
    'ishwar_chandra_vidyasagar_vardhanthi',
    'Ishwar Chandra Vidyasagar Vardhanthi',
    'ఈశ్వర్ చంద్ర విద్యాసాగర్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    7,
    29,
    80,
  ],
  [
    'west_bengal',
    'matangini_hazra_vardhanthi',
    'Matangini Hazra Vardhanthi',
    'మాతంగిని హాజ్రా వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    9,
    29,
    70,
  ],
  [
    'odisha',
    'biju_patnaik_jayanthi',
    'Biju Patnaik Jayanthi / Panchayati Raj Diwas',
    'బిజు పట్నాయక్ జయంతి',
    DynamicCategoryType.jayanthi,
    3,
    5,
    80,
  ],
  [
    'odisha',
    'madhusudan_das_jayanthi',
    'Madhusudan Das Jayanthi',
    'మధుసూదన్ దాస్ జయంతి',
    DynamicCategoryType.jayanthi,
    4,
    28,
    80,
  ],
  [
    'odisha',
    'gopabandhu_das_jayanthi',
    'Gopabandhu Das Jayanthi',
    'గోపబంధు దాస్ జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    9,
    80,
  ],
  [
    'bihar',
    'karpoori_thakur_jayanthi',
    'Karpoori Thakur Jayanthi',
    'కర్పూరి ఠాకూర్ జయంతి',
    DynamicCategoryType.jayanthi,
    1,
    24,
    80,
  ],
  [
    'bihar',
    'dr_rajendra_prasad_jayanthi',
    'Dr. Rajendra Prasad Jayanthi',
    'డాక్టర్ రాజేంద్ర ప్రసాద్ జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    3,
    80,
  ],
  [
    'bihar',
    'jayaprakash_narayan_jayanthi',
    'Jayaprakash Narayan Jayanthi',
    'జయప్రకాశ్ నారాయణ్ జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    11,
    80,
  ],
  [
    'bihar',
    'veer_kunwar_singh_jayanthi',
    'Veer Kunwar Singh Jayanthi',
    'వీర్ కున్వర్ సింగ్ జయంతి',
    DynamicCategoryType.jayanthi,
    4,
    23,
    80,
  ],
  [
    'uttar_pradesh',
    'ram_manohar_lohia_jayanthi',
    'Ram Manohar Lohia Jayanthi',
    'రామ్ మనోహర్ లోహియా జయంతి',
    DynamicCategoryType.jayanthi,
    3,
    23,
    80,
  ],
  [
    'uttar_pradesh',
    'deendayal_upadhyaya_jayanthi',
    'Deendayal Upadhyaya Jayanthi',
    'దీన్‌దయాళ్ ఉపాధ్యాయ జయంతి',
    DynamicCategoryType.jayanthi,
    9,
    25,
    80,
  ],
  [
    'uttar_pradesh',
    'atal_bihari_vajpayee_jayanthi',
    'Atal Bihari Vajpayee Jayanthi',
    'అటల్ బిహారీ వాజ్‌పేయి జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    25,
    80,
  ],
  [
    'uttar_pradesh',
    'atal_bihari_vajpayee_vardhanthi',
    'Atal Bihari Vajpayee Vardhanthi',
    'అటల్ బిహారీ వాజ్‌పేయి వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    8,
    16,
    80,
  ],
  [
    'rajasthan',
    'maharana_pratap_jayanthi',
    'Maharana Pratap Jayanthi',
    'మహారాణా ప్రతాప్ జయంతి',
    DynamicCategoryType.jayanthi,
    5,
    9,
    80,
  ],
  [
    'rajasthan',
    'panna_dhai_jayanthi',
    'Panna Dhai Jayanthi',
    'పన్నా ధాయ్ జయంతి',
    DynamicCategoryType.jayanthi,
    3,
    8,
    70,
  ],
  [
    'rajasthan',
    'gogaji_jayanthi',
    'Gogaji Jayanthi',
    'గోగాజీ జయంతి',
    DynamicCategoryType.jayanthi,
    8,
    20,
    70,
  ],
  [
    'punjab',
    'shaheed_udham_singh_vardhanthi',
    'Shaheed Udham Singh Vardhanthi',
    'షహీద్ ఉధమ్ సింగ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    7,
    31,
    80,
  ],
  [
    'punjab',
    'maharaja_ranjit_singh_vardhanthi',
    'Maharaja Ranjit Singh Vardhanthi',
    'మహారాజా రంజిత్ సింగ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    6,
    27,
    70,
  ],
  [
    'punjab',
    'bhagat_singh_vardhanthi_punjab',
    'Bhagat Singh Vardhanthi / Shaheed Diwas',
    'భగత్ సింగ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    3,
    23,
    80,
  ],
  [
    'haryana',
    'deenbandhu_chhotu_ram_jayanthi',
    'Deenbandhu Chhotu Ram Jayanthi',
    'దీనబంధు చోటూ రామ్ జయంతి',
    DynamicCategoryType.jayanthi,
    11,
    24,
    80,
  ],
  [
    'haryana',
    'kalpana_chawla_jayanthi',
    'Kalpana Chawla Jayanthi',
    'కల్పనా చావ్లా జయంతి',
    DynamicCategoryType.jayanthi,
    3,
    17,
    70,
  ],
  [
    'jharkhand',
    'sidhu_kanhu_hul_diwas',
    'Sidhu Kanhu Hul Diwas',
    'సిధు కాన్హు హుల్ దివస్',
    DynamicCategoryType.regionalSpecial,
    6,
    30,
    80,
  ],
  [
    'jharkhand',
    'tilka_manjhi_jayanthi',
    'Tilka Manjhi Jayanthi',
    'తిల్కా మాంఝీ జయంతి',
    DynamicCategoryType.jayanthi,
    2,
    11,
    70,
  ],
  [
    'jharkhand',
    'jaipal_singh_munda_jayanthi',
    'Jaipal Singh Munda Jayanthi',
    'జైపాల్ సింగ్ ముండా జయంతి',
    DynamicCategoryType.jayanthi,
    1,
    3,
    70,
  ],
  [
    'madhya_pradesh',
    'tantya_bhil_vardhanthi',
    'Tantya Bhil Vardhanthi',
    'టంట్యా భీల్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    12,
    4,
    70,
  ],
  [
    'madhya_pradesh',
    'rani_durgavati_jayanthi',
    'Rani Durgavati Jayanthi',
    'రాణి దుర్గావతి జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    5,
    80,
  ],
  [
    'madhya_pradesh',
    'rani_durgavati_vardhanthi',
    'Rani Durgavati Vardhanthi',
    'రాణి దుర్గావతి వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    6,
    24,
    80,
  ],
  [
    'chhattisgarh',
    'guru_ghasidas_jayanthi',
    'Guru Ghasidas Jayanthi',
    'గురు ఘాసీదాస్ జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    18,
    80,
  ],
  [
    'chhattisgarh',
    'veer_narayan_singh_vardhanthi',
    'Veer Narayan Singh Vardhanthi',
    'వీర్ నారాయణ్ సింగ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    12,
    10,
    80,
  ],
  [
    'assam',
    'gopinath_bordoloi_vardhanthi',
    'Gopinath Bordoloi Vardhanthi',
    'గోపీనాథ్ బోర్డొలొయ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    8,
    5,
    80,
  ],
  [
    'assam',
    'jyoti_prasad_agarwala_vardhanthi',
    'Jyoti Prasad Agarwala Vardhanthi / Silpi Divas',
    'జ్యోతి ప్రసాద్ అగర్వాలా వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    1,
    17,
    80,
  ],
  [
    'assam',
    'bishnu_prasad_rabha_vardhanthi',
    'Bishnu Prasad Rabha Vardhanthi / Rabha Divas',
    'బిష్ణు ప్రసాద్ రాభా వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    6,
    20,
    80,
  ],
  [
    'manipur',
    'bir_tikendrajit_vardhanthi',
    'Bir Tikendrajit Vardhanthi / Patriots Day',
    'బీర్ టికేంద్రజిత్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    8,
    13,
    80,
  ],
  [
    'manipur',
    'nupi_lan_day',
    'Nupi Lan Day',
    'నూపి లాన్ దినం',
    DynamicCategoryType.regionalSpecial,
    12,
    12,
    80,
  ],
  [
    'meghalaya',
    'u_tirot_singh_day',
    'U Tirot Singh Day',
    'యూ తిరోట్ సింగ్ దినం',
    DynamicCategoryType.vardhanthi,
    7,
    17,
    80,
  ],
  [
    'meghalaya',
    'u_kiang_nangbah_day',
    'U Kiang Nangbah Day',
    'యూ కియాంగ్ నాంగ్బా దినం',
    DynamicCategoryType.vardhanthi,
    12,
    30,
    80,
  ],
  [
    'mizoram',
    'remna_ni',
    'Remna Ni / Peace Accord Day',
    'రెమ్నా ని',
    DynamicCategoryType.regionalSpecial,
    6,
    30,
    80,
  ],
  [
    'mizoram',
    'zoram_ni',
    'Zoram Ni',
    'జోరం ని',
    DynamicCategoryType.regionalSpecial,
    6,
    21,
    70,
  ],
  [
    'nagaland',
    'naga_national_day',
    'Naga National Day',
    'నాగా నేషనల్ డే',
    DynamicCategoryType.regionalSpecial,
    8,
    14,
    70,
  ],
  [
    'sikkim',
    'jorethang_maghey_mela',
    'Jorethang Maghey Mela',
    'జోరేథాంగ్ మాఘే మేళా',
    DynamicCategoryType.festival,
    1,
    15,
    70,
  ],
  [
    'sikkim',
    'red_panda_winter_festival',
    'Red Panda Winter Festival',
    'రెడ్ పాండా వింటర్ ఫెస్టివల్',
    DynamicCategoryType.festival,
    12,
    15,
    70,
  ],
  [
    'tripura',
    'chabimura_festival',
    'Chabimura Festival',
    'ఛబిమురా పండుగ',
    DynamicCategoryType.festival,
    1,
    15,
    70,
  ],
  [
    'tripura',
    'tirthamukh_festival',
    'Tirthamukh Festival',
    'తీర్థముఖ్ పండుగ',
    DynamicCategoryType.festival,
    1,
    14,
    70,
  ],
  [
    'tripura',
    'ashokastami_mela',
    'Ashokastami Mela',
    'అశోకాష్టమి మేళా',
    DynamicCategoryType.festival,
    4,
    8,
    70,
  ],
  [
    'andaman_nicobar',
    'veer_savarkar_jayanthi_andaman',
    'Veer Savarkar Jayanthi',
    'వీర్ సావర్కర్ జయంతి',
    DynamicCategoryType.jayanthi,
    5,
    28,
    80,
  ],
  [
    'andaman_nicobar',
    'veer_savarkar_vardhanthi_andaman',
    'Veer Savarkar Vardhanthi',
    'వీర్ సావర్కర్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    2,
    26,
    80,
  ],
  [
    'arunachal_pradesh',
    'daying_ering_jayanthi',
    'Dr. Daying Ering Jayanthi',
    'డాక్టర్ దయింగ్ ఎరింగ్ జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    11,
    80,
  ],
  [
    'arunachal_pradesh',
    'daying_ering_vardhanthi',
    'Dr. Daying Ering Vardhanthi',
    'డాక్టర్ దయింగ్ ఎరింగ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    6,
    21,
    80,
  ],
  [
    'assam',
    'gopinath_bordoloi_jayanthi',
    'Gopinath Bordoloi Jayanthi',
    'గోపీనాథ్ బోర్డొలొయ్ జయంతి',
    DynamicCategoryType.jayanthi,
    6,
    6,
    80,
  ],
  [
    'bihar',
    'karpoori_thakur_vardhanthi',
    'Karpoori Thakur Vardhanthi',
    'కర్పూరి ఠాకూర్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    2,
    17,
    80,
  ],
  [
    'chandigarh',
    'le_corbusier_jayanthi_chandigarh',
    'Le Corbusier Jayanthi',
    'లె కొర్బూజియర్ జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    6,
    70,
  ],
  [
    'chandigarh',
    'le_corbusier_vardhanthi_chandigarh',
    'Le Corbusier Vardhanthi',
    'లె కొర్బూజియర్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    8,
    27,
    70,
  ],
  [
    'dadra_nagar_haveli_daman_diu',
    'govind_guru_jayanthi_dnhdd',
    'Govind Guru Jayanthi',
    'గోవింద్ గురు జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    20,
    70,
  ],
  [
    'dadra_nagar_haveli_daman_diu',
    'govind_guru_vardhanthi_dnhdd',
    'Govind Guru Vardhanthi',
    'గోవింద్ గురు వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    10,
    30,
    70,
  ],
  [
    'delhi',
    'mirza_ghalib_jayanthi_delhi',
    'Mirza Ghalib Jayanthi',
    'మిర్జా గాలిబ్ జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    27,
    70,
  ],
  [
    'delhi',
    'mirza_ghalib_vardhanthi_delhi',
    'Mirza Ghalib Vardhanthi',
    'మిర్జా గాలిబ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    2,
    15,
    70,
  ],
  [
    'goa',
    't_b_cunha_jayanthi',
    'T.B. Cunha Jayanthi',
    'టి.బి. కున్హా జయంతి',
    DynamicCategoryType.jayanthi,
    4,
    2,
    80,
  ],
  [
    'goa',
    't_b_cunha_vardhanthi',
    'T.B. Cunha Vardhanthi',
    'టి.బి. కున్హా వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    9,
    26,
    80,
  ],
  [
    'haryana',
    'deenbandhu_chhotu_ram_vardhanthi',
    'Deenbandhu Chhotu Ram Vardhanthi',
    'దీనబంధు చోటూ రామ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    1,
    9,
    80,
  ],
  [
    'himachal_pradesh',
    'y_s_parmar_jayanthi',
    'Dr. Y.S. Parmar Jayanthi',
    'డాక్టర్ వై.ఎస్. పరమార్ జయంతి',
    DynamicCategoryType.jayanthi,
    8,
    4,
    80,
  ],
  [
    'himachal_pradesh',
    'y_s_parmar_vardhanthi',
    'Dr. Y.S. Parmar Vardhanthi',
    'డాక్టర్ వై.ఎస్. పరమార్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    5,
    2,
    80,
  ],
  [
    'jammu_kashmir',
    'sheikh_abdullah_jayanthi',
    'Sheikh Abdullah Jayanthi',
    'షేక్ అబ్దుల్లా జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    5,
    80,
  ],
  [
    'jammu_kashmir',
    'sheikh_abdullah_vardhanthi',
    'Sheikh Abdullah Vardhanthi',
    'షేక్ అబ్దుల్లా వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    9,
    8,
    80,
  ],
  [
    'jharkhand',
    'tilka_manjhi_vardhanthi',
    'Tilka Manjhi Vardhanthi',
    'తిల్కా మాంఝీ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    1,
    13,
    80,
  ],
  [
    'ladakh',
    'kushok_bakula_jayanthi',
    'Kushok Bakula Rinpoche Jayanthi',
    'కుషోక్ బకుల రిన్‌పోచే జయంతి',
    DynamicCategoryType.jayanthi,
    5,
    19,
    80,
  ],
  [
    'ladakh',
    'kushok_bakula_vardhanthi',
    'Kushok Bakula Rinpoche Vardhanthi',
    'కుషోక్ బకుల రిన్‌పోచే వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    11,
    4,
    80,
  ],
  [
    'lakshadweep',
    'sardar_patel_jayanthi_lakshadweep',
    'Sardar Patel Jayanthi',
    'సర్దార్ పటేల్ జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    31,
    70,
  ],
  [
    'lakshadweep',
    'sardar_patel_vardhanthi_lakshadweep',
    'Sardar Patel Vardhanthi',
    'సర్దార్ పటేల్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    12,
    15,
    70,
  ],
  [
    'manipur',
    'rani_gaidinliu_jayanthi_manipur',
    'Rani Gaidinliu Jayanthi',
    'రాణి గైడిన్‌ల్యూ జయంతి',
    DynamicCategoryType.jayanthi,
    1,
    26,
    80,
  ],
  [
    'meghalaya',
    'williamson_sangma_jayanthi',
    'Williamson A. Sangma Jayanthi',
    'విలియమ్సన్ ఏ. సంగ్మా జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    18,
    80,
  ],
  [
    'mizoram',
    'laldenga_jayanthi',
    'Laldenga Jayanthi',
    'లాల్డెంగా జయంతి',
    DynamicCategoryType.jayanthi,
    6,
    11,
    80,
  ],
  [
    'mizoram',
    'laldenga_vardhanthi',
    'Laldenga Vardhanthi',
    'లాల్డెంగా వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    7,
    7,
    80,
  ],
  [
    'nagaland',
    'a_z_phizo_jayanthi',
    'A.Z. Phizo Jayanthi',
    'ఏ.జెడ్. ఫిజో జయంతి',
    DynamicCategoryType.jayanthi,
    5,
    16,
    80,
  ],
  [
    'nagaland',
    'a_z_phizo_vardhanthi',
    'A.Z. Phizo Vardhanthi',
    'ఏ.జెడ్. ఫిజో వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    4,
    30,
    80,
  ],
  [
    'odisha',
    'biju_patnaik_vardhanthi',
    'Biju Patnaik Vardhanthi',
    'బిజు పట్నాయక్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    4,
    17,
    80,
  ],
  [
    'puducherry',
    'bharathidasan_jayanthi_puducherry',
    'Bharathidasan Jayanthi',
    'భారతిదాసన్ జయంతి',
    DynamicCategoryType.jayanthi,
    4,
    29,
    80,
  ],
  [
    'puducherry',
    'bharathidasan_vardhanthi_puducherry',
    'Bharathidasan Vardhanthi',
    'భారతిదాసన్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    4,
    21,
    80,
  ],
  [
    'punjab',
    'shaheed_udham_singh_jayanthi',
    'Shaheed Udham Singh Jayanthi',
    'షహీద్ ఉధమ్ సింగ్ జయంతి',
    DynamicCategoryType.jayanthi,
    12,
    26,
    80,
  ],
  [
    'rajasthan',
    'maharana_pratap_vardhanthi',
    'Maharana Pratap Vardhanthi',
    'మహారాణా ప్రతాప్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    1,
    19,
    80,
  ],
  [
    'sikkim',
    'tashi_namgyal_jayanthi',
    'Tashi Namgyal Jayanthi',
    'తాషి నామ్‌గ్యాల్ జయంతి',
    DynamicCategoryType.jayanthi,
    10,
    26,
    70,
  ],
  [
    'sikkim',
    'tashi_namgyal_vardhanthi',
    'Tashi Namgyal Vardhanthi',
    'తాషి నామ్‌గ్యాల్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    12,
    2,
    70,
  ],
  [
    'tripura',
    'bir_bikram_jayanthi',
    'Maharaja Bir Bikram Jayanthi',
    'మహారాజా బీర్ బిక్రమ్ జయంతి',
    DynamicCategoryType.jayanthi,
    8,
    19,
    80,
  ],
  [
    'tripura',
    'bir_bikram_vardhanthi',
    'Maharaja Bir Bikram Vardhanthi',
    'మహారాజా బీర్ బిక్రమ్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    5,
    17,
    80,
  ],
  [
    'uttarakhand',
    'govind_ballabh_pant_jayanthi_uttarakhand',
    'Govind Ballabh Pant Jayanthi',
    'గోవింద్ బాల్లభ్ పంత్ జయంతి',
    DynamicCategoryType.jayanthi,
    9,
    10,
    80,
  ],
  [
    'uttarakhand',
    'govind_ballabh_pant_vardhanthi_uttarakhand',
    'Govind Ballabh Pant Vardhanthi',
    'గోవింద్ బాల్లభ్ పంత్ వర్ధంతి',
    DynamicCategoryType.vardhanthi,
    3,
    7,
    80,
  ],
];

List<DynamicCalendarEvent> buildRegionalDynamicEvents() {
  return <DynamicCalendarEvent>[
    for (var index = 0; index < _regionalFixedEventRows.length; index++)
      _regionalFixedRowToEvent(_regionalFixedEventRows[index], index),
  ];
}

DynamicCalendarEvent _regionalFixedRowToEvent(List<Object> row, int index) {
  final regionId = row[0] as String;
  final slug = row[1] as String;
  return DynamicCalendarEvent(
    id: slug,
    slug: slug,
    type: row[4] as DynamicCategoryType,
    scope: DynamicEventScope.india,
    priority: row[7] as int,
    sortOrder: 6000 + index,
    startMonth: row[5] as int,
    startDay: row[6] as int,
    title: DynamicLocalizedTitle(
      telugu: row[3] as String,
      english: row[2] as String,
      hindi: row[2] as String,
    ),
    tags: <String>[regionId, 'regional_special', slug],
    regionIds: <String>{regionId},
  );
}
