const List<String> editorElementCategories = <String>[
  'All',
  'Popular',
  'Badges',
  'Campaign',
  'Festive',
  'Line Arts',
  'Political Logos',
];

const List<String> lineArtsElements = <String>[
  'assets/elements/line_arts/arrow_photos_001.png',
  'assets/elements/line_arts/arrow_photos_002.png',
  'assets/elements/line_arts/arrow_photos_003.png',
  'assets/elements/line_arts/arrow_photos_004.png',
  'assets/elements/line_arts/arrow_photos_005.png',
  'assets/elements/line_arts/arrow_photos_006.png',
  'assets/elements/line_arts/arrow_photos_007.png',
  'assets/elements/line_arts/arrow_photos_008.png',
  'assets/elements/line_arts/arrow_photos_011.png',
  'assets/elements/line_arts/arrow_photos_012.png',
  'assets/elements/line_arts/arrow_photos_013.png',
  'assets/elements/line_arts/arrow_photos_018.png',
  'assets/elements/line_arts/arrow_photos_020.png',
  'assets/elements/line_arts/arrow_photos_021.png',
  'assets/elements/line_arts/arrow_photos_022.png',
  'assets/elements/line_arts/arrow_photos_023.png',
  'assets/elements/line_arts/arrow_photos_024.png',
  'assets/elements/line_arts/arrow_photos_025.png',
  'assets/elements/line_arts/arrow_photos_026.png',
  'assets/elements/line_arts/arrow_photos_028.png',
  'assets/elements/line_arts/arrow_photos_030.png',
  'assets/elements/line_arts/arrow_photos_031.png',
  'assets/elements/line_arts/arrow_photos_032.png',
  'assets/elements/line_arts/arrow_photos_033.png',
  'assets/elements/line_arts/arrow_photos_034.png',
  'assets/elements/line_arts/arrow_photos_035.png',
  'assets/elements/line_arts/arrow_photos_036.png',
  'assets/elements/line_arts/arrow_photos_037.png',
  'assets/elements/line_arts/arrow_photos_038.png',
  'assets/elements/line_arts/arrow_photos_039.png',
  'assets/elements/line_arts/arrow_photos_040.png',
  'assets/elements/line_arts/arrow_photos_041.png',
  'assets/elements/line_arts/arrow_photos_042.png',
  'assets/elements/line_arts/arrow_photos_043.png',
  'assets/elements/line_arts/arrow_photos_044.png',
  'assets/elements/line_arts/arrow_photos_045.png',
  'assets/elements/line_arts/arrow_photos_046.png',
  'assets/elements/line_arts/arrow_photos_047.png',
  'assets/elements/line_arts/arrow_photos_048.png',
  'assets/elements/line_arts/arrow_photos_049.png',
  'assets/elements/line_arts/arrow_photos_050.png',
  'assets/elements/line_arts/arrow_photos_051.png',
  'assets/elements/line_arts/arrow_photos_052.png',
  'assets/elements/line_arts/arrow_photos_053.png',
  'assets/elements/line_arts/arrow_photos_054.png',
  'assets/elements/line_arts/arrow_photos_055.png',
  'assets/elements/line_arts/arrow_photos_056.png',
  'assets/elements/line_arts/arrow_photos_058.png',
  'assets/elements/line_arts/arrow_photos_060.png',
  'assets/elements/line_arts/arrow_photos_061.png',
  'assets/elements/line_arts/arrow_photos_062.png',
  'assets/elements/line_arts/arrow_photos_063.png',
  'assets/elements/line_arts/arrow_photos_064.png',
  'assets/elements/line_arts/arrow_photos_065.png',
  'assets/elements/line_arts/arrow_photos_066.png',
  'assets/elements/line_arts/arrow_photos_067.png',
  'assets/elements/line_arts/arrow_photos_068.png',
  'assets/elements/line_arts/arrow_photos_069.png',
  'assets/elements/line_arts/arrow_photos_072.png',
  'assets/elements/line_arts/arrow_photos_073.png',
  'assets/elements/line_arts/arrow_photos_074.png',
  'assets/elements/line_arts/arrow_photos_075.png',
  'assets/elements/line_arts/arrow_photos_076.png',
  'assets/elements/line_arts/arrow_photos_078.png',
  'assets/elements/line_arts/arrow_photos_079.png',
  'assets/elements/line_arts/arrow_photos_081.png',
  'assets/elements/line_arts/arrow_photos_082.png',
  'assets/elements/line_arts/arrow_photos_083.png',
  'assets/elements/line_arts/arrow_photos_085.png',
  'assets/elements/line_arts/arrow_photos_086.png',
  'assets/elements/line_arts/arrow_photos_087.png',
  'assets/elements/line_arts/arrow_photos_088.png',
  'assets/elements/line_arts/arrow_photos_090.png',
  'assets/elements/line_arts/arrow_photos_092.png',
  'assets/elements/line_arts/arrow_photos_093.png',
  'assets/elements/line_arts/arrow_photos_094.png',
  'assets/elements/line_arts/arrow_photos_095.png',
  'assets/elements/line_arts/arrow_photos_096.png',
  'assets/elements/line_arts/arrow_photos_097.png',
  'assets/elements/line_arts/arrow_photos_098.png',
  'assets/elements/line_arts/arrow_photos_099.png',
  'assets/elements/line_arts/arrow_photos_100.png',
  'assets/elements/line_arts/arrow_photos_101.png',
  'assets/elements/line_arts/arrow_photos_102.png',
  'assets/elements/line_arts/arrow_photos_103.png',
  'assets/elements/line_arts/arrow_photos_104.png',
  'assets/elements/line_arts/arrow_photos_105.png',
  'assets/elements/line_arts/arrow_photos_106.png',
  'assets/elements/line_arts/arrow_photos_107.png',
  'assets/elements/line_arts/arrow_photos_108.png',
  'assets/elements/line_arts/arrow_photos_109.png',
  'assets/elements/line_arts/arrow_photos_110.png',
  'assets/elements/line_arts/arrow_photos_111.png',
  'assets/elements/line_arts/arrow_photos_112.png',
  'assets/elements/line_arts/arrow_photos_113.png',
  'assets/elements/line_arts/arrow_photos_114.png',
  'assets/elements/line_arts/arrow_photos_115.png',
  'assets/elements/line_arts/arrow_photos_116.png',
  'assets/elements/line_arts/arrow_photos_117.png',
  'assets/elements/line_arts/arrow_photos_119.png',
  'assets/elements/line_arts/arrow_photos_120.png',
  'assets/elements/line_arts/arrow_photos_121.png',
  'assets/elements/line_arts/arrow_photos_185.png',
  'assets/elements/line_arts/arrow_photos_187.png',
  'assets/elements/line_arts/arrow_photos_189.png',
  'assets/elements/line_arts/arrow_photos_190.png',
  'assets/elements/line_arts/arrow_photos_191.png',
  'assets/elements/line_arts/arrow_photos_192.png',
];

const List<String> politicalLogoElements = <String>[
  'assets/elements/political/logos/cpi_insignia.png',
  'assets/elements/political/logos/cpm_election_symbol.png',
  'assets/elements/political/logos/political_logo_00.png',
  'assets/elements/political/logos/political_logo_01.png',
  'assets/elements/political/logos/political_logo_02.png',
  'assets/elements/political/logos/political_logo_03.png',
  'assets/elements/political/logos/political_logo_04.png',
  'assets/elements/political/logos/political_logo_05.png',
  'assets/elements/political/logos/political_logo_06.png',
  'assets/elements/political/logos/political_logo_07.png',
  'assets/elements/political/logos/political_logo_08.png',
  'assets/elements/political/logos/political_logo_09.png',
];

const Map<String, List<String>> editorElementCatalog = <String, List<String>>{
  'Popular': <String>['⭐', '🔥', '✅', '🎉', '💥', '⚡'],
  'Badges': <String>['🏆', '🎯', '✅', '📢', '⭐', '🔥'],
  'Campaign': <String>['📢', '🚩', '✅', '⭐', '🎯', '🔥'],
  'Festive': <String>['🎉', '❤️', '🙏', '⭐', '🔥', '💥'],
  'Line Arts': lineArtsElements,
  'Political Logos': politicalLogoElements,
};
