import 'package:mana_poster/features/editor/models/editor_architecture.dart';

const List<String> kEditorTeluguFonts = <String>[
  'Anek Telugu Condensed Bold',
  'Anek Telugu Condensed Extra Bold',
  'Anek Telugu Condensed Extra Light',
  'Anek Telugu Condensed Light',
  'Anek Telugu Condensed Medium',
  'Anek Telugu Condensed Regular',
  'Noto Sans Telugu Condensed Black',
  'Noto Sans Telugu Condensed Bold',
  'Noto Sans Telugu Condensed Extra Bold',
  'Noto Sans Telugu Condensed Extra Light',
  'Noto Sans Telugu Condensed Light',
  'Aaradhana',
  'Abhilasha',
  'Ajantha',
  'Akshara',
  'Amrutha',
  'Anjali',
  'Anu Subhalekha Two',
  'Anupama Bold',
  'Anupama Extra Bold',
  'Anupama Medium',
  'Anupama Thin',
  'Anusha',
  'Apoorva',
  'Ashwini',
  'Bapu Bold',
  'Bapu Brush',
  'Bapu Script',
  'Bharghava',
  'Bhavya',
  'Brahma',
  'Brahma Script',
  'Chandra Script',
  'Deepika',
  'Dharani',
  'Geetha',
  'Gowthami Black',
  'Gowthami Bold',
  'Gowthami Extra Bold',
  'Gowthami Medium',
  'Gowthami Narrow',
  'Gowthami Thin',
  'Harsha',
  'Hiranya',
  'Jyothi',
  'Kalaanjali',
  'Keerthi Font',
  'Kranthi',
  'Kusuma',
  'Maanasa',
  'Madhubala',
  'Meena Script',
  'Mohini',
  'Natyamayuri',
  'Neelima',
  'Padmini',
  'Pallavi Bold',
  'Pallavi Medium',
  'Pallavi Thin',
  'Prabhava',
  'Pragathi',
  'Pragathi Italic',
  'Pragathi Narrow',
  'Pragathi Special',
  'Preethi',
  'Pridhvi',
  'Priyaanka',
  'Priyaanka Bold',
  'Rachana',
  'Rachana Bold',
  'Ramana Brush',
  'Ramana Script',
  'Ramana Script Medium',
  'Ravali',
  'Reshma',
  'Rohini',
  'Saagari',
  'Sanghavi',
  'Sowmya',
  'Sravya',
  'Subhadra',
  'Suchithra',
  'Sujatha',
  'Suneetha',
  'Supriya',
  'Tejafont',
  'Thripura',
  'Udayam',
  'Vaibhav',
  'Vasantha',
  'Vasundhara',
  'Veenaa',
  'Vikaas',
];

const List<String> kEditorEnglishFonts = <String>['Poppins', 'Roboto', 'Lato'];

const String kDefaultEditorTeluguFontFamily = 'Anek Telugu Condensed Regular';

const EditorFontCatalog kEditorFontCatalog = EditorFontCatalog(
  teluguFonts: kEditorTeluguFonts,
  englishFonts: kEditorEnglishFonts,
);
