import 'package:mana_poster/app/localization/app_language.dart';

class PoliticalParty {
  const PoliticalParty({
    required this.id,
    required this.name,
    required this.shortName,
    required this.scope,
    required this.regionIds,
  });

  final String id;
  final String name;
  final String shortName;
  final String scope;
  final Set<String> regionIds;

  bool isRelevantTo(String regionId) {
    return regionIds.isEmpty || regionIds.contains(regionId);
  }

  String nameFor(AppLanguage language) {
    return _localizedPartyNames[id]?[language] ?? name;
  }

  String? get logoAssetPath => _partyLogoAssetPaths[id];
}

const Map<String, String> _partyLogoAssetPaths = <String, String>{
  'bjp': 'assets/elements/political/party_logos/bjp.png',
  'inc': 'assets/elements/political/party_logos/inc.png',
  'aap': 'assets/elements/political/party_logos/aap.png',
  'bsp': 'assets/elements/political/party_logos/bsp.png',
  'cpi_m': 'assets/elements/political/party_logos/cpi_m.png',
  'cpi': 'assets/elements/political/party_logos/cpi.png',
  'npp': 'assets/elements/political/party_logos/npp.png',
  'tdp': 'assets/elements/political/party_logos/tdp.png',
  'ysrcp': 'assets/elements/political/party_logos/ysrcp.jpg',
  'brs': 'assets/elements/political/party_logos/brs.png',
  'aitc': 'assets/elements/political/party_logos/aitc.png',
  'dmk': 'assets/elements/political/party_logos/dmk.png',
  'aiadmk': 'assets/elements/political/party_logos/aiadmk.png',
  'jds': 'assets/elements/political/party_logos/jds.png',
  'shiv_sena': 'assets/elements/political/party_logos/shiv_sena.png',
  'ncp': 'assets/elements/political/party_logos/ncp.png',
  'rjd': 'assets/elements/political/party_logos/rjd.jpg',
  'jdu': 'assets/elements/political/party_logos/jdu.png',
  'sp': 'assets/elements/political/party_logos/sp.png',
  'rld': 'assets/elements/political/party_logos/rld.jpg',
  'sad': 'assets/elements/political/party_logos/sad.png',
  'bjd': 'assets/elements/political/party_logos/bjd.png',
  'jmm': 'assets/elements/political/party_logos/jmm.png',
  'skm': 'assets/elements/political/party_logos/skm.png',
  'mnf': 'assets/elements/political/party_logos/mnf.jpg',
  'npf': 'assets/elements/political/party_logos/npf.png',
  'jknc': 'assets/elements/political/party_logos/jknc.png',
  'pdp': 'assets/elements/political/party_logos/pdp.png',
  'agp': 'assets/elements/political/party_logos/agp.png',
  'udp': 'assets/elements/political/party_logos/udp.jpg',
  'tmp': 'assets/elements/political/party_logos/tmp.jpg',
  'mgp': 'assets/elements/political/party_logos/mgp.jpg',
  'inld': 'assets/elements/political/party_logos/inld.png',
  'jjp': 'assets/elements/political/party_logos/jjp.jpg',
  'aifb': 'assets/elements/political/party_logos/aifb.png',
  'rsp': 'assets/elements/political/party_logos/rsp.png',
  'iuml': 'assets/elements/political/party_logos/iuml.jpg',
  'kc_m': 'assets/elements/political/party_logos/kc_m.png',
  'kc': 'assets/elements/political/party_logos/kc.png',
  'cpi_ml_l': 'assets/elements/political/party_logos/cpi_ml_l.png',
  'aimim': 'assets/elements/political/party_logos/aimim.png',
  'ajsupa': 'assets/elements/political/party_logos/ajsupa.jpg',
  'ad_s': 'assets/elements/political/party_logos/ad_s.jpg',
  'ljp_rv': 'assets/elements/political/party_logos/ljp_rv.jpg',
  'rljp': 'assets/elements/political/party_logos/rljp.jpg',
  'ham_s': 'assets/elements/political/party_logos/ham_s.jpg',
  'vip': 'assets/elements/political/party_logos/vip.png',
  'jsp': 'assets/elements/political/party_logos/jsp.png',
  'ntk': 'assets/elements/political/party_logos/ntk.jpg',
  'pmk': 'assets/elements/political/party_logos/pmk.png',
  'vck': 'assets/elements/political/party_logos/vck.png',
  'mdmk': 'assets/elements/political/party_logos/mdmk.png',
  'dmdk': 'assets/elements/political/party_logos/dmdk.png',
  'aiudf': 'assets/elements/political/party_logos/aiudf.webp',
  'bpf': 'assets/elements/political/party_logos/bpf.svg',
  'uppl': 'assets/elements/political/party_logos/uppl.svg',
  'zpm': 'assets/elements/political/party_logos/zpm.svg',
  'ndpp': 'assets/elements/political/party_logos/ndpp.svg',
  'ipft': 'assets/elements/political/party_logos/ipft.svg',
  'rgp': 'assets/elements/political/party_logos/rgp.jpg',
  'gfp': 'assets/elements/political/party_logos/gfp.jpg',
  'hspdp': 'assets/elements/political/party_logos/hspdp.png',
  'vpp': 'assets/elements/political/party_logos/vpp.svg',
  'ppa': 'assets/elements/political/party_logos/ppa.svg',
  'bap': 'assets/elements/political/party_logos/bap.png',
  'rpi_a': 'assets/elements/political/party_logos/rpi_a.png',
  'mns': 'assets/elements/political/party_logos/mns.jpg',
  'swabhimani': 'assets/elements/political/party_logos/swabhimani.jpg',
  'prahar': 'assets/elements/political/party_logos/prahar.jpg',
  'sdf': 'assets/elements/political/party_logos/sdf.png',
  'rlp': 'assets/elements/political/party_logos/rlp.svg',
  'sbsp': 'assets/elements/political/party_logos/sbsp.jpg',
  'ncp_sp': 'assets/elements/political/party_logos/ncp_sp.jpg',
  'shs_ubt': 'assets/elements/political/party_logos/shs_ubt.jpg',
  'jkpc': 'assets/elements/political/party_logos/jkpc.svg',
  'kpa': 'assets/elements/political/party_logos/kpa.svg',
  'ukd': 'assets/elements/political/party_logos/ukd.gif',
  'jccj': 'assets/elements/political/party_logos/jccj.svg',
  'tvk': 'assets/elements/political/party_logos/tvk.png',
  'tmc_m': 'assets/elements/political/party_logos/tmc_m.png',
  'vba': 'assets/elements/political/party_logos/vba.jpg',
  'wpi': 'assets/elements/political/party_logos/wpi.jpg',
  'jsdl': 'assets/elements/political/party_logos/jsdl.png',
};

const Map<String, Map<AppLanguage, String>> _localizedPartyNames =
    <String, Map<AppLanguage, String>>{
      'bjp': <AppLanguage, String>{
        AppLanguage.telugu: 'భారతీయ జనతా పార్టీ',
        AppLanguage.hindi: 'भारतीय जनता पार्टी',
        AppLanguage.tamil: 'பாரதிய ஜனதா கட்சி',
        AppLanguage.kannada: 'ಭಾರತೀಯ ಜನತಾ ಪಕ್ಷ',
        AppLanguage.malayalam: 'ഭാരതീയ ജനതാ പാർട്ടി',
      },
      'inc': <AppLanguage, String>{
        AppLanguage.telugu: 'భారత జాతీయ కాంగ్రెస్',
        AppLanguage.hindi: 'भारतीय राष्ट्रीय कांग्रेस',
        AppLanguage.tamil: 'இந்திய தேசிய காங்கிரஸ்',
        AppLanguage.kannada: 'ಭಾರತೀಯ ರಾಷ್ಟ್ರೀಯ ಕಾಂಗ್ರೆಸ್',
        AppLanguage.malayalam: 'ഇന്ത്യൻ നാഷണൽ കോൺഗ്രസ്',
      },
      'aap': <AppLanguage, String>{
        AppLanguage.telugu: 'ఆమ్ ఆద్మీ పార్టీ',
        AppLanguage.hindi: 'आम आदमी पार्टी',
        AppLanguage.tamil: 'ஆம் ஆத்மி கட்சி',
        AppLanguage.kannada: 'ಆಮ್ ಆದ್ಮಿ ಪಕ್ಷ',
        AppLanguage.malayalam: 'ആം ആദ്മി പാർട്ടി',
      },
      'bsp': <AppLanguage, String>{
        AppLanguage.telugu: 'బహుజన్ సమాజ్ పార్టీ',
        AppLanguage.hindi: 'बहुजन समाज पार्टी',
        AppLanguage.tamil: 'பகுஜன் சமாஜ் கட்சி',
        AppLanguage.kannada: 'ಬಹುಜನ ಸಮಾಜ ಪಕ್ಷ',
        AppLanguage.malayalam: 'ബഹുജൻ സമാജ് പാർട്ടി',
      },
      'tdp': <AppLanguage, String>{
        AppLanguage.telugu: 'తెలుగు దేశం పార్టీ',
        AppLanguage.hindi: 'तेलुगु देशम पार्टी',
        AppLanguage.tamil: 'தெலுங்கு தேசம் கட்சி',
        AppLanguage.kannada: 'ತೆಲುಗು ದೇಶಂ ಪಕ್ಷ',
        AppLanguage.malayalam: 'തെലുങ്കു ദേശം പാർട്ടി',
      },
      'ysrcp': <AppLanguage, String>{
        AppLanguage.telugu: 'వైఎస్ఆర్ కాంగ్రెస్ పార్టీ',
        AppLanguage.hindi: 'वाईएसआर कांग्रेस पार्टी',
        AppLanguage.tamil: 'ஒய்எஸ்ஆர் காங்கிரஸ் கட்சி',
        AppLanguage.kannada: 'ವೈಎಸ್‌ಆರ್ ಕಾಂಗ್ರೆಸ್ ಪಕ್ಷ',
        AppLanguage.malayalam: 'വൈഎസ്ആർ കോൺഗ്രസ് പാർട്ടി',
      },
      'brs': <AppLanguage, String>{
        AppLanguage.telugu: 'భారత్ రాష్ట్ర సమితి',
        AppLanguage.hindi: 'भारत राष्ट्र समिति',
        AppLanguage.tamil: 'பாரத் ராஷ்ட்ர சமிதி',
        AppLanguage.kannada: 'ಭಾರತ್ ರಾಷ್ಟ್ರ ಸಮಿತಿ',
        AppLanguage.malayalam: 'ഭാരത് രാഷ്ട്ര സമിതി',
      },
      'aitc': <AppLanguage, String>{
        AppLanguage.telugu: 'ఆల్ ఇండియా తృణమూల్ కాంగ్రెస్',
        AppLanguage.hindi: 'ऑल इंडिया तृणमूल कांग्रेस',
        AppLanguage.bengali: 'সর্বভারতীয় তৃণমূল কংগ্রেস',
      },
      'dmk': <AppLanguage, String>{
        AppLanguage.telugu: 'ద్రావిడ మున్నేత్ర కళగం',
        AppLanguage.tamil: 'திராவிட முன்னேற்றக் கழகம்',
      },
      'aiadmk': <AppLanguage, String>{
        AppLanguage.telugu: 'ఆల్ ఇండియా అన్నా ద్రావిడ మున్నేత్ర కళగం',
        AppLanguage.tamil: 'அனைத்திந்திய அண்ணா திராவிட முன்னேற்றக் கழகம்',
      },
      'jds': <AppLanguage, String>{
        AppLanguage.telugu: 'జనతా దళ్ (సెక్యులర్)',
        AppLanguage.hindi: 'जनता दल (सेक्युलर)',
        AppLanguage.kannada: 'ಜನತಾ ದಳ (ಜಾತ್ಯತೀತ)',
      },
      'shiv_sena': <AppLanguage, String>{
        AppLanguage.telugu: 'శివసేన',
        AppLanguage.hindi: 'शिवसेना',
        AppLanguage.marathi: 'शिवसेना',
      },
      'ncp': <AppLanguage, String>{
        AppLanguage.telugu: 'నేషనలిస్ట్ కాంగ్రెస్ పార్టీ',
        AppLanguage.hindi: 'राष्ट्रवादी कांग्रेस पार्टी',
        AppLanguage.marathi: 'राष्ट्रवादी काँग्रेस पक्ष',
      },
      'rjd': <AppLanguage, String>{
        AppLanguage.telugu: 'రాష్ట్రీయ జనతా దళ్',
        AppLanguage.hindi: 'राष्ट्रीय जनता दल',
      },
      'jdu': <AppLanguage, String>{
        AppLanguage.telugu: 'జనతా దళ్ (యునైటెడ్)',
        AppLanguage.hindi: 'जनता दल (यूनाइटेड)',
      },
      'sp': <AppLanguage, String>{
        AppLanguage.telugu: 'సమాజ్‌వాది పార్టీ',
        AppLanguage.hindi: 'समाजवादी पार्टी',
      },
      'rld': <AppLanguage, String>{
        AppLanguage.telugu: 'రాష్ట్రీయ లోక్ దళ్',
        AppLanguage.hindi: 'राष्ट्रीय लोक दल',
      },
      'sad': <AppLanguage, String>{
        AppLanguage.telugu: 'శిరోమణి అకాలీ దళ్',
        AppLanguage.hindi: 'शिरोमणि अकाली दल',
        AppLanguage.punjabi: 'ਸ਼੍ਰੋਮਣੀ ਅਕਾਲੀ ਦਲ',
      },
      'bjd': <AppLanguage, String>{
        AppLanguage.telugu: 'బిజూ జనతా దళ్',
        AppLanguage.hindi: 'बीजू जनता दल',
        AppLanguage.odia: 'ବିଜୁ ଜନତା ଦଳ',
      },
      'jmm': <AppLanguage, String>{
        AppLanguage.telugu: 'జార్ఖండ్ ముక్తి మోర్చా',
        AppLanguage.hindi: 'झारखंड मुक्ति मोर्चा',
      },
      'skm': <AppLanguage, String>{
        AppLanguage.telugu: 'సిక్కిం క్రాంతికారి మోర్చా',
        AppLanguage.hindi: 'सिक्किम क्रांतिकारी मोर्चा',
        AppLanguage.nepali: 'सिक्किम क्रान्तिकारी मोर्चा',
      },
      'mnf': <AppLanguage, String>{
        AppLanguage.telugu: 'మిజో నేషనల్ ఫ్రంట్',
        AppLanguage.hindi: 'मिजो नेशनल फ्रंट',
        AppLanguage.mizo: 'Mizo National Front',
      },
      'npf': <AppLanguage, String>{
        AppLanguage.telugu: 'నాగా పీపుల్స్ ఫ్రంట్',
        AppLanguage.hindi: 'नागा पीपुल्स फ्रंट',
      },
      'jknc': <AppLanguage, String>{
        AppLanguage.telugu: 'నేషనల్ కాన్ఫరెన్స్',
        AppLanguage.hindi: 'नेशनल कॉन्फ्रेंस',
      },
      'pdp': <AppLanguage, String>{
        AppLanguage.telugu: 'పీపుల్స్ డెమోక్రటిక్ పార్టీ',
        AppLanguage.hindi: 'पीपुल्स डेमोक्रेटिक पार्टी',
      },
      'agp': <AppLanguage, String>{
        AppLanguage.telugu: 'అసోం గణ పరిషద్',
        AppLanguage.hindi: 'असम गण परिषद',
        AppLanguage.assamese: 'অসম গণ পৰিষদ',
      },
      'udp': <AppLanguage, String>{
        AppLanguage.telugu: 'యునైటెడ్ డెమోక్రటిక్ పార్టీ',
        AppLanguage.hindi: 'यूनाइटेड डेमोक्रेटिक पार्टी',
      },
      'tmp': <AppLanguage, String>{
        AppLanguage.telugu: 'టిప్రా మోతా పార్టీ',
        AppLanguage.hindi: 'टिपरा मोथा पार्टी',
        AppLanguage.bengali: 'টিপ্রা মথা পার্টি',
      },
      'mgp': <AppLanguage, String>{
        AppLanguage.telugu: 'మహారాష్ట్రవాది గోమంతక్ పార్టీ',
        AppLanguage.hindi: 'महाराष्ट्रवादी गोमांतक पार्टी',
        AppLanguage.konkani: 'महाराष्ट्रवादी गोमंतक पक्ष',
      },
      'inld': <AppLanguage, String>{
        AppLanguage.telugu: 'ఇండియన్ నేషనల్ లోక్ దళ్',
        AppLanguage.hindi: 'इंडियन नेशनल लोक दल',
      },
      'jjp': <AppLanguage, String>{
        AppLanguage.telugu: 'జననాయక్ జనతా పార్టీ',
        AppLanguage.hindi: 'जननायक जनता पार्टी',
      },
      'cpi_m': <AppLanguage, String>{
        AppLanguage.telugu: 'భారత కమ్యూనిస్టు పార్టీ (మార్క్సిస్టు)',
        AppLanguage.hindi: 'भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)',
        AppLanguage.malayalam:
            'കമ്മ്യൂണിസ്റ്റ് പാർട്ടി ഓഫ് ഇന്ത്യ (മാർക്സിസ്റ്റ്)',
      },
      'cpi': <AppLanguage, String>{
        AppLanguage.telugu: 'భారత కమ్యూనిస్టు పార్టీ',
        AppLanguage.hindi: 'भारतीय कम्युनिस्ट पार्टी',
        AppLanguage.tamil: 'இந்திய கம்யூனிஸ்ட் கட்சி',
        AppLanguage.kannada: 'ಭಾರತ ಕಮ್ಯುನಿಸ್ಟ್ ಪಕ್ಷ',
        AppLanguage.malayalam: 'കമ്മ്യൂണിസ്റ്റ് പാർട്ടി ഓഫ് ഇന്ത്യ',
        AppLanguage.bengali: 'ভারতীয় কমিউনিস্ট পার্টি',
      },
      'npp': <AppLanguage, String>{
        AppLanguage.telugu: 'నేషనల్ పీపుల్స్ పార్టీ',
        AppLanguage.hindi: 'नेशनल पीपुल्स पार्टी',
      },
      'aifb': <AppLanguage, String>{
        AppLanguage.telugu: 'ఆల్ ఇండియా ఫార్వర్డ్ బ్లాక్',
        AppLanguage.hindi: 'ऑल इंडिया फॉरवर्ड ब्लॉक',
        AppLanguage.bengali: 'অল ইন্ডিয়া ফরওয়ার্ড ব্লক',
      },
      'rsp': <AppLanguage, String>{
        AppLanguage.telugu: 'రివల్యూషనరీ సోషలిస్ట్ పార్టీ',
        AppLanguage.hindi: 'रिवोल्यूशनरी सोशलिस्ट पार्टी',
        AppLanguage.malayalam: 'റവല്യൂഷണറി സോഷ്യലിസ്റ്റ് പാർട്ടി',
        AppLanguage.bengali: 'রেভলিউশনারি সোশ্যালিস্ট পার্টি',
      },
      'iuml': <AppLanguage, String>{
        AppLanguage.telugu: 'ఇండియన్ యూనియన్ ముస్లిం లీగ్',
        AppLanguage.hindi: 'इंडियन यूनियन मुस्लिम लीग',
        AppLanguage.malayalam: 'ഇന്ത്യൻ യൂണിയൻ മുസ്ലിം ലീഗ്',
      },
      'kc_m': <AppLanguage, String>{
        AppLanguage.telugu: 'కేరళ కాంగ్రెస్ (ఎం)',
        AppLanguage.hindi: 'केरल कांग्रेस (एम)',
        AppLanguage.malayalam: 'കേരള കോൺഗ്രസ് (എം)',
      },
      'kc': <AppLanguage, String>{
        AppLanguage.telugu: 'కేరళ కాంగ్రెస్',
        AppLanguage.hindi: 'केरल कांग्रेस',
        AppLanguage.malayalam: 'കേരള കോൺഗ്രസ്',
      },
      'cpi_ml_l': <AppLanguage, String>{
        AppLanguage.telugu:
            'భారత కమ్యూనిస్టు పార్టీ (మార్క్సిస్టు-లెనినిస్టు) లిబరేషన్',
        AppLanguage.hindi:
            'भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी-लेनिनवादी) लिबरेशन',
      },
      'aimim': <AppLanguage, String>{
        AppLanguage.telugu: 'ఆల్ ఇండియా మజ్లిస్-ఏ-ఇత్తెహాదుల్ ముస్లిమీన్',
        AppLanguage.hindi: 'ऑल इंडिया मजलिस-ए-इत्तेहादुल मुस्लिमीन',
        AppLanguage.marathi: 'ऑल इंडिया मजलिस-ए-इत्तेहादुल मुस्लिमीन',
      },
      'ajsupa': <AppLanguage, String>{
        AppLanguage.telugu: 'ఏజేఎస్‌యూ పార్టీ',
        AppLanguage.hindi: 'आजसू पार्टी',
      },
      'ad_s': <AppLanguage, String>{
        AppLanguage.telugu: 'అప్నా దళ్ (సోనీలాల్)',
        AppLanguage.hindi: 'अपना दल (सोनेलाल)',
      },
      'ljp_rv': <AppLanguage, String>{
        AppLanguage.telugu: 'లోక్ జనశక్తి పార్టీ (రామ్ విలాస్)',
        AppLanguage.hindi: 'लोक जनशक्ति पार्टी (राम विलास)',
      },
      'rljp': <AppLanguage, String>{
        AppLanguage.telugu: 'రాష్ట్రీయ లోక్ జనశక్తి పార్టీ',
        AppLanguage.hindi: 'राष्ट्रीय लोक जनशक्ति पार्टी',
      },
      'ham_s': <AppLanguage, String>{
        AppLanguage.telugu: 'హిందుస్తానీ అవామ్ మోర్చా (సెక్యులర్)',
        AppLanguage.hindi: 'हिंदुस्तानी आवाम मोर्चा (सेक्युलर)',
      },
      'vip': <AppLanguage, String>{
        AppLanguage.telugu: 'వికాస్షీల్ ఇన్సాన్ పార్టీ',
        AppLanguage.hindi: 'विकासशील इंसान पार्टी',
      },
      'jsp': <AppLanguage, String>{
        AppLanguage.telugu: 'జనసేన పార్టీ',
        AppLanguage.hindi: 'जन सेना पार्टी',
      },
      'ntk': <AppLanguage, String>{
        AppLanguage.telugu: 'నామ్ తమిళర్ కచ్చి',
        AppLanguage.hindi: 'नाम तमिलर कच्ची',
        AppLanguage.tamil: 'நாம் தமிழர் கட்சி',
      },
      'pmk': <AppLanguage, String>{
        AppLanguage.telugu: 'పట్టాలి మక్కల్ కచ్చి',
        AppLanguage.hindi: 'पट्टाली मक्कल कच्ची',
        AppLanguage.tamil: 'பாட்டாளி மக்கள் கட்சி',
      },
      'vck': <AppLanguage, String>{
        AppLanguage.telugu: 'విడுதలై చిరుతైగల్ కచ్చి',
        AppLanguage.hindi: 'विदुथलाई चिरुथैगल कच्ची',
        AppLanguage.tamil: 'விடுதலை சிறுத்தைகள் கட்சி',
      },
      'mdmk': <AppLanguage, String>{
        AppLanguage.telugu: 'మరుమలార్చి ద్రావిడ మున్నేత్ర కళగం',
        AppLanguage.hindi: 'मरुमलार्चि द्रविड़ मुनेत्र कड़गम',
        AppLanguage.tamil: 'மறுமலர்ச்சி திராவிட முன்னேற்றக் கழகம்',
      },
      'dmdk': <AppLanguage, String>{
        AppLanguage.telugu: 'దేశీయ ముర్పోక్కు ద్రావిడ కళగం',
        AppLanguage.hindi: 'देसिया मुरपोक्कु द्रविड़ कड़गम',
        AppLanguage.tamil: 'தேசிய முற்போக்கு திராவிட கழகம்',
      },
      'aiudf': <AppLanguage, String>{
        AppLanguage.telugu: 'ఆల్ ఇండియా యునైటెడ్ డెమోక్రటిక్ ఫ్రంట్',
        AppLanguage.hindi: 'ऑल इंडिया यूनाइटेड डेमोक्रेटिक फ्रंट',
        AppLanguage.assamese: 'অল ইণ্ডিয়া ইউনাইটেড ডেমোক্ৰেটিক ফ্ৰণ্ট',
      },
      'bpf': <AppLanguage, String>{
        AppLanguage.telugu: 'బోడోలాండ్ పీపుల్స్ ఫ్రంట్',
        AppLanguage.hindi: 'बोडोलैंड पीपुल्स फ्रंट',
        AppLanguage.assamese: 'বড়োলেণ্ড পিপলছ ফ্ৰণ্ট',
      },
      'uppl': <AppLanguage, String>{
        AppLanguage.telugu: 'యునైటెడ్ పీపుల్స్ పార్టీ లిబరల్',
        AppLanguage.hindi: 'यूनाइटेड पीपुल्स पार्टी लिबरल',
        AppLanguage.assamese: 'ইউনাইটেড পিপলছ পাৰ্টি লিবাৰেল',
      },
      'zpm': <AppLanguage, String>{
        AppLanguage.telugu: 'జోరం పీపుల్స్ మూవ్‌మెంట్',
        AppLanguage.hindi: 'जोरम पीपुल्स मूवमेंट',
        AppLanguage.mizo: 'Zoram People’s Movement',
      },
      'ndpp': <AppLanguage, String>{
        AppLanguage.telugu: 'నేషనలిస్ట్ డెమోక్రటిక్ ప్రోగ్రెసివ్ పార్టీ',
        AppLanguage.hindi: 'नेशनलिस्ट डेमोक्रेटिक प्रोग्रेसिव पार्टी',
      },
      'ipft': <AppLanguage, String>{
        AppLanguage.telugu: 'ఇండిజినస్ పీపుల్స్ ఫ్రంట్ ఆఫ్ త్రిపుర',
        AppLanguage.hindi: 'इंडिजिनस पीपुल्स फ्रंट ऑफ त्रिपुरा',
        AppLanguage.bengali: 'ইন্ডিজেনাস পিপলস ফ্রন্ট অফ ত্রিপুরা',
      },
      'rgp': <AppLanguage, String>{
        AppLanguage.telugu: 'రివల్యూషనరీ గోవాన్స్ పార్టీ',
        AppLanguage.hindi: 'रिवोल्यूशनरी गोअन्स पार्टी',
        AppLanguage.konkani: 'Revolutionary Goans Party',
      },
      'gfp': <AppLanguage, String>{
        AppLanguage.telugu: 'గోవా ఫార్వర్డ్ పార్టీ',
        AppLanguage.hindi: 'गोवा फॉरवर्ड पार्टी',
        AppLanguage.konkani: 'Goa Forward Party',
      },
      'hspdp': <AppLanguage, String>{
        AppLanguage.telugu: 'హిల్ స్టేట్ పీపుల్స్ డెమోక్రటిక్ పార్టీ',
        AppLanguage.hindi: 'हिल स्टेट पीपुल्स डेमोक्रेटिक पार्टी',
      },
      'vpp': <AppLanguage, String>{
        AppLanguage.telugu: 'వాయిస్ ఆఫ్ ది పీపుల్ పార్టీ',
        AppLanguage.hindi: 'वॉइस ऑफ द पीपल पार्टी',
      },
      'ppa': <AppLanguage, String>{
        AppLanguage.telugu: 'పీపుల్స్ పార్టీ ఆఫ్ అరుణాచల్',
        AppLanguage.hindi: 'पीपुल्स पार्टी ऑफ अरुणाचल',
      },
      'bap': <AppLanguage, String>{
        AppLanguage.telugu: 'భారత్ ఆదివాసీ పార్టీ',
        AppLanguage.hindi: 'भारत आदिवासी पार्टी',
      },
      'rpi_a': <AppLanguage, String>{
        AppLanguage.telugu: 'రిపబ్లికన్ పార్టీ ఆఫ్ ఇండియా (ఏ)',
        AppLanguage.hindi: 'रिपब्लिकन पार्टी ऑफ इंडिया (ए)',
        AppLanguage.marathi: 'रिपब्लिकन पार्टी ऑफ इंडिया (ए)',
      },
      'mns': <AppLanguage, String>{
        AppLanguage.telugu: 'మహారాష్ట్ర నవనిర్మాణ సేన',
        AppLanguage.hindi: 'महाराष्ट्र नवनिर्माण सेना',
        AppLanguage.marathi: 'महाराष्ट्र नवनिर्माण सेना',
      },
      'swabhimani': <AppLanguage, String>{
        AppLanguage.telugu: 'స్వాభిమాని పక్ష',
        AppLanguage.hindi: 'स्वाभिमानी पक्ष',
        AppLanguage.marathi: 'स्वाभिमानी पक्ष',
      },
      'prahar': <AppLanguage, String>{
        AppLanguage.telugu: 'ప్రహార్ జనశక్తి పార్టీ',
        AppLanguage.hindi: 'प्रहार जनशक्ति पार्टी',
        AppLanguage.marathi: 'प्रहार जनशक्ति पक्ष',
      },
      'sdf': <AppLanguage, String>{
        AppLanguage.telugu: 'సిక్కిం డెమోక్రటిక్ ఫ్రంట్',
        AppLanguage.hindi: 'सिक्किम डेमोक्रेटिक फ्रंट',
        AppLanguage.nepali: 'सिक्किम डेमोक्रेटिक फ्रन्ट',
      },
      'rlp': <AppLanguage, String>{
        AppLanguage.telugu: 'రాష్ట్రీయ లోకతాంత్రిక్ పార్టీ',
        AppLanguage.hindi: 'राष्ट्रीय लोकतांत्रिक पार्टी',
      },
      'sbsp': <AppLanguage, String>{
        AppLanguage.telugu: 'సుహెల్‌దేవ్ భారతీయ సమాజ్ పార్టీ',
        AppLanguage.hindi: 'सुहेलदेव भारतीय समाज पार्टी',
      },
      'ncp_sp': <AppLanguage, String>{
        AppLanguage.telugu: 'నేషనలిస్ట్ కాంగ్రెస్ పార్టీ - శరద్‌చంద్ర పవార్',
        AppLanguage.hindi: 'राष्ट्रवादी कांग्रेस पार्टी - शरदचंद्र पवार',
        AppLanguage.marathi: 'राष्ट्रवादी काँग्रेस पक्ष - शरदचंद्र पवार',
      },
      'shs_ubt': <AppLanguage, String>{
        AppLanguage.telugu: 'శివసేన (ఉద్ధవ్ బాలాసాహెబ్ ठाकरे)',
        AppLanguage.hindi: 'शिवसेना (उद्धव बालासाहेब ठाकरे)',
        AppLanguage.marathi: 'शिवसेना (उद्धव बाळासाहेब ठाकरे)',
      },
      'jkpc': <AppLanguage, String>{
        AppLanguage.telugu: 'జమ్మూ కాశ్మీర్ పీపుల్స్ కాన్ఫరెన్స్',
        AppLanguage.hindi: 'जम्मू कश्मीर पीपुल्स कॉन्फ्रेंस',
        AppLanguage.kashmiri: 'Jammu and Kashmir People’s Conference',
      },
      'kpa': <AppLanguage, String>{
        AppLanguage.telugu: 'కుకి పీపుల్స్ అలయన్స్',
        AppLanguage.hindi: 'कुकी पीपुल्स अलायंस',
        AppLanguage.meitei: 'Kuki People’s Alliance',
      },
      'ukd': <AppLanguage, String>{
        AppLanguage.telugu: 'ఉత్తరాఖండ్ క్రాంతి దళ్',
        AppLanguage.hindi: 'उत्तराखंड क्रांति दल',
      },
      'jccj': <AppLanguage, String>{
        AppLanguage.telugu: 'జనతా కాంగ్రెస్ ఛత్తీస్‌గఢ్ (జె)',
        AppLanguage.hindi: 'जनता कांग्रेस छत्तीसगढ़ (जे)',
      },
      'tvk': <AppLanguage, String>{
        AppLanguage.telugu: 'తమిళగ వెట్రి కళగం',
        AppLanguage.hindi: 'तमिलगा वेट्री कड़गम',
        AppLanguage.tamil: 'தமிழக வெற்றிக் கழகம்',
      },
      'tmc_m': <AppLanguage, String>{
        AppLanguage.telugu: 'తమిళ మానిల కాంగ్రెస్ (మూపనార్)',
        AppLanguage.hindi: 'तमिल मानीला कांग्रेस (मूपनार)',
        AppLanguage.tamil: 'தமிழ் மாநில காங்கிரஸ் (மூப்பனார்)',
      },
      'vba': <AppLanguage, String>{
        AppLanguage.telugu: 'వంచిత్ బహుజన్ ఆఘాడీ',
        AppLanguage.hindi: 'वंचित बहुजन आघाड़ी',
        AppLanguage.marathi: 'वंचित बहुजन आघाडी',
      },
      'wpi': <AppLanguage, String>{
        AppLanguage.telugu: 'వెల్ఫేర్ పార్టీ ఆఫ్ ఇండియా',
        AppLanguage.hindi: 'वेलफेयर पार्टी ऑफ इंडिया',
        AppLanguage.malayalam: 'വെൽഫെയർ പാർട്ടി ഓഫ് ഇന്ത്യ',
      },
      'jsdl': <AppLanguage, String>{
        AppLanguage.telugu: 'జనసత్తా దళ్ (లోకతాంత్రిక్)',
        AppLanguage.hindi: 'जनसत्ता दल (लोकतांत्रिक)',
      },
    };

const List<PoliticalParty> politicalParties = <PoliticalParty>[
  PoliticalParty(
    id: 'bjp',
    name: 'Bharatiya Janata Party',
    shortName: 'BJP',
    scope: 'National Party',
    regionIds: <String>{},
  ),
  PoliticalParty(
    id: 'inc',
    name: 'Indian National Congress',
    shortName: 'INC',
    scope: 'National Party',
    regionIds: <String>{},
  ),
  PoliticalParty(
    id: 'aap',
    name: 'Aam Aadmi Party',
    shortName: 'AAP',
    scope: 'National Party',
    regionIds: <String>{},
  ),
  PoliticalParty(
    id: 'bsp',
    name: 'Bahujan Samaj Party',
    shortName: 'BSP',
    scope: 'National Party',
    regionIds: <String>{},
  ),
  PoliticalParty(
    id: 'cpi_m',
    name: 'Communist Party of India (Marxist)',
    shortName: 'CPI(M)',
    scope: 'National Party',
    regionIds: <String>{},
  ),
  PoliticalParty(
    id: 'cpi',
    name: 'Communist Party of India',
    shortName: 'CPI',
    scope: 'National Party',
    regionIds: <String>{},
  ),
  PoliticalParty(
    id: 'npp',
    name: 'National People\'s Party',
    shortName: 'NPP',
    scope: 'National Party',
    regionIds: <String>{},
  ),
  PoliticalParty(
    id: 'tdp',
    name: 'Telugu Desam Party',
    shortName: 'TDP',
    scope: 'Regional Party',
    regionIds: <String>{'andhra_pradesh', 'telangana'},
  ),
  PoliticalParty(
    id: 'ysrcp',
    name: 'YSR Congress Party',
    shortName: 'YSRCP',
    scope: 'Regional Party',
    regionIds: <String>{'andhra_pradesh'},
  ),
  PoliticalParty(
    id: 'brs',
    name: 'Bharat Rashtra Samithi',
    shortName: 'BRS',
    scope: 'Regional Party',
    regionIds: <String>{'telangana'},
  ),
  PoliticalParty(
    id: 'aitc',
    name: 'All India Trinamool Congress',
    shortName: 'AITC',
    scope: 'Regional Party',
    regionIds: <String>{'west_bengal', 'tripura', 'meghalaya'},
  ),
  PoliticalParty(
    id: 'dmk',
    name: 'Dravida Munnetra Kazhagam',
    shortName: 'DMK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu', 'puducherry'},
  ),
  PoliticalParty(
    id: 'aiadmk',
    name: 'All India Anna Dravida Munnetra Kazhagam',
    shortName: 'AIADMK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu', 'puducherry'},
  ),
  PoliticalParty(
    id: 'jds',
    name: 'Janata Dal (Secular)',
    shortName: 'JD(S)',
    scope: 'Regional Party',
    regionIds: <String>{'karnataka'},
  ),
  PoliticalParty(
    id: 'shiv_sena',
    name: 'Shiv Sena',
    shortName: 'SS',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'ncp',
    name: 'Nationalist Congress Party',
    shortName: 'NCP',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'rjd',
    name: 'Rashtriya Janata Dal',
    shortName: 'RJD',
    scope: 'Regional Party',
    regionIds: <String>{'bihar', 'jharkhand'},
  ),
  PoliticalParty(
    id: 'jdu',
    name: 'Janata Dal (United)',
    shortName: 'JD(U)',
    scope: 'Regional Party',
    regionIds: <String>{'bihar'},
  ),
  PoliticalParty(
    id: 'sp',
    name: 'Samajwadi Party',
    shortName: 'SP',
    scope: 'Regional Party',
    regionIds: <String>{'uttar_pradesh', 'uttarakhand'},
  ),
  PoliticalParty(
    id: 'rld',
    name: 'Rashtriya Lok Dal',
    shortName: 'RLD',
    scope: 'Regional Party',
    regionIds: <String>{'uttar_pradesh'},
  ),
  PoliticalParty(
    id: 'sad',
    name: 'Shiromani Akali Dal',
    shortName: 'SAD',
    scope: 'Regional Party',
    regionIds: <String>{'punjab', 'chandigarh'},
  ),
  PoliticalParty(
    id: 'bjd',
    name: 'Biju Janata Dal',
    shortName: 'BJD',
    scope: 'Regional Party',
    regionIds: <String>{'odisha'},
  ),
  PoliticalParty(
    id: 'jmm',
    name: 'Jharkhand Mukti Morcha',
    shortName: 'JMM',
    scope: 'Regional Party',
    regionIds: <String>{'jharkhand'},
  ),
  PoliticalParty(
    id: 'skm',
    name: 'Sikkim Krantikari Morcha',
    shortName: 'SKM',
    scope: 'Regional Party',
    regionIds: <String>{'sikkim'},
  ),
  PoliticalParty(
    id: 'mnf',
    name: 'Mizo National Front',
    shortName: 'MNF',
    scope: 'Regional Party',
    regionIds: <String>{'mizoram'},
  ),
  PoliticalParty(
    id: 'npf',
    name: 'Naga People\'s Front',
    shortName: 'NPF',
    scope: 'Regional Party',
    regionIds: <String>{'nagaland', 'manipur'},
  ),
  PoliticalParty(
    id: 'jknc',
    name: 'National Conference',
    shortName: 'JKNC',
    scope: 'Regional Party',
    regionIds: <String>{'jammu_kashmir', 'ladakh'},
  ),
  PoliticalParty(
    id: 'pdp',
    name: 'Peoples Democratic Party',
    shortName: 'PDP',
    scope: 'Regional Party',
    regionIds: <String>{'jammu_kashmir'},
  ),
  PoliticalParty(
    id: 'agp',
    name: 'Asom Gana Parishad',
    shortName: 'AGP',
    scope: 'Regional Party',
    regionIds: <String>{'assam'},
  ),
  PoliticalParty(
    id: 'udp',
    name: 'United Democratic Party',
    shortName: 'UDP',
    scope: 'Regional Party',
    regionIds: <String>{'meghalaya'},
  ),
  PoliticalParty(
    id: 'tmp',
    name: 'Tipra Motha Party',
    shortName: 'TMP',
    scope: 'Regional Party',
    regionIds: <String>{'tripura'},
  ),
  PoliticalParty(
    id: 'mgp',
    name: 'Maharashtrawadi Gomantak Party',
    shortName: 'MGP',
    scope: 'Regional Party',
    regionIds: <String>{'goa'},
  ),
  PoliticalParty(
    id: 'inld',
    name: 'Indian National Lok Dal',
    shortName: 'INLD',
    scope: 'Regional Party',
    regionIds: <String>{'haryana'},
  ),
  PoliticalParty(
    id: 'jjp',
    name: 'Jannayak Janta Party',
    shortName: 'JJP',
    scope: 'Regional Party',
    regionIds: <String>{'haryana'},
  ),
  PoliticalParty(
    id: 'aifb',
    name: 'All India Forward Bloc',
    shortName: 'AIFB',
    scope: 'Regional Party',
    regionIds: <String>{'west_bengal'},
  ),
  PoliticalParty(
    id: 'rsp',
    name: 'Revolutionary Socialist Party',
    shortName: 'RSP',
    scope: 'Regional Party',
    regionIds: <String>{'kerala', 'west_bengal', 'tripura'},
  ),
  PoliticalParty(
    id: 'iuml',
    name: 'Indian Union Muslim League',
    shortName: 'IUML',
    scope: 'Regional Party',
    regionIds: <String>{'kerala'},
  ),
  PoliticalParty(
    id: 'kc_m',
    name: 'Kerala Congress (M)',
    shortName: 'KC(M)',
    scope: 'Regional Party',
    regionIds: <String>{'kerala'},
  ),
  PoliticalParty(
    id: 'kc',
    name: 'Kerala Congress',
    shortName: 'KC',
    scope: 'Regional Party',
    regionIds: <String>{'kerala'},
  ),
  PoliticalParty(
    id: 'cpi_ml_l',
    name: 'Communist Party of India (Marxist-Leninist) Liberation',
    shortName: 'CPI(ML)L',
    scope: 'Regional Party',
    regionIds: <String>{'bihar'},
  ),
  PoliticalParty(
    id: 'aimim',
    name: 'All India Majlis-e-Ittehadul Muslimeen',
    shortName: 'AIMIM',
    scope: 'Regional Party',
    regionIds: <String>{'telangana', 'maharashtra'},
  ),
  PoliticalParty(
    id: 'ajsupa',
    name: 'AJSU Party',
    shortName: 'AJSU',
    scope: 'Regional Party',
    regionIds: <String>{'jharkhand'},
  ),
  PoliticalParty(
    id: 'ad_s',
    name: 'Apna Dal (Soneylal)',
    shortName: 'AD(S)',
    scope: 'Regional Party',
    regionIds: <String>{'uttar_pradesh'},
  ),
  PoliticalParty(
    id: 'ljp_rv',
    name: 'Lok Janshakti Party (Ram Vilas)',
    shortName: 'LJP(RV)',
    scope: 'Regional Party',
    regionIds: <String>{'bihar'},
  ),
  PoliticalParty(
    id: 'rljp',
    name: 'Rashtriya Lok Janshakti Party',
    shortName: 'RLJP',
    scope: 'Regional Party',
    regionIds: <String>{'bihar'},
  ),
  PoliticalParty(
    id: 'ham_s',
    name: 'Hindustani Awam Morcha (Secular)',
    shortName: 'HAM(S)',
    scope: 'Regional Party',
    regionIds: <String>{'bihar'},
  ),
  PoliticalParty(
    id: 'vip',
    name: 'Vikassheel Insaan Party',
    shortName: 'VIP',
    scope: 'Regional Party',
    regionIds: <String>{'bihar'},
  ),
  PoliticalParty(
    id: 'jsp',
    name: 'Jana Sena Party',
    shortName: 'JSP',
    scope: 'Regional Party',
    regionIds: <String>{'andhra_pradesh', 'telangana'},
  ),
  PoliticalParty(
    id: 'ntk',
    name: 'Naam Tamilar Katchi',
    shortName: 'NTK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu', 'puducherry'},
  ),
  PoliticalParty(
    id: 'pmk',
    name: 'Pattali Makkal Katchi',
    shortName: 'PMK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu', 'puducherry'},
  ),
  PoliticalParty(
    id: 'vck',
    name: 'Viduthalai Chiruthaigal Katchi',
    shortName: 'VCK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu', 'puducherry'},
  ),
  PoliticalParty(
    id: 'mdmk',
    name: 'Marumalarchi Dravida Munnetra Kazhagam',
    shortName: 'MDMK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu'},
  ),
  PoliticalParty(
    id: 'dmdk',
    name: 'Desiya Murpokku Dravida Kazhagam',
    shortName: 'DMDK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu'},
  ),
  PoliticalParty(
    id: 'aiudf',
    name: 'All India United Democratic Front',
    shortName: 'AIUDF',
    scope: 'Regional Party',
    regionIds: <String>{'assam'},
  ),
  PoliticalParty(
    id: 'bpf',
    name: 'Bodoland People\'s Front',
    shortName: 'BPF',
    scope: 'Regional Party',
    regionIds: <String>{'assam'},
  ),
  PoliticalParty(
    id: 'uppl',
    name: 'United People\'s Party Liberal',
    shortName: 'UPPL',
    scope: 'Regional Party',
    regionIds: <String>{'assam'},
  ),
  PoliticalParty(
    id: 'zpm',
    name: 'Zoram People\'s Movement',
    shortName: 'ZPM',
    scope: 'Regional Party',
    regionIds: <String>{'mizoram'},
  ),
  PoliticalParty(
    id: 'ndpp',
    name: 'Nationalist Democratic Progressive Party',
    shortName: 'NDPP',
    scope: 'Regional Party',
    regionIds: <String>{'nagaland'},
  ),
  PoliticalParty(
    id: 'ipft',
    name: 'Indigenous People\'s Front of Tripura',
    shortName: 'IPFT',
    scope: 'Regional Party',
    regionIds: <String>{'tripura'},
  ),
  PoliticalParty(
    id: 'rgp',
    name: 'Revolutionary Goans Party',
    shortName: 'RGP',
    scope: 'Regional Party',
    regionIds: <String>{'goa'},
  ),
  PoliticalParty(
    id: 'gfp',
    name: 'Goa Forward Party',
    shortName: 'GFP',
    scope: 'Regional Party',
    regionIds: <String>{'goa'},
  ),
  PoliticalParty(
    id: 'hspdp',
    name: 'Hill State People\'s Democratic Party',
    shortName: 'HSPDP',
    scope: 'Regional Party',
    regionIds: <String>{'meghalaya'},
  ),
  PoliticalParty(
    id: 'vpp',
    name: 'Voice of the People Party',
    shortName: 'VPP',
    scope: 'Regional Party',
    regionIds: <String>{'meghalaya'},
  ),
  PoliticalParty(
    id: 'ppa',
    name: 'People\'s Party of Arunachal',
    shortName: 'PPA',
    scope: 'Regional Party',
    regionIds: <String>{'arunachal_pradesh'},
  ),
  PoliticalParty(
    id: 'bap',
    name: 'Bharat Adivasi Party',
    shortName: 'BAP',
    scope: 'Regional Party',
    regionIds: <String>{'rajasthan'},
  ),
  PoliticalParty(
    id: 'rpi_a',
    name: 'Republican Party of India (A)',
    shortName: 'RPI(A)',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'mns',
    name: 'Maharashtra Navnirman Sena',
    shortName: 'MNS',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'swabhimani',
    name: 'Swabhimani Paksha',
    shortName: 'SWP',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'prahar',
    name: 'Prahar Janshakti Party',
    shortName: 'PJP',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'sdf',
    name: 'Sikkim Democratic Front',
    shortName: 'SDF',
    scope: 'Regional Party',
    regionIds: <String>{'sikkim'},
  ),
  PoliticalParty(
    id: 'rlp',
    name: 'Rashtriya Loktantrik Party',
    shortName: 'RLP',
    scope: 'Regional Party',
    regionIds: <String>{'rajasthan'},
  ),
  PoliticalParty(
    id: 'sbsp',
    name: 'Suheldev Bharatiya Samaj Party',
    shortName: 'SBSP',
    scope: 'Regional Party',
    regionIds: <String>{'uttar_pradesh'},
  ),
  PoliticalParty(
    id: 'ncp_sp',
    name: 'Nationalist Congress Party - Sharadchandra Pawar',
    shortName: 'NCP(SP)',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra', 'nagaland'},
  ),
  PoliticalParty(
    id: 'shs_ubt',
    name: 'Shiv Sena (Uddhav Balasaheb Thackeray)',
    shortName: 'SHS(UBT)',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'jkpc',
    name: 'Jammu and Kashmir People\'s Conference',
    shortName: 'JKPC',
    scope: 'Regional Party',
    regionIds: <String>{'jammu_kashmir'},
  ),
  PoliticalParty(
    id: 'kpa',
    name: 'Kuki People\'s Alliance',
    shortName: 'KPA',
    scope: 'Regional Party',
    regionIds: <String>{'manipur'},
  ),
  PoliticalParty(
    id: 'ukd',
    name: 'Uttarakhand Kranti Dal',
    shortName: 'UKD',
    scope: 'Regional Party',
    regionIds: <String>{'uttarakhand'},
  ),
  PoliticalParty(
    id: 'jccj',
    name: 'Janta Congress Chhattisgarh (J)',
    shortName: 'JCC(J)',
    scope: 'Regional Party',
    regionIds: <String>{'chhattisgarh'},
  ),
  PoliticalParty(
    id: 'tvk',
    name: 'Tamilaga Vettri Kazhagam',
    shortName: 'TVK',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu', 'puducherry'},
  ),
  PoliticalParty(
    id: 'tmc_m',
    name: 'Tamil Maanila Congress (Moopanar)',
    shortName: 'TMC(M)',
    scope: 'Regional Party',
    regionIds: <String>{'tamil_nadu'},
  ),
  PoliticalParty(
    id: 'vba',
    name: 'Vanchit Bahujan Aaghadi',
    shortName: 'VBA',
    scope: 'Regional Party',
    regionIds: <String>{'maharashtra'},
  ),
  PoliticalParty(
    id: 'wpi',
    name: 'Welfare Party of India',
    shortName: 'WPI',
    scope: 'Regional Party',
    regionIds: <String>{'kerala'},
  ),
  PoliticalParty(
    id: 'jsdl',
    name: 'Jansatta Dal (Loktantrik)',
    shortName: 'JSDL',
    scope: 'Regional Party',
    regionIds: <String>{'uttar_pradesh'},
  ),
];

List<PoliticalParty> partiesForRegion(String regionId) {
  return politicalParties
      .where((party) => party.isRelevantTo(regionId))
      .toList(growable: false);
}
